// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::consts;

#[derive(Default)]
pub(super) struct AcData {
    pub(super) a: u32,
    pub(super) c: u32,
    pub(super) cbptr: i32,
}

impl AcData {
    pub(super) fn init(&mut self, cb: &[u8], fs: i32) {
        self.a = consts::ONE - 1;
        self.c = 0;
        self.cbptr = 1;
        while self.cbptr <= consts::ABITS as i32 {
            self.c <<= 1;
            if self.cbptr < fs {
                self.c |= cb[self.cbptr as usize] as u32;
            }
            self.cbptr += 1;
        }
    }

    #[inline]
    pub(super) fn decode_bit(&mut self, p: i32, cb: &[u8], fs: i32) -> u8 {
        // approximate (A * p) with "partial rounding"
        let ap = ((self.a >> consts::PBITS) | ((self.a >> (consts::PBITS - 1)) & 1)) * p as u32;
        let h = self.a - ap;
        let b = if self.c >= h {
            self.c -= h;
            self.a = ap;
            0u8
        } else {
            self.a = h;
            1u8
        };
        // Renormalize. `cb` is zero-padded past `fs` by the caller, so the
        // bounds check the C reference does (`if cbptr < fs`) is unnecessary
        // — past-end reads return 0, matching the spec's "insert zero in LSB
        // of C" rule.
        let _ = fs;
        while self.a < consts::HALF {
            self.a <<= 1;
            let bit = cb.get(self.cbptr as usize).copied().unwrap_or(0);
            self.c = (self.c << 1) | u32::from(bit);
            self.cbptr += 1;
        }
        b
    }

    /// Validate trailing bits at end-of-frame. Returns 1 on success (matches C).
    pub(super) fn flush(&mut self, cb: &[u8], fs: i32) -> u8 {
        let mut b: u8;
        if self.cbptr < fs - 7 {
            b = 0;
        } else {
            b = 1;
            while self.cbptr < fs && b == 1 {
                if cb[self.cbptr as usize] != 0 {
                    b = 1;
                }
                self.cbptr += 1;
            }
        }
        b
    }
}
