// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::error::DstError;
use anyhow::{Result, bail};

pub(super) struct BitReader<'a> {
    pub(super) data: &'a [u8],
    /// Bit position (0..8). 0 means a fresh byte must be loaded.
    pub(super) bit_position: u8,
    /// Index of next byte to read from `data`.
    pub(super) byte_counter: usize,
    pub(super) data_byte: u8,
}

impl<'a> BitReader<'a> {
    pub(super) fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            bit_position: 0,
            byte_counter: 0,
            data_byte: 0,
        }
    }

    pub(super) fn fetch_byte(&mut self) -> Result<()> {
        if self.byte_counter >= self.data.len() {
            bail!(DstError::NegativeBitAllocation);
        }
        self.data_byte = self.data[self.byte_counter];
        self.byte_counter += 1;
        self.bit_position = 8;
        Ok(())
    }

    pub(super) fn read_bit(&mut self) -> Result<u8> {
        if self.bit_position == 0 {
            self.fetch_byte()?;
        }
        self.bit_position -= 1;
        Ok((self.data_byte >> self.bit_position) & 1)
    }

    pub(super) fn read_uint(&mut self, len: usize) -> Result<u32> {
        if len == 0 {
            return Ok(0);
        }
        let mut out: u32 = 0;
        let mut remaining = len;
        while remaining > 0 {
            if self.bit_position == 0 {
                self.fetch_byte()?;
            }
            let take = (self.bit_position as usize).min(remaining);
            let shift = self.bit_position as usize - take;
            let mask: u32 = ((1u32 << take) - 1) << shift;
            let bits = ((self.data_byte as u32) & mask) >> shift;
            out = (out << take) | bits;
            self.bit_position -= take as u8;
            remaining -= take;
        }
        Ok(out)
    }

    pub(super) fn read_int(&mut self, len: usize) -> Result<i32> {
        let mut v = self.read_uint(len)? as i32;
        if len > 0 && v >= (1 << (len - 1)) {
            v -= 1 << len;
        }
        Ok(v)
    }

    pub(super) fn read_short_signed(&mut self, len: usize) -> Result<i16> {
        Ok(self.read_int(len)? as i16)
    }

    pub(super) fn read_byte(&mut self) -> Result<u8> {
        Ok(self.read_uint(8)? as u8)
    }

    pub(super) fn bit_count(&self) -> i64 {
        self.byte_counter as i64 * 8 - self.bit_position as i64
    }
}

pub(super) fn rice_decode(reader: &mut BitReader, m: i32) -> Result<i32> {
    // Run length: count leading zeros until a 1 bit.
    let mut run_length = 0i32;
    loop {
        let b = reader.read_uint(1)? as i32;
        run_length += 1 - b;
        if b == 1 {
            break;
        }
    }
    let lsbs = reader.read_uint(m as usize)? as i32;
    let mut nr = (run_length << m) + lsbs;
    if nr != 0 {
        let sign = reader.read_uint(1)? as i32;
        if sign == 1 {
            nr = -nr;
        }
    }
    Ok(nr)
}
