// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::TableType;
use crate::consts;

pub(super) struct CodedTable {
    /// CPredOrder[Method], length = max(NROFFRICEMETHODS, NROFPRICEMETHODS).
    pub(super) c_pred_order: [i32; 4],
    /// CPredCoef[Method][CoefNr]
    pub(super) c_pred_coef: [[i32; consts::MAXCPREDORDER]; 4],
    /// Coded[FilterNr or PtableNr]
    pub(super) coded: Vec<i32>,
    /// BestMethod[FilterNr or PtableNr]
    pub(super) best_method: Vec<i32>,
    /// m[FilterNr or PtableNr][Method]
    pub(super) m: Vec<[i32; 4]>,
    /// FILTER or PTABLE
    pub(super) table_type: TableType,
}

impl CodedTable {
    pub(super) fn new(table_type: TableType, max_tables: usize) -> Self {
        let mut t = Self {
            c_pred_order: [0; 4],
            c_pred_coef: [[0; consts::MAXCPREDORDER]; 4],
            coded: vec![0; max_tables],
            best_method: vec![-1; max_tables],
            m: vec![[0; 4]; max_tables],
            table_type,
        };
        t.ccp_calc_init();
        t
    }

    /// CCP_CalcInit from ccp_calc.c.
    pub(super) fn ccp_calc_init(&mut self) {
        match self.table_type {
            TableType::Filter => {
                // Method 0
                self.c_pred_order[0] = 1;
                self.c_pred_coef[0] = [-8, 0, 0];
                // Method 1
                self.c_pred_order[1] = 2;
                self.c_pred_coef[1] = [-16, 8, 0];
                // Method 2
                self.c_pred_order[2] = 3;
                self.c_pred_coef[2] = [-9, -5, 6];
            }
            TableType::Ptable => {
                self.c_pred_order[0] = 1;
                self.c_pred_coef[0] = [-8, 0, 0];
                self.c_pred_order[1] = 2;
                self.c_pred_coef[1] = [-16, 8, 0];
                self.c_pred_order[2] = 3;
                self.c_pred_coef[2] = [-24, 24, -8];
            }
        }
    }
}
