// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::ac_data::AcData;
use super::bit_reader::BitReader;
use super::bit_reader::rice_decode;
use super::coded_table::CodedTable;
use super::error::DstError;
use super::fir::fir_predict;
use super::max::max_nr_of_filters;
use super::max::max_nr_of_ptables;
use super::misc::ac_get_ptable_index;
use super::misc::log2_round_up;
use super::misc::reverse7_lsbs;
use super::segment::Segment;
use super::types::FrameHeader;
use super::types::TableType;
use crate::consts;
use anyhow::{Result, bail};

/// Stateful decoder for MPEG-4 DST frames.
///
/// One instance decodes any number of frames sequentially for a fixed
/// channel count and DSD sample rate. The decoder holds preallocated
/// scratch buffers sized at construction, so per-frame decoding does not
/// allocate on the hot path. Instances are not internally synchronised;
/// for parallel decoding, use one decoder per thread.
///
/// # Example
///
/// ```no_run
/// use dst_decoder::decoder::DstDecoder;
///
/// let mut decoder = DstDecoder::new(2, 2_822_400).unwrap();
/// let mut dsd = vec![0u8; decoder.dsd_frame_bytes()];
/// # let dst_frame: &[u8] = &[];
/// let written = decoder.decode_frame(dst_frame, &mut dsd).unwrap();
/// assert_eq!(written, decoder.dsd_frame_bytes());
/// ```
pub struct DstDecoder {
    pub(super) frame_hdr: FrameHeader,
    pub(super) str_filter: CodedTable,
    pub(super) str_ptable: CodedTable,
    /// P_one[PtableNr][EntryNr]
    pub(super) p_one: Vec<[i32; consts::AC_HISMAX]>,
    /// AData buffer: one bit per byte (0 or 1).
    pub(super) a_data: Vec<u8>,
    pub(super) a_data_len: i32,
    /// Filter4Bit, flat row-major as `[ch * bits_per_ch_stride + bit]`,
    /// filled per-frame. One allocation instead of `MAX_CHANNELS` separate
    /// heap blocks for cache locality and to drop the inner-Vec metadata
    /// from the hot path.
    pub(super) filter4_bit: Vec<u8>,
    /// Ptable4Bit, flat row-major; same layout as `filter4_bit`.
    pub(super) ptable4_bit: Vec<u8>,
    /// FIR lookup tables, reused and refilled per frame.
    pub(super) filter_tables: Vec<[[i16; 256]; 16]>,
    /// Per-channel row stride for `filter4_bit` / `ptable4_bit`. Equals
    /// `nr_of_bits_per_ch` and is constant for the decoder's lifetime
    /// (derived from the sample rate at construction).
    pub(super) bits_per_ch_stride: usize,
    pub(super) channel_count: usize,
    /// Whether the current CPU advertises AVX2; cached at construction so
    /// the per-bit FIR dispatch is one predicted branch instead of a
    /// `cpuid` call.
    pub(super) has_avx2: bool,
}

impl DstDecoder {
    /// Construct a decoder for a stream with the given channel count and
    /// DSD sample rate.
    ///
    /// `channel_count` must be in `1..=MAX_CHANNELS` (6). `sample_rate`
    /// must be one of the three DSD rates the spec defines: 2_822_400
    /// (DSD64), 5_644_800 (DSD128), or 11_289_600 (DSD256). Any other
    /// value is rejected.
    ///
    /// On construction the decoder allocates its full scratch space (FIR
    /// status tables, AC buffers, per-bit table maps), sized from these
    /// two parameters; subsequent [`decode_frame`](Self::decode_frame)
    /// calls do no further heap work.
    ///
    /// # Errors
    ///
    /// Returns an error if `channel_count` is out of range or
    /// `sample_rate` is not a supported DSD rate.
    pub fn new(channel_count: usize, sample_rate: usize) -> Result<Self> {
        if channel_count == 0 || channel_count > consts::MAX_CHANNELS {
            bail!("Invalid channel count: {}", channel_count);
        }
        // The C reference computes MaxFrameLen as `588 * SampleRate / 8`
        // where SampleRate is an Fs44 multiplier (64/128/256). Validate
        // and translate the Hz value here; we don't need to retain it.
        let fsample_44: i64 = match sample_rate as u32 {
            consts::DSD64_SAMPLE_RATE => 64,
            consts::DSD128_SAMPLE_RATE => 128,
            consts::DSD256_SAMPLE_RATE => 256,
            _ => bail!("Unsupported sample rate: {}", sample_rate),
        };
        let max_frame_len = 588 * fsample_44 / 8;
        let nr_of_bits_per_ch = max_frame_len * consts::RESOL;
        let max_nr_of_filters = max_nr_of_filters(channel_count);
        let max_nr_of_ptables = max_nr_of_ptables(channel_count);

        Ok(Self {
            frame_hdr: FrameHeader {
                nr_of_channels: channel_count as i32,
                pred_order: vec![0; max_nr_of_filters],
                ptable_len: vec![0; max_nr_of_ptables],
                i_coef_a: vec![vec![0; 1 << consts::SIZE_CODEDPREDORDER]; max_nr_of_filters],
                max_nr_of_filters: max_nr_of_filters as i32,
                max_nr_of_ptables: max_nr_of_ptables as i32,
                max_frame_len,
                nr_of_bits_per_ch,
                ..Default::default()
            },
            str_filter: CodedTable::new(TableType::Filter, max_nr_of_filters),
            str_ptable: CodedTable::new(TableType::Ptable, max_nr_of_ptables),
            p_one: vec![[0; consts::AC_HISMAX]; max_nr_of_ptables],
            a_data: Vec::new(),
            a_data_len: 0,
            filter4_bit: vec![0u8; (nr_of_bits_per_ch as usize) * consts::MAX_CHANNELS],
            ptable4_bit: vec![0u8; (nr_of_bits_per_ch as usize) * consts::MAX_CHANNELS],
            filter_tables: vec![[[0i16; 256]; 16]; max_nr_of_filters],
            bits_per_ch_stride: nr_of_bits_per_ch as usize,
            channel_count,
            #[cfg(target_arch = "x86_64")]
            has_avx2: std::is_x86_feature_detected!("avx2"),
            #[cfg(not(target_arch = "x86_64"))]
            has_avx2: false,
        })
    }

    /// Number of DSD bytes a single decoded frame occupies.
    ///
    /// Equal to `max_frame_len * channel_count`, where `max_frame_len`
    /// is `588 * Fs44 / 8` per the MPEG-4 DST spec (Fs44 ∈ {64, 128,
    /// 256}). Use this to size the output buffer passed to
    /// [`decode_frame`](Self::decode_frame).
    pub fn dsd_frame_bytes(&self) -> usize {
        (self.frame_hdr.max_frame_len as usize) * self.channel_count
    }

    /// Decode one DST frame into channel-interleaved DSD bytes.
    ///
    /// `dst_data` is the compressed frame payload (the DST elementary
    /// stream unit, without any container framing). `dsd_data` must be
    /// at least [`dsd_frame_bytes`](Self::dsd_frame_bytes) long; on
    /// success the first that-many bytes are filled with DSD samples,
    /// channel-interleaved at byte granularity (eight samples per byte,
    /// MSB first). Trailing bytes in an oversized buffer are left
    /// untouched.
    ///
    /// The decoder transparently handles both DST-coded frames (the
    /// common case) and uncompressed DSD frames (per the spec's escape
    /// hatch).
    ///
    /// # Returns
    ///
    /// Number of DSD bytes written, always equal to
    /// [`dsd_frame_bytes`](Self::dsd_frame_bytes).
    ///
    /// # Errors
    ///
    /// Returns an error if `dsd_data` is too small, or if the frame is
    /// malformed. On decode failure the output buffer is overwritten
    /// with `0x55` (DSD silence) — matching the C reference's behaviour
    /// — so a caller that ignores the error still gets a deterministic
    /// frame of silence rather than garbage. The underlying error
    /// downcasts to [`DstError`] for malformed-bitstream cases.
    pub fn decode_frame(&mut self, dst_data: &[u8], dsd_data: &mut [u8]) -> Result<usize> {
        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        let max_frame_len = self.frame_hdr.max_frame_len;
        let nr_of_bits_per_ch = self.frame_hdr.nr_of_bits_per_ch as usize;
        let total_dsd_bytes = (nr_of_bits_per_ch * nr_of_channels) / 8;

        if dsd_data.len() < total_dsd_bytes {
            bail!(
                "DSD output buffer too small: need {}, got {}",
                total_dsd_bytes,
                dsd_data.len()
            );
        }

        self.frame_hdr.calc_nr_of_bytes = dst_data.len() as i64;
        self.frame_hdr.calc_nr_of_bits = self.frame_hdr.calc_nr_of_bytes * 8;

        let res = self.unpack_dst_frame(dst_data, dsd_data);
        if let Err(e) = res {
            // On error C returns DSD silence (0x55) for the whole frame.
            for b in &mut dsd_data[..total_dsd_bytes] {
                *b = 0x55;
            }
            return Err(e);
        }

        if self.frame_hdr.dst_coded == 0 {
            // Uncompressed DSD already written into dsd_data.
            return Ok((max_frame_len * nr_of_channels as i64) as usize);
        }

        // DST-coded: run filter loop.
        let bytes = self.decode_dsd_samples(dsd_data)?;
        Ok(bytes)
    }

    // ------------------------------------------------------------
    // UnpackDSTframe
    // ------------------------------------------------------------
    pub(super) fn unpack_dst_frame(&mut self, dst_data: &[u8], dsd_data: &mut [u8]) -> Result<()> {
        let mut reader = BitReader::new(dst_data);

        self.frame_hdr.dst_coded = reader.read_uint(1)? as i32;

        if self.frame_hdr.dst_coded == 0 {
            // 1 bit dummy + 6 bits stuffing pattern (must be zero).
            let _ = reader.read_uint(1)?;
            let stuffing = reader.read_uint(6)?;
            if stuffing != 0 {
                bail!(DstError::InvalidStuffingPattern);
            }
            self.read_dsd_frame(&mut reader, dsd_data)?;
            return Ok(());
        }

        self.read_segment_data(&mut reader)?;
        self.read_mapping_data(&mut reader)?;
        self.read_filter_coef_sets(&mut reader)?;
        self.read_probability_tables(&mut reader)?;

        // ADataLen = total bits - bits already read.
        self.a_data_len = (self.frame_hdr.calc_nr_of_bits - reader.bit_count()) as i32;
        self.read_arithmetic_coded_data(&mut reader)?;

        if self.a_data_len > 0 && self.a_data[0] != 0 {
            bail!(DstError::InvalidArithmeticCode);
        }
        Ok(())
    }

    pub(super) fn read_dsd_frame(&self, reader: &mut BitReader, dsd_data: &mut [u8]) -> Result<()> {
        let max = (self.frame_hdr.max_frame_len * self.frame_hdr.nr_of_channels as i64) as usize;
        for byte in dsd_data.iter_mut().take(max) {
            *byte = reader.read_byte()?;
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // Segmentation
    // ------------------------------------------------------------
    pub(super) fn read_segment_data(&mut self, reader: &mut BitReader) -> Result<()> {
        self.frame_hdr.p_same_seg_as_f = reader.read_uint(1)? as i32;

        Self::read_table_segment_data(
            reader,
            self.frame_hdr.nr_of_channels as usize,
            self.frame_hdr.max_frame_len as i32,
            consts::MAXNROF_FSEGS,
            consts::MIN_FSEG_LEN,
            &mut self.frame_hdr.f_seg,
            &mut self.frame_hdr.f_same_seg_all_ch,
        )?;

        if self.frame_hdr.p_same_seg_as_f == 1 {
            self.copy_segment_data()?;
        } else {
            Self::read_table_segment_data(
                reader,
                self.frame_hdr.nr_of_channels as usize,
                self.frame_hdr.max_frame_len as i32,
                consts::MAXNROF_PSEGS,
                consts::MIN_PSEG_LEN,
                &mut self.frame_hdr.p_seg,
                &mut self.frame_hdr.p_same_seg_all_ch,
            )?;
        }
        Ok(())
    }

    pub(super) fn read_table_segment_data(
        reader: &mut BitReader,
        nr_of_channels: usize,
        frame_len: i32,
        max_nr_of_segs: i32,
        min_seg_len: i32,
        s: &mut Segment,
        same_seg_all_ch: &mut i32,
    ) -> Result<()> {
        let mut defined_bits: i32 = 0;
        let mut resol_read = false;
        let mut seg_nr: i32 = 0;
        let mut max_seg_size: i32 = frame_len - min_seg_len / 8;

        *same_seg_all_ch = reader.read_uint(1)? as i32;
        if *same_seg_all_ch == 1 {
            let mut end_of_channel = reader.read_uint(1)? as i32;
            while end_of_channel == 0 {
                if seg_nr >= max_nr_of_segs {
                    bail!(DstError::TooManySegments);
                }
                if !resol_read {
                    let nbits = log2_round_up((frame_len - min_seg_len / 8) as u32);
                    s.resolution = reader.read_uint(nbits)? as i32;
                    if s.resolution == 0 || s.resolution > frame_len - min_seg_len / 8 {
                        bail!(DstError::InvalidSegmentResolution);
                    }
                    resol_read = true;
                }
                let nbits = log2_round_up((max_seg_size / s.resolution) as u32);
                let len = reader.read_uint(nbits)? as i32;
                s.segment_len[0][seg_nr as usize] = len;
                if s.resolution * 8 * len < min_seg_len
                    || s.resolution * 8 * len > frame_len * 8 - defined_bits - min_seg_len
                {
                    bail!(DstError::InvalidSegmentLength);
                }
                defined_bits += s.resolution * 8 * len;
                max_seg_size -= s.resolution * len;
                seg_nr += 1;
                end_of_channel = reader.read_uint(1)? as i32;
            }
            s.nr_of_segments[0] = seg_nr + 1;
            s.segment_len[0][seg_nr as usize] = 0;
            for ch in 1..nr_of_channels {
                s.nr_of_segments[ch] = s.nr_of_segments[0];
                for i in 0..s.nr_of_segments[0] as usize {
                    s.segment_len[ch][i] = s.segment_len[0][i];
                }
            }
        } else {
            let mut ch_nr = 0usize;
            while ch_nr < nr_of_channels {
                if seg_nr >= max_nr_of_segs {
                    bail!(DstError::TooManySegments);
                }
                let end_of_channel = reader.read_uint(1)? as i32;
                if end_of_channel == 0 {
                    if !resol_read {
                        let nbits = log2_round_up((frame_len - min_seg_len / 8) as u32);
                        s.resolution = reader.read_uint(nbits)? as i32;
                        if s.resolution == 0 || s.resolution > frame_len - min_seg_len / 8 {
                            bail!(DstError::InvalidSegmentResolution);
                        }
                        resol_read = true;
                    }
                    let nbits = log2_round_up((max_seg_size / s.resolution) as u32);
                    let len = reader.read_uint(nbits)? as i32;
                    s.segment_len[ch_nr][seg_nr as usize] = len;
                    if s.resolution * 8 * len < min_seg_len
                        || s.resolution * 8 * len > frame_len * 8 - defined_bits - min_seg_len
                    {
                        bail!(DstError::InvalidSegmentLength);
                    }
                    defined_bits += s.resolution * 8 * len;
                    max_seg_size -= s.resolution * len;
                    seg_nr += 1;
                } else {
                    s.nr_of_segments[ch_nr] = seg_nr + 1;
                    s.segment_len[ch_nr][seg_nr as usize] = 0;
                    seg_nr = 0;
                    defined_bits = 0;
                    max_seg_size = frame_len - min_seg_len / 8;
                    ch_nr += 1;
                }
            }
        }
        if !resol_read {
            s.resolution = 1;
        }
        Ok(())
    }

    pub(super) fn copy_segment_data(&mut self) -> Result<()> {
        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        self.frame_hdr.p_seg.resolution = self.frame_hdr.f_seg.resolution;
        self.frame_hdr.p_same_seg_all_ch = 1;
        for ch in 0..nr_of_channels {
            self.frame_hdr.p_seg.nr_of_segments[ch] = self.frame_hdr.f_seg.nr_of_segments[ch];
            if self.frame_hdr.p_seg.nr_of_segments[ch] > consts::MAXNROF_PSEGS {
                bail!(DstError::TooManySegments);
            }
            if self.frame_hdr.p_seg.nr_of_segments[ch] != self.frame_hdr.p_seg.nr_of_segments[0] {
                self.frame_hdr.p_same_seg_all_ch = 0;
            }
            for seg in 0..self.frame_hdr.p_seg.nr_of_segments[ch] as usize {
                let len = self.frame_hdr.f_seg.segment_len[ch][seg];
                self.frame_hdr.p_seg.segment_len[ch][seg] = len;
                if len != 0 && self.frame_hdr.p_seg.resolution * 8 * len < consts::MIN_PSEG_LEN {
                    bail!(DstError::InvalidSegmentLength);
                }
                if len != self.frame_hdr.p_seg.segment_len[0][seg] {
                    self.frame_hdr.p_same_seg_all_ch = 0;
                }
            }
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // Mapping
    // ------------------------------------------------------------
    pub(super) fn read_mapping_data(&mut self, reader: &mut BitReader) -> Result<()> {
        self.frame_hdr.p_same_map_as_f = reader.read_uint(1)? as i32;

        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        let max_nr_of_filters = self.frame_hdr.max_nr_of_filters;
        let max_nr_of_ptables = self.frame_hdr.max_nr_of_ptables;

        let mut nr_of_filters = 0i32;
        Self::read_table_mapping_data(
            reader,
            nr_of_channels,
            max_nr_of_filters,
            &mut self.frame_hdr.f_seg,
            &mut nr_of_filters,
            &mut self.frame_hdr.f_same_map_all_ch,
        )?;
        self.frame_hdr.nr_of_filters = nr_of_filters;

        if self.frame_hdr.p_same_map_as_f == 1 {
            self.copy_mapping_data()?;
        } else {
            let mut nr_of_ptables = 0i32;
            Self::read_table_mapping_data(
                reader,
                nr_of_channels,
                max_nr_of_ptables,
                &mut self.frame_hdr.p_seg,
                &mut nr_of_ptables,
                &mut self.frame_hdr.p_same_map_all_ch,
            )?;
            self.frame_hdr.nr_of_ptables = nr_of_ptables;
        }

        // HalfProb per channel.
        for ch in 0..nr_of_channels {
            self.frame_hdr.half_prob[ch] = reader.read_uint(1)? as i32;
        }
        Ok(())
    }

    pub(super) fn read_table_mapping_data(
        reader: &mut BitReader,
        nr_of_channels: usize,
        max_nr_of_tables: i32,
        s: &mut Segment,
        nr_of_tables: &mut i32,
        same_map_all_ch: &mut i32,
    ) -> Result<()> {
        let mut count_tables: i32 = 1;

        s.table4_segment[0][0] = 0;
        *same_map_all_ch = reader.read_uint(1)? as i32;
        if *same_map_all_ch == 1 {
            for seg_nr in 1..s.nr_of_segments[0] as usize {
                let nbits = log2_round_up(count_tables as u32);
                let v = reader.read_uint(nbits)? as i32;
                s.table4_segment[0][seg_nr] = v;
                if v == count_tables {
                    count_tables += 1;
                } else if v > count_tables {
                    bail!(DstError::InvalidTableNumber);
                }
            }
            for ch in 1..nr_of_channels {
                if s.nr_of_segments[ch] != s.nr_of_segments[0] {
                    bail!(DstError::InvalidChannelMapping);
                }
                for seg in 0..s.nr_of_segments[0] as usize {
                    s.table4_segment[ch][seg] = s.table4_segment[0][seg];
                }
            }
        } else {
            for ch_nr in 0..nr_of_channels {
                for seg_nr in 0..s.nr_of_segments[ch_nr] as usize {
                    if !(ch_nr == 0 && seg_nr == 0) {
                        let nbits = log2_round_up(count_tables as u32);
                        let v = reader.read_uint(nbits)? as i32;
                        s.table4_segment[ch_nr][seg_nr] = v;
                        if v == count_tables {
                            count_tables += 1;
                        } else if v > count_tables {
                            bail!(DstError::InvalidTableNumber);
                        }
                    }
                }
            }
        }
        if count_tables > max_nr_of_tables {
            bail!(DstError::TooManyTables);
        }
        *nr_of_tables = count_tables;
        Ok(())
    }

    pub(super) fn copy_mapping_data(&mut self) -> Result<()> {
        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        self.frame_hdr.p_same_map_all_ch = 1;
        for ch in 0..nr_of_channels {
            if self.frame_hdr.p_seg.nr_of_segments[ch] != self.frame_hdr.f_seg.nr_of_segments[ch] {
                bail!(DstError::SegmentNumberMismatch);
            }
            for seg in 0..self.frame_hdr.f_seg.nr_of_segments[ch] as usize {
                let v = self.frame_hdr.f_seg.table4_segment[ch][seg];
                self.frame_hdr.p_seg.table4_segment[ch][seg] = v;
                if v != self.frame_hdr.p_seg.table4_segment[0][seg] {
                    self.frame_hdr.p_same_map_all_ch = 0;
                }
            }
        }
        self.frame_hdr.nr_of_ptables = self.frame_hdr.nr_of_filters;
        if self.frame_hdr.nr_of_ptables > self.frame_hdr.max_nr_of_ptables {
            bail!(DstError::TooManyTables);
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // Filter coefficient sets
    // ------------------------------------------------------------
    pub(super) fn read_filter_coef_sets(&mut self, reader: &mut BitReader) -> Result<()> {
        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        let nr_of_filters = self.frame_hdr.nr_of_filters as usize;
        let coef_max = 1 << consts::SIZE_CODEDPREDORDER;

        for filter_nr in 0..nr_of_filters {
            let pred_order = reader.read_uint(consts::SIZE_CODEDPREDORDER)? as i32 + 1;
            self.frame_hdr.pred_order[filter_nr] = pred_order;
            let coded = reader.read_uint(1)? as i32;
            self.str_filter.coded[filter_nr] = coded;

            let coefs = &mut self.frame_hdr.i_coef_a[filter_nr];
            // Zero out tail (for SSE2 path safety).
            for c in coefs.iter_mut() {
                *c = 0;
            }

            if coded == 0 {
                self.str_filter.best_method[filter_nr] = -1;
                for c in coefs.iter_mut().take(pred_order as usize) {
                    *c = reader.read_short_signed(consts::SIZE_PREDCOEF)?;
                }
            } else {
                let best_method = reader.read_uint(consts::SIZE_RICEMETHOD)? as i32;
                if best_method as usize >= consts::NROFFRICEMETHODS {
                    bail!(DstError::InvalidCoefficientCoding);
                }
                self.str_filter.best_method[filter_nr] = best_method;
                let cpred_order = self.str_filter.c_pred_order[best_method as usize];
                if cpred_order >= pred_order {
                    bail!(DstError::InvalidCoefficientCoding);
                }
                for c in coefs.iter_mut().take(cpred_order as usize) {
                    *c = reader.read_short_signed(consts::SIZE_PREDCOEF)?;
                }
                let m = reader.read_uint(consts::SIZE_RICEM)? as i32;
                self.str_filter.m[filter_nr][best_method as usize] = m;
                for c in cpred_order as usize..pred_order as usize {
                    let mut x = 0i32;
                    for tap in 0..cpred_order as usize {
                        x += self.str_filter.c_pred_coef[best_method as usize][tap]
                            * coefs[c - tap - 1] as i32;
                    }
                    let r = rice_decode(reader, m)?;
                    let cv = if x >= 0 {
                        r - (x + 4) / 8
                    } else {
                        r + (-x + 3) / 8
                    };
                    if !(-(1 << (consts::SIZE_PREDCOEF - 1))..(1 << (consts::SIZE_PREDCOEF - 1)))
                        .contains(&cv)
                    {
                        bail!(DstError::InvalidCoefficientRange);
                    }
                    coefs[c] = cv as i16;
                }
            }
            // Coefs after pred_order remain zero (already cleared).
            let _ = coef_max;
        }

        // Set NrOfHalfBits[ChNr] = PredOrder[FSeg.Table4Segment[ChNr][0]].
        for ch in 0..nr_of_channels {
            let filter_idx = self.frame_hdr.f_seg.table4_segment[ch][0] as usize;
            self.frame_hdr.nr_of_half_bits[ch] = self.frame_hdr.pred_order[filter_idx];
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // Probability tables
    // ------------------------------------------------------------
    pub(super) fn read_probability_tables(&mut self, reader: &mut BitReader) -> Result<()> {
        let nr_of_ptables = self.frame_hdr.nr_of_ptables as usize;

        for ptable_nr in 0..nr_of_ptables {
            let len = reader.read_uint(consts::AC_HISBITS)? as i32 + 1;
            self.frame_hdr.ptable_len[ptable_nr] = len;
            if len > 1 {
                let coded = reader.read_uint(1)? as i32;
                self.str_ptable.coded[ptable_nr] = coded;
                if coded == 0 {
                    self.str_ptable.best_method[ptable_nr] = -1;
                    for entry in 0..len as usize {
                        let v = reader.read_uint(consts::AC_BITS - 1)? as i32 + 1;
                        self.p_one[ptable_nr][entry] = v;
                    }
                } else {
                    let best_method = reader.read_uint(consts::SIZE_RICEMETHOD)? as i32;
                    if best_method as usize >= consts::NROFPRICEMETHODS {
                        bail!(DstError::InvalidPtableCoding);
                    }
                    self.str_ptable.best_method[ptable_nr] = best_method;
                    let cpred_order = self.str_ptable.c_pred_order[best_method as usize];
                    if cpred_order >= len {
                        bail!(DstError::InvalidPtableCoding);
                    }
                    for entry in 0..cpred_order as usize {
                        let v = reader.read_uint(consts::AC_BITS - 1)? as i32 + 1;
                        self.p_one[ptable_nr][entry] = v;
                    }
                    let m = reader.read_uint(consts::SIZE_RICEM)? as i32;
                    self.str_ptable.m[ptable_nr][best_method as usize] = m;
                    for entry in cpred_order as usize..len as usize {
                        // entry < 0 || entry > AC_HISMAX check is structurally impossible here;
                        // but the C code performs it inside the loop. We mirror its semantics:
                        // entry is non-negative and bounded by len <= AC_HISMAX, so always pass.
                        let mut x = 0i32;
                        for tap in 0..cpred_order as usize {
                            x += self.str_ptable.c_pred_coef[best_method as usize][tap]
                                * self.p_one[ptable_nr][entry - tap - 1];
                        }
                        let r = rice_decode(reader, m)?;
                        let cv = if x >= 0 {
                            r - (x + 4) / 8
                        } else {
                            r + (-x + 3) / 8
                        };
                        if !(1..=(1 << (consts::AC_BITS - 1))).contains(&cv) {
                            bail!(DstError::InvalidPtableRange);
                        }
                        self.p_one[ptable_nr][entry] = cv;
                    }
                }
            } else {
                self.p_one[ptable_nr][0] = 128;
                self.str_ptable.best_method[ptable_nr] = -1;
            }
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // Arithmetic-coded data: read bit-by-bit into a_data[].
    // ------------------------------------------------------------
    pub(super) fn read_arithmetic_coded_data(&mut self, reader: &mut BitReader) -> Result<()> {
        let n = self.a_data_len.max(0) as usize;
        self.a_data.clear();
        // Reserve room for the AC bits + a small zero-padded tail so
        // `decode_bit` can read past the end without a bounds check. The
        // renormalise loop reads at most ABITS bits beyond cbptr, plus the
        // flush walk; 64 zero bytes are plenty.
        self.a_data.resize(n + 64, 0);
        // Fast path: pull 8 bits at a time and expand them MSB-first to
        // a-data bytes. `read_byte` (= `read_uint(8)`) handles arbitrary
        // bit alignment — it spans byte boundaries when needed — so this
        // produces the exact same per-bit sequence as the slow path. The
        // trailing `while i < n` covers when `a_data_len` is not a
        // multiple of 8.
        let mut i = 0;
        while i + 8 <= n {
            let byte = reader.read_byte()? as u32;
            self.a_data[i] = ((byte >> 7) & 1) as u8;
            self.a_data[i + 1] = ((byte >> 6) & 1) as u8;
            self.a_data[i + 2] = ((byte >> 5) & 1) as u8;
            self.a_data[i + 3] = ((byte >> 4) & 1) as u8;
            self.a_data[i + 4] = ((byte >> 3) & 1) as u8;
            self.a_data[i + 5] = ((byte >> 2) & 1) as u8;
            self.a_data[i + 6] = ((byte >> 1) & 1) as u8;
            self.a_data[i + 7] = (byte & 1) as u8;
            i += 8;
        }
        while i < n {
            self.a_data[i] = reader.read_bit()?;
            i += 1;
        }
        Ok(())
    }

    // ------------------------------------------------------------
    // FillTable4Bit
    // ------------------------------------------------------------
    pub(super) fn fill_table_4bit(
        nr_of_channels: usize,
        nr_of_bits_per_ch: usize,
        s: &Segment,
        table_4bit: &mut [u8],
    ) {
        for ch in 0..nr_of_channels {
            let row_start = ch * nr_of_bits_per_ch;
            let row = &mut table_4bit[row_start..row_start + nr_of_bits_per_ch];
            let mut start = 0usize;
            let mut last_seg = 0usize;
            let n = s.nr_of_segments[ch] as usize;
            for seg in 0..n.saturating_sub(1) {
                let val = s.table4_segment[ch][seg] as u8;
                let end = start + (s.resolution as usize) * 8 * (s.segment_len[ch][seg] as usize);
                row[start..end].fill(val);
                start = end;
                last_seg = seg + 1;
            }
            // Final segment fills the rest.
            let val = s.table4_segment[ch][last_seg] as u8;
            row[start..].fill(val);
        }
    }

    pub(super) fn build_filter_tables(&mut self) -> usize {
        let nr_of_filters = self.frame_hdr.nr_of_filters as usize;
        for (filter_nr, filter_tables) in self
            .filter_tables
            .iter_mut()
            .take(nr_of_filters)
            .enumerate()
        {
            let filter_length = self.frame_hdr.pred_order[filter_nr];
            let coefs = &self.frame_hdr.i_coef_a[filter_nr];
            for (table_nr, table) in filter_tables.iter_mut().enumerate() {
                let k = (filter_length - (table_nr as i32) * 8).clamp(0, 8) as usize;
                for (i, slot) in table.iter_mut().enumerate() {
                    let mut cvalue: i32 = 0;
                    for j in 0..k {
                        let bit_val = (((i >> j) & 1) as i32) * 2 - 1;
                        cvalue += bit_val * coefs[table_nr * 8 + j] as i32;
                    }
                    *slot = cvalue as i16;
                }
            }
        }
        nr_of_filters
    }

    // ------------------------------------------------------------
    // DST_FramDSTDecode main loop
    // ------------------------------------------------------------
    pub(super) fn decode_dsd_samples(&mut self, dsd_data: &mut [u8]) -> Result<usize> {
        let nr_of_channels = self.frame_hdr.nr_of_channels as usize;
        let nr_of_bits_per_ch = self.frame_hdr.nr_of_bits_per_ch as usize;

        // FillTable4Bit for filters and ptables.
        Self::fill_table_4bit(
            nr_of_channels,
            nr_of_bits_per_ch,
            &self.frame_hdr.f_seg,
            &mut self.filter4_bit,
        );
        Self::fill_table_4bit(
            nr_of_channels,
            nr_of_bits_per_ch,
            &self.frame_hdr.p_seg,
            &mut self.ptable4_bit,
        );

        let nr_of_filters = self.build_filter_tables();

        // Status as 4 u32 words per channel (matches the C macro that shifts
        // 32-bit words). Initial value: all bytes 0xAA -> each word = 0xAAAAAAAA.
        let mut status = [[0xAAAA_AAAAu32; 4]; consts::MAX_CHANNELS];

        // Init AC and decode the first dummy bit using Reverse7LSBs(ICoefA[0][0]).
        let mut ac = AcData::default();
        ac.init(&self.a_data, self.a_data_len);
        let dummy_prob = reverse7_lsbs(self.frame_hdr.i_coef_a[0][0]);
        let _dummy = ac.decode_bit(dummy_prob, &self.a_data, self.a_data_len);

        let total_bytes = (nr_of_bits_per_ch * nr_of_channels) / 8;
        for b in &mut dsd_data[..total_bytes] {
            *b = 0;
        }

        // Hoist field accesses out of the inner loop so the borrow checker
        // and codegen don't have to chase `self.frame_hdr.*` on every bit.
        let half_prob = self.frame_hdr.half_prob;
        let nr_of_half_bits = self.frame_hdr.nr_of_half_bits;
        let ptable_len = &self.frame_hdr.ptable_len[..];
        let p_one = &self.p_one[..];
        let a_data: &[u8] = &self.a_data;
        let a_data_len: i32 = self.a_data_len;
        let i_coef_i = &self.filter_tables[..nr_of_filters];
        let filter4_bit = &self.filter4_bit[..];
        let ptable4_bit = &self.ptable4_bit[..];
        let stride = self.bits_per_ch_stride;
        let has_avx2 = self.has_avx2;

        for bit_nr in 0..nr_of_bits_per_ch {
            let byte_nr = bit_nr / 8;
            let bit_shift = 7 - (bit_nr % 8);
            for ch_nr in 0..nr_of_channels {
                let row_off = ch_nr * stride + bit_nr;
                let filter_idx = filter4_bit[row_off] as usize;
                let ftable = &i_coef_i[filter_idx];
                let st = &mut status[ch_nr];

                // FIR filter (LT_RUN_FILTER_I). Each `st[i]` u32 packs four
                // status bytes (little-endian: byte j lives at
                // `(j & 3) * 8`). SIMD paths use wrapping i16 lane adds,
                // matching the scalar chained `wrapping_add` exactly.
                let predict = fir_predict(ftable, st, has_avx2);

                // Decode residual.
                let residual = if half_prob[ch_nr] != 0 && (bit_nr as i32) < nr_of_half_bits[ch_nr]
                {
                    ac.decode_bit(consts::AC_PROBS / 2, a_data, a_data_len)
                } else {
                    let ptable_idx = ptable4_bit[row_off] as usize;
                    let plen = ptable_len[ptable_idx];
                    let entry = ac_get_ptable_index(predict, plen) as usize;
                    let prob = p_one[ptable_idx][entry];
                    ac.decode_bit(prob, a_data, a_data_len)
                };

                let bit_val = (((predict as u16) >> 15) ^ residual as u16) & 1;
                dsd_data[byte_nr * nr_of_channels + ch_nr] |= (bit_val as u8) << bit_shift;

                // Filter status update — 32-bit shift-with-carry, four words.
                let w0 = st[0];
                let w1 = st[1];
                let w2 = st[2];
                st[3] = (st[3] << 1) | (w2 >> 31);
                st[2] = (w2 << 1) | (w1 >> 31);
                st[1] = (w1 << 1) | (w0 >> 31);
                st[0] = (w0 << 1) | bit_val as u32;
            }
        }

        let ac_status = ac.flush(a_data, a_data_len);
        if ac_status != 1 {
            bail!(DstError::ArithmeticDecoder);
        }
        Ok(total_bytes)
    }
}
