// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Errors that can be raised while parsing or decoding a DST frame.
///
/// Each variant maps to a specific malformed-bitstream condition checked
/// by the spec; the [`Display`](std::fmt::Display) impl yields a human-
/// readable message. These are wrapped by [`anyhow::Error`] in the public
/// API (see [`DstDecoder::decode_frame`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DstError {
    /// The bit reader was advanced past the end of the input frame.
    NegativeBitAllocation,
    /// A channel declared more segments than the spec maximum.
    TooManySegments,
    /// Segment resolution field is zero or exceeds the frame length.
    InvalidSegmentResolution,
    /// Segment length is below the minimum or overflows the frame.
    InvalidSegmentLength,
    /// Number of distinct filter or probability tables exceeds the spec maximum.
    TooManyTables,
    /// Segment references a table index that hasn't been allocated yet.
    InvalidTableNumber,
    /// Per-channel mapping flagged as varying but is identical across all channels.
    InvalidChannelMapping,
    /// Filter and probability segment counts disagree when reuse was signalled.
    SegmentNumberMismatch,
    /// Filter coefficient coding method is out of range or has invalid predictor order.
    InvalidCoefficientCoding,
    /// Decoded filter coefficient falls outside the legal signed range.
    InvalidCoefficientRange,
    /// Probability table coding method is out of range or has invalid predictor order.
    InvalidPtableCoding,
    /// Decoded probability entry falls outside the legal range `[1, 128]`.
    InvalidPtableRange,
    /// The trailing stuffing bits in an uncompressed-DSD frame were not all zero.
    InvalidStuffingPattern,
    /// The first byte of the arithmetic-coded payload was non-zero.
    InvalidArithmeticCode,
    /// End-of-frame trailing-bit check in the arithmetic decoder failed.
    ArithmeticDecoder,
}

impl DstError {
    pub(super) fn message(self) -> &'static str {
        match self {
            DstError::NegativeBitAllocation => "A negative number of bits allocated",
            DstError::TooManySegments => "Too many segments for this channel",
            DstError::InvalidSegmentResolution => "Invalid segment resolution",
            DstError::InvalidSegmentLength => "Invalid segment length",
            DstError::TooManyTables => "Too many tables for this frame",
            DstError::InvalidTableNumber => "Invalid table number for segment",
            DstError::InvalidChannelMapping => "Mapping can't be the same for all channels",
            DstError::SegmentNumberMismatch => {
                "Not same number of segments for filters and Ptables"
            }
            DstError::InvalidCoefficientCoding => "Invalid coefficient coding method",
            DstError::InvalidCoefficientRange => "Filter coefficient out of range",
            DstError::InvalidPtableCoding => "Invalid Ptable coding method",
            DstError::InvalidPtableRange => "Ptable entry out of range",
            DstError::InvalidStuffingPattern => "Illegal stuffing pattern",
            DstError::InvalidArithmeticCode => "Illegal arithmetic code",
            DstError::ArithmeticDecoder => "Arithmetic decoding error",
        }
    }
}

impl std::fmt::Display for DstError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.message())
    }
}

impl std::error::Error for DstError {}
