// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[inline(always)]
pub(super) fn fir_predict(ftable: &[[i16; 256]; 16], st: &[u32; 4], has_avx2: bool) -> i16 {
    #[cfg(target_arch = "x86_64")]
    {
        if has_avx2 {
            // SAFETY: `has_avx2` was set from `is_x86_feature_detected!("avx2")`
            // at decoder construction, so AVX2 instructions are available.
            unsafe { fir_predict_avx2(ftable, st) }
        } else {
            // SSE2 is baseline on every x86_64 target.
            fir_predict_sse2(ftable, st)
        }
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        let _ = has_avx2;
        fir_predict_scalar(ftable, st)
    }
}

#[cfg(any(test, not(target_arch = "x86_64")))]
#[inline]
pub(super) fn fir_predict_scalar(ftable: &[[i16; 256]; 16], st: &[u32; 4]) -> i16 {
    let w0 = st[0];
    let w1 = st[1];
    let w2 = st[2];
    let w3 = st[3];
    let sum = ftable[0][(w0 & 0xff) as usize] as i32
        + ftable[1][((w0 >> 8) & 0xff) as usize] as i32
        + ftable[2][((w0 >> 16) & 0xff) as usize] as i32
        + ftable[3][((w0 >> 24) & 0xff) as usize] as i32
        + ftable[4][(w1 & 0xff) as usize] as i32
        + ftable[5][((w1 >> 8) & 0xff) as usize] as i32
        + ftable[6][((w1 >> 16) & 0xff) as usize] as i32
        + ftable[7][((w1 >> 24) & 0xff) as usize] as i32
        + ftable[8][(w2 & 0xff) as usize] as i32
        + ftable[9][((w2 >> 8) & 0xff) as usize] as i32
        + ftable[10][((w2 >> 16) & 0xff) as usize] as i32
        + ftable[11][((w2 >> 24) & 0xff) as usize] as i32
        + ftable[12][(w3 & 0xff) as usize] as i32
        + ftable[13][((w3 >> 8) & 0xff) as usize] as i32
        + ftable[14][((w3 >> 16) & 0xff) as usize] as i32
        + ftable[15][((w3 >> 24) & 0xff) as usize] as i32;
    sum as i16
}

#[cfg(target_arch = "x86_64")]
#[inline]
pub(super) fn fir_predict_sse2(ftable: &[[i16; 256]; 16], st: &[u32; 4]) -> i16 {
    use std::arch::x86_64::*;

    // SAFETY: every x86_64 baseline target has SSE2. The table lookups are
    // ordinary safe indexing into fixed 256-entry tables using masked bytes.
    unsafe {
        let w0 = st[0];
        let w1 = st[1];
        let w2 = st[2];
        let w3 = st[3];

        let v0 = _mm_set_epi16(
            ftable[7][((w1 >> 24) & 0xff) as usize],
            ftable[6][((w1 >> 16) & 0xff) as usize],
            ftable[5][((w1 >> 8) & 0xff) as usize],
            ftable[4][(w1 & 0xff) as usize],
            ftable[3][((w0 >> 24) & 0xff) as usize],
            ftable[2][((w0 >> 16) & 0xff) as usize],
            ftable[1][((w0 >> 8) & 0xff) as usize],
            ftable[0][(w0 & 0xff) as usize],
        );
        let v1 = _mm_set_epi16(
            ftable[15][((w3 >> 24) & 0xff) as usize],
            ftable[14][((w3 >> 16) & 0xff) as usize],
            ftable[13][((w3 >> 8) & 0xff) as usize],
            ftable[12][(w3 & 0xff) as usize],
            ftable[11][((w2 >> 24) & 0xff) as usize],
            ftable[10][((w2 >> 16) & 0xff) as usize],
            ftable[9][((w2 >> 8) & 0xff) as usize],
            ftable[8][(w2 & 0xff) as usize],
        );

        let s = _mm_add_epi16(v0, v1);
        let s = _mm_add_epi16(s, _mm_srli_si128(s, 8));
        let s = _mm_add_epi16(s, _mm_srli_si128(s, 4));
        let s = _mm_add_epi16(s, _mm_srli_si128(s, 2));
        _mm_extract_epi16::<0>(s) as i16
    }
}

#[cfg(target_arch = "x86_64")]
#[target_feature(enable = "avx2")]
#[inline]
pub(super) unsafe fn fir_predict_avx2(ftable: &[[i16; 256]; 16], st: &[u32; 4]) -> i16 {
    use std::arch::x86_64::*;

    let w0 = st[0];
    let w1 = st[1];
    let w2 = st[2];
    let w3 = st[3];
    let v = _mm256_set_epi16(
        ftable[15][((w3 >> 24) & 0xff) as usize],
        ftable[14][((w3 >> 16) & 0xff) as usize],
        ftable[13][((w3 >> 8) & 0xff) as usize],
        ftable[12][(w3 & 0xff) as usize],
        ftable[11][((w2 >> 24) & 0xff) as usize],
        ftable[10][((w2 >> 16) & 0xff) as usize],
        ftable[9][((w2 >> 8) & 0xff) as usize],
        ftable[8][(w2 & 0xff) as usize],
        ftable[7][((w1 >> 24) & 0xff) as usize],
        ftable[6][((w1 >> 16) & 0xff) as usize],
        ftable[5][((w1 >> 8) & 0xff) as usize],
        ftable[4][(w1 & 0xff) as usize],
        ftable[3][((w0 >> 24) & 0xff) as usize],
        ftable[2][((w0 >> 16) & 0xff) as usize],
        ftable[1][((w0 >> 8) & 0xff) as usize],
        ftable[0][(w0 & 0xff) as usize],
    );

    let lo = _mm256_castsi256_si128(v);
    let hi = _mm256_extracti128_si256::<1>(v);
    let s = _mm_add_epi16(lo, hi);
    let s = _mm_add_epi16(s, _mm_srli_si128(s, 8));
    let s = _mm_add_epi16(s, _mm_srli_si128(s, 4));
    let s = _mm_add_epi16(s, _mm_srli_si128(s, 2));
    _mm_extract_epi16::<0>(s) as i16
}
