// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub(super) fn max_nr_of_filters(nr_channels: usize) -> usize {
    2 * nr_channels
}

pub(super) fn max_nr_of_ptables(nr_channels: usize) -> usize {
    2 * nr_channels
}
