// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::consts;

#[derive(Clone)]
pub(super) struct Segment {
    pub(super) resolution: i32,
    pub(super) segment_len: [[i32; consts::MAXNROF_SEGS]; consts::MAX_CHANNELS],
    pub(super) nr_of_segments: [i32; consts::MAX_CHANNELS],
    pub(super) table4_segment: [[i32; consts::MAXNROF_SEGS]; consts::MAX_CHANNELS],
}

impl Default for Segment {
    fn default() -> Self {
        Self {
            resolution: 0,
            segment_len: [[0; consts::MAXNROF_SEGS]; consts::MAX_CHANNELS],
            nr_of_segments: [0; consts::MAX_CHANNELS],
            table4_segment: [[0; consts::MAXNROF_SEGS]; consts::MAX_CHANNELS],
        }
    }
}
