// Auto-generated by r2factor. Manual edits will be overwritten on next split.
use super::ac_data::AcData;
use super::bit_reader::BitReader;
use super::dst_decoder::DstDecoder;
use super::fir::fir_predict;
#[cfg(target_arch = "x86_64")]
use super::fir::fir_predict_avx2;
#[cfg(any(test, not(target_arch = "x86_64")))]
use super::fir::fir_predict_scalar;
use super::misc::ac_get_ptable_index;
use super::misc::log2_round_up;
use super::misc::reverse7_lsbs;
use crate::consts::{
    DSD64_SAMPLE_RATE, DSD128_SAMPLE_RATE, DSD256_SAMPLE_RATE, HALF, MAX_CHANNELS,
};

#[test]
fn test_decoder_creation() {
    let d = DstDecoder::new(2, 2_822_400).unwrap();
    assert_eq!(d.channel_count, 2);
    assert_eq!(d.frame_hdr.max_frame_len, 4704);
}

#[test]
fn test_invalid_args() {
    assert!(DstDecoder::new(0, 2_822_400).is_err());
    assert!(DstDecoder::new(MAX_CHANNELS + 1, 2_822_400).is_err());
    assert!(DstDecoder::new(2, 48000).is_err());
}

#[test]
fn test_log2_round_up() {
    // Matches C: smallest y with x < 2^y, but counted as `while x >= 1<<y`.
    assert_eq!(log2_round_up(0), 0);
    assert_eq!(log2_round_up(1), 1);
    assert_eq!(log2_round_up(2), 2);
    assert_eq!(log2_round_up(3), 2);
    assert_eq!(log2_round_up(4), 3);
    assert_eq!(log2_round_up(7), 3);
    assert_eq!(log2_round_up(8), 4);
}

#[test]
fn test_ac_get_ptable_index() {
    assert_eq!(ac_get_ptable_index(0, 10), 0);
    assert_eq!(ac_get_ptable_index(8, 10), 1);
    assert_eq!(ac_get_ptable_index(-8, 10), 1);
    assert_eq!(ac_get_ptable_index(1000, 5), 4); // clamped
}

#[test]
fn test_reverse7_lsbs() {
    assert_eq!(reverse7_lsbs(0), 1);
}

#[test]
fn test_bit_reader_basic() {
    let data = [0b1010_0110u8, 0b1111_0000];
    let mut r = BitReader::new(&data);
    assert_eq!(r.read_uint(1).unwrap(), 1);
    assert_eq!(r.read_uint(1).unwrap(), 0);
    assert_eq!(r.read_uint(2).unwrap(), 0b10);
    assert_eq!(r.read_uint(4).unwrap(), 0b0110);
    assert_eq!(r.read_uint(4).unwrap(), 0b1111);
    assert_eq!(r.read_uint(4).unwrap(), 0);
    assert!(r.read_uint(1).is_err());
}

#[test]
fn test_bit_reader_signed() {
    // 9 bits of 0b1_1110_0101 = 485 unsigned = -27 signed
    let data = [0b1111_0010u8, 0b1000_0000];
    let mut r = BitReader::new(&data);
    assert_eq!(r.read_int(9).unwrap(), -27);
}

// BEGIN public-API tests
//
// These tests exercise every public surface of the dst_decoder module
// with both synthetic inputs (config edges) and real DST frames snipped
// from a SACD ISO. The fixture files under `test_fixtures/` are
// committed binary blobs; their reference DSD outputs were verified
// against the C `sacd-ripper` decoder via byte-for-byte file comparison
// before being baked in.

#[cfg(feature = "fixture-tests")]
macro_rules! stereo_fixture {
    ($n:literal) => {
        (
            include_bytes!(concat!("test_fixtures/stereo/frame_", $n, ".dst")) as &[u8],
            include_bytes!(concat!("test_fixtures/stereo/frame_", $n, ".dsd")) as &[u8],
        )
    };
}
#[cfg(feature = "fixture-tests")]
macro_rules! mch_fixture {
    ($n:literal) => {
        (
            include_bytes!(concat!("test_fixtures/mch/frame_", $n, ".dst")) as &[u8],
            include_bytes!(concat!("test_fixtures/mch/frame_", $n, ".dsd")) as &[u8],
        )
    };
}

#[test]
fn new_accepts_all_supported_sample_rates() {
    for &rate in &[DSD64_SAMPLE_RATE, DSD128_SAMPLE_RATE, DSD256_SAMPLE_RATE] {
        DstDecoder::new(2, rate as usize)
            .unwrap_or_else(|e| panic!("DSD@{} should be accepted: {}", rate, e));
    }
}

#[test]
fn new_rejects_zero_and_too_many_channels() {
    assert!(DstDecoder::new(0, DSD64_SAMPLE_RATE as usize).is_err());
    assert!(DstDecoder::new(MAX_CHANNELS + 1, DSD64_SAMPLE_RATE as usize).is_err());
}

#[test]
fn new_rejects_unsupported_sample_rate() {
    assert!(DstDecoder::new(2, 48_000).is_err());
    assert!(DstDecoder::new(2, 44_100).is_err());
    assert!(DstDecoder::new(2, 0).is_err());
}

#[test]
fn dsd_frame_bytes_matches_588_times_fs_over_8_times_channels() {
    // Spec: max_frame_len = 588 * Fs44 / 8 bytes per channel; total
    // frame bytes = max_frame_len * nr_of_channels.
    let cases = [
        (2, DSD64_SAMPLE_RATE as usize, 588 * 64 / 8 * 2),
        (5, DSD64_SAMPLE_RATE as usize, 588 * 64 / 8 * 5),
        (6, DSD64_SAMPLE_RATE as usize, 588 * 64 / 8 * 6),
        (2, DSD128_SAMPLE_RATE as usize, 588 * 128 / 8 * 2),
        (2, DSD256_SAMPLE_RATE as usize, 588 * 256 / 8 * 2),
    ];
    for (ch, rate, expected) in cases {
        let d = DstDecoder::new(ch, rate).unwrap();
        assert_eq!(
            d.dsd_frame_bytes(),
            expected,
            "channels={} rate={}",
            ch,
            rate
        );
    }
}

#[test]
fn arithmetic_decoder_reads_zero_past_padding() {
    let mut ac = AcData {
        a: HALF - 1,
        c: 0,
        cbptr: 1,
    };

    let _ = ac.decode_bit(1, &[0], 1);
}

#[test]
fn fir_predict_simd_matches_scalar() {
    let mut ftable = [[0i16; 256]; 16];
    for (table_idx, table) in ftable.iter_mut().enumerate() {
        for (slot_idx, slot) in table.iter_mut().enumerate() {
            let seed = (table_idx as i32 * 257) ^ (slot_idx as i32 * 31);
            *slot = (seed.wrapping_mul(17).wrapping_sub(12_345)) as i16;
        }
    }

    let cases = [
        [0x0000_0000, 0x1111_1111, 0x2222_2222, 0x3333_3333],
        [0xffff_ffff, 0xeeee_eeee, 0xdddd_dddd, 0xcccc_cccc],
        [0x0123_4567, 0x89ab_cdef, 0xfedc_ba98, 0x7654_3210],
        [0xaa55_aa55, 0x55aa_55aa, 0x0f0f_f0f0, 0xf0f0_0f0f],
    ];

    for st in cases {
        let expected = fir_predict_scalar(&ftable, &st);
        assert_eq!(fir_predict(&ftable, &st, false), expected);

        #[cfg(target_arch = "x86_64")]
        if std::is_x86_feature_detected!("avx2") {
            // SAFETY: guarded by the runtime AVX2 feature check above.
            assert_eq!(unsafe { fir_predict_avx2(&ftable, &st) }, expected);
        }
    }
}

#[cfg(feature = "fixture-tests")]
#[test]
fn decode_frame_stereo_first_frame_bit_exact() {
    let (dst, dsd_ref) = stereo_fixture!("001");
    let mut decoder = DstDecoder::new(2, DSD64_SAMPLE_RATE as usize).unwrap();
    let mut out = vec![0u8; decoder.dsd_frame_bytes()];
    let n = decoder.decode_frame(dst, &mut out).unwrap();
    assert_eq!(n, decoder.dsd_frame_bytes());
    assert_eq!(out, dsd_ref);
}

#[cfg(feature = "fixture-tests")]
#[test]
fn decode_frame_stereo_sequence_is_per_frame_stateless() {
    // A single decoder instance must produce identical output for each
    // fixture frame as a freshly-constructed decoder would; this is
    // the property that lets the production pipeline parallelise via
    // rayon thread-local decoders.
    let frames = [
        stereo_fixture!("001"),
        stereo_fixture!("002"),
        stereo_fixture!("003"),
    ];
    let mut shared = DstDecoder::new(2, DSD64_SAMPLE_RATE as usize).unwrap();
    let dsd_len = shared.dsd_frame_bytes();
    let mut out = vec![0u8; dsd_len];

    for (i, (dst, dsd_ref)) in frames.iter().enumerate() {
        out.fill(0);
        let n = shared.decode_frame(dst, &mut out).unwrap();
        assert_eq!(n, dsd_len, "frame {} returned wrong length", i + 1);
        assert_eq!(&out, dsd_ref, "shared decoder mismatch on frame {}", i + 1);

        let mut fresh = DstDecoder::new(2, DSD64_SAMPLE_RATE as usize).unwrap();
        let mut fresh_out = vec![0u8; dsd_len];
        fresh.decode_frame(dst, &mut fresh_out).unwrap();
        assert_eq!(
            &fresh_out,
            dsd_ref,
            "fresh decoder mismatch on frame {}",
            i + 1
        );
    }
}

#[cfg(feature = "fixture-tests")]
#[test]
fn decode_frame_mch_sequence_bit_exact() {
    let frames = [
        mch_fixture!("001"),
        mch_fixture!("002"),
        mch_fixture!("003"),
    ];
    let channels = 5;
    let mut decoder = DstDecoder::new(channels, DSD64_SAMPLE_RATE as usize).unwrap();
    let dsd_len = decoder.dsd_frame_bytes();
    let mut out = vec![0u8; dsd_len];

    for (i, (dst, dsd_ref)) in frames.iter().enumerate() {
        assert_eq!(dsd_ref.len(), dsd_len);
        out.fill(0);
        let n = decoder.decode_frame(dst, &mut out).unwrap();
        assert_eq!(n, dsd_len);
        assert_eq!(&out, dsd_ref, "mch frame {} mismatch", i + 1);
    }
}

#[test]
fn decode_frame_rejects_undersized_output_buffer() {
    let mut decoder = DstDecoder::new(2, DSD64_SAMPLE_RATE as usize).unwrap();
    let mut tiny = vec![0u8; decoder.dsd_frame_bytes() - 1];
    let err = decoder.decode_frame(&[], &mut tiny).unwrap_err();
    let msg = format!("{}", err);
    assert!(
        msg.contains("DSD output buffer too small"),
        "unexpected error: {}",
        msg
    );
}

#[cfg(feature = "fixture-tests")]
#[test]
fn decode_frame_accepts_oversized_output_buffer() {
    // A larger-than-needed output buffer is fine: decode_frame writes
    // exactly dsd_frame_bytes() and reports that count; the trailing
    // bytes are left untouched.
    let (dst, dsd_ref) = stereo_fixture!("001");
    let mut decoder = DstDecoder::new(2, DSD64_SAMPLE_RATE as usize).unwrap();
    let dsd_len = decoder.dsd_frame_bytes();
    let mut out = vec![0xAAu8; dsd_len + 64];
    let n = decoder.decode_frame(dst, &mut out).unwrap();
    assert_eq!(n, dsd_len);
    assert_eq!(&out[..dsd_len], dsd_ref);
    assert!(out[dsd_len..].iter().all(|&b| b == 0xAA));
}
// END public-API tests
