// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::segment::Segment;
use crate::consts;

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum TableType {
    Filter,
    Ptable,
}

#[derive(Default)]
pub(super) struct FrameHeader {
    pub(super) nr_of_channels: i32,
    pub(super) nr_of_filters: i32,
    pub(super) nr_of_ptables: i32,
    pub(super) pred_order: Vec<i32>, // [MaxNrOfFilters]
    pub(super) ptable_len: Vec<i32>, // [MaxNrOfPtables]
    /// ICoefA[FilterNr][CoefNr] padded to (1<<SIZE_CODEDPREDORDER) entries.
    pub(super) i_coef_a: Vec<Vec<i16>>,
    pub(super) dst_coded: i32,
    pub(super) calc_nr_of_bytes: i64,
    pub(super) calc_nr_of_bits: i64,
    pub(super) half_prob: [i32; consts::MAX_CHANNELS],
    pub(super) nr_of_half_bits: [i32; consts::MAX_CHANNELS],
    pub(super) f_seg: Segment,
    pub(super) p_seg: Segment,
    pub(super) p_same_seg_as_f: i32,
    pub(super) p_same_map_as_f: i32,
    pub(super) f_same_seg_all_ch: i32,
    pub(super) f_same_map_all_ch: i32,
    pub(super) p_same_seg_all_ch: i32,
    pub(super) p_same_map_all_ch: i32,
    pub(super) max_nr_of_filters: i32,
    pub(super) max_nr_of_ptables: i32,
    pub(super) max_frame_len: i64,
    pub(super) nr_of_bits_per_ch: i64,
}
