// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::get::get_stage1_chunk_params;
use super::round::round_down_to_multiple;
use super::round::round_up_to_multiple;
use dsd_reader::dsd_file::DSD_64_RATE;

#[inline]
pub(super) fn compute_stage1_chunk(
    total_groups: usize,
    m: usize,
    _l: u32,
) -> usize {
    let (mult, mut align, target) = get_stage1_chunk_params();
    // Default chunk: round TARGET≈128 up to multiple of M
    let mut chunk = if target > 0 {
        round_up_to_multiple(target, m)
    } else if mult > 0 {
        m.saturating_mul(mult)
    } else {
        round_up_to_multiple(128, m)
    };
    if chunk == 0 {
        chunk = m.max(1);
    }
    // Default ALIGN=M if unset
    if align == 0 {
        align = m.max(1);
    }
    if chunk > total_groups {
        chunk = total_groups;
    }
    // apply alignment by rounding down; keep within [min, total_groups]
    let min_allowed = align.min(total_groups).max(1);
    chunk = round_down_to_multiple(chunk, align)
        .max(min_allowed)
        .min(total_groups);
    chunk
}

pub fn compute_decim_and_upsample(
    in_rate: i32,
    out_rate: u32,
) -> (i32, u32) {
    // Determine decimation ratio (M)
    let decim_ratio: i32 = if out_rate == 96_000 && in_rate == 4 {
        // DSD256 -> 96k two-stage LM path: M=588 (×5 -> /21 -> /28)
        588
    } else if (out_rate == 96_000 && in_rate == 2)
        || (out_rate == 192_000 && in_rate == 4)
    {
        294
    } else if out_rate == 96_000
        || out_rate == 192_000
        || out_rate == 384_000
    {
        147
    } else {
        // Integer ratio attempt (fallback to 64)
        let base = DSD_64_RATE * (in_rate as u32);
        if out_rate > 0 && base % (out_rate as u32) == 0 {
            (base / (out_rate as u32)) as i32
        } else {
            64
        }
    };

    // Upsample (L) selection
    let upsample_ratio: u32 = if decim_ratio < 147 {
        1
    } else if out_rate == 384_000 {
        // Specialized two-phase L choices for 384k: DSD64->L20, DSD128->L10, DSD256->L5
        if in_rate == 1 {
            20
        } else if in_rate == 2 {
            10
        } else if in_rate == 4 {
            5
        } else {
            5
        }
    } else if out_rate == 192_000 {
        // 192k: DSD64->L10, DSD128->L5, DSD256->L5 (reuses L5 path)
        if in_rate == 1 {
            10
        } else if in_rate == 2 {
            5
        } else if in_rate == 4 {
            5
        } else {
            5
        }
    } else if out_rate == 96_000 {
        5
    } else {
        5
    };
    (decim_ratio, upsample_ratio)
}
