// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::Stage1LutKey;
use super::types::Stage1LutTable;
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

pub(super) static STAGE1_LUT_CACHE: OnceLock<
    Mutex<HashMap<Stage1LutKey, Arc<Stage1LutTable>>>,
> = OnceLock::new();

pub(super) static ST1_DIAG_ONCE: OnceLock<()> = OnceLock::new();

pub(super) static ST1_MULT: OnceLock<usize> = OnceLock::new();

pub(super) static ST1_ALIGN: OnceLock<usize> = OnceLock::new();

pub(super) static ST1_TARGET: OnceLock<usize> = OnceLock::new();
