// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Lightweight decimator structure direct symmetric convolution only
#[derive(Debug)]
pub(super) struct DecimFIRSym {
    pub(super) full: Vec<f64>, // full symmetric taps
    pub(super) len: usize,
    pub(super) half: usize,
    pub(super) has_center: bool,
    pub(super) center: usize, // (len-1)/2, used for initial output schedule
    pub(super) decim: usize,  // decimation factor D
    pub(super) ring: Vec<f64>,
    pub(super) mask: usize,
    pub(super) w: usize,          // next write index
    pub(super) count: usize,      // total samples seen
    pub(super) next_out_t: usize, // next t index at which an output is due
}

impl DecimFIRSym {
    pub(super) fn new_from_half(right_half: &[f64], decim: usize) -> Self {
        // Reconstruct full taps (mirror right_half)
        let mut full: Vec<f64> =
            right_half.iter().rev().cloned().collect();
        full.extend_from_slice(right_half);
        let len = full.len();
        let center = (len - 1) / 2;
        let has_center = len % 2 == 1;
        let half = if has_center { (len - 1) / 2 } else { len / 2 };
        // Ring capacity: next power of two >= len + decim (margin)
        let cap = (len + decim).next_power_of_two();
        return Self {
            full,
            len,
            half,
            has_center,
            center,
            decim,
            ring: vec![0.0; cap],
            mask: cap - 1,
            w: 0,
            count: 0,
            next_out_t: center,
        };
    }

    /// Block processing: feed a slice of inputs and write produced outputs into `out`.
    /// Returns number of output samples written.
    #[inline(always)]
    pub(super) fn process_block(
        &mut self,
        input: &[f64],
        out: &mut [f64],
    ) -> usize {
        let mut produced = 0usize;
        for &x in input {
            // Write newest sample
            self.ring[self.w] = x;
            self.w = (self.w + 1) & self.mask;
            let t = self.count;
            self.count += 1;

            // Produce only when we've reached the next scheduled output time
            if t != self.next_out_t {
                continue;
            }
            // Advance next output time for future samples
            self.next_out_t = self.next_out_t.saturating_add(self.decim);

            let acc = self.convolve_direct();
            if produced < out.len() {
                out[produced] = acc;
                produced += 1;
            }
        }
        produced
    }

    /// Direct full-rate symmetric FIR convolution
    /// Evaluates y[t] = sum_{k=0..len-1} h[k] * x[t - k] when push() determines an output is due.
    #[inline(always)]
    pub(super) fn convolve_direct(&self) -> f64 {
        let cap = self.ring.len();
        let newest = (self.w + cap - 1) & self.mask; // index of x[t]
        let mut total = 0.0;

        // Pairwise sum using symmetry: for k in 0..half-1
        // y += h[k] * (x[t-k] + x[t-(len-1-k)])
        let len = self.len;
        let half = self.half;
        let has_center = self.has_center;
        let center = self.center;

        // Indices for front (newest side) and back (oldest side)
        let mut idx_front = newest; // x[t - 0]
        let mut idx_back = (newest + cap - (len - 1)) & self.mask; // x[t - (len-1)]

        let mut k = 0usize;
        while k < half {
            let c = self.full[k];
            let xf = self.ring[idx_front];
            let xb = self.ring[idx_back];
            total += c * (xf + xb);
            // advance indices
            idx_front = (idx_front + cap - 1) & self.mask; // older by 1
            idx_back = (idx_back + 1) & self.mask; // newer by 1
            k += 1;
        }

        // Center tap (odd length)
        if has_center {
            let ic = (newest + cap - center) & self.mask;
            total += self.full[center] * self.ring[ic];
        }
        total
    }
}
