// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::env;

#[inline]
pub(super) fn env_usize(name: &str, default: usize) -> usize {
    env::var(name)
        .ok()
        .and_then(|v| v.parse::<usize>().ok())
        .unwrap_or(default)
}

#[inline]
pub(super) fn env_present(name: &str) -> bool {
    env::var_os(name).is_some()
}

#[inline]
pub(super) fn any_env_present(names: &[&str]) -> bool {
    names.iter().any(|n| env_present(n))
}
