// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::ST1_ALIGN;
use super::consts::ST1_MULT;
use super::consts::ST1_TARGET;
use super::consts::STAGE1_LUT_CACHE;
use super::env_mod::env_usize;
use super::misc::build_stage1_lut_from_right_half;
use super::misc::hash_f64_slice_fnv1a;
use super::types::Stage1LutKey;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

#[inline]
pub(super) fn get_stage1_chunk_params() -> (usize, usize, usize) {
    // Allow zeros as sentinels to enable baked defaults downstream (ALIGN=M, TARGET=128)
    let mult = *ST1_MULT
        .get_or_init(|| env_usize("DSD2DXD_STAGE1_CHUNK_MULT", 0));
    let align = *ST1_ALIGN
        .get_or_init(|| env_usize("DSD2DXD_STAGE1_CHUNK_ALIGN", 0));
    let target = *ST1_TARGET
        .get_or_init(|| env_usize("DSD2DXD_STAGE1_CHUNK_TARGET", 256));
    (mult, align, target)
}

pub(super) fn get_or_build_stage1_lut(
    right_half: &[f64],
    l: u32,
) -> Arc<Vec<Vec<[f64; 256]>>> {
    let key = Stage1LutKey {
        l,
        n: right_half.len() as u32,
        hash: hash_f64_slice_fnv1a(right_half),
    };
    let cache =
        STAGE1_LUT_CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    // Fast path: try hit
    if let Some(found) = cache.lock().unwrap().get(&key) {
        return found.clone();
    }
    // Miss: build and insert
    let lut = build_stage1_lut_from_right_half(right_half, l);
    let arc = Arc::new(lut);
    cache.lock().unwrap().insert(key, arc.clone());
    arc
}
