// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::decim_firsym::DecimFIRSym;
use super::stage1_poly::Stage1Poly;
use crate::filters_lm::HTAPS_1_34MHZ_7TO1_EQ;
use crate::filters_lm::HTAPS_2_68MHZ_7TO1_EQ;
use crate::filters_lm::HTAPS_2_68MHZ_14TO1_EQ;
use crate::filters_lm::HTAPS_2_68MHZ_28TO1_EQ;
use crate::filters_lm::HTAPS_2MHZ_7TO1_EQ;
use crate::filters_lm::HTAPS_4MHZ_7TO1_EQ;
use crate::filters_lm::HTAPS_288K_3TO1_EQ;
use crate::filters_lm::HTAPS_576K_3TO1_EQ;
use crate::filters_lm::HTAPS_DDRX5_7TO_1_EQ;
use crate::filters_lm::HTAPS_DDRX5_14TO1_EQ; // ADD first-stage half taps (5× up, 14:1 down)
use crate::filters_lm::HTAPS_DDRX10_21TO1_EQ;
use crate::filters_lm::HTAPS_DSDX5_7TO1_EQ;
use crate::filters_lm::HTAPS_DSDX10_21TO1_EQ;
use log::debug;
use std::error::Error;

pub struct LMResampler {
    // Unified Stage1 polyphase
    pub(super) stage1_poly: Option<Stage1Poly>,
    pub(super) stage2_decim: Option<DecimFIRSym>,
    pub(super) stage3_decim: Option<DecimFIRSym>,
    // Reusable buffer for batching Stage1 outputs before pushing to s1 ring
    pub(super) s1_scratch: Vec<f64>,
    pub(super) s2_scratch: Vec<f64>,
}

impl LMResampler {
    pub fn new(
        l: u32,
        m: i32,
        out_rate: u32,
    ) -> Result<Self, Box<dyn Error>> {
        match m {
            588 => {
                // DSD256 -> 96k two‑stage path: (×5 -> /21) => ~10.752 MHz -> /28 => 96k
                if out_rate == 96_000 && l == 5 {
                    debug!(
                        "Two-stage DSD256->96k: (×{} -> /21) -> /28 [DDRX10_21TO1 + 2.68MHz 28:1]",
                        l
                    );
                    return Ok(Self {
                        stage1_poly: Some(Stage1Poly::new(
                            &HTAPS_DDRX10_21TO1_EQ[..],
                            l,
                            21,
                        )),
                        stage2_decim: Some(DecimFIRSym::new_from_half(
                            &HTAPS_2_68MHZ_28TO1_EQ[..],
                            28,
                        )),
                        stage3_decim: None,
                        s2_scratch: Vec::new(),
                        s1_scratch: Vec::new(),
                    });
                }
                return Err(
                    "Unsupported 588: must be out_rate=96k and L=5".into(),
                );
            }
            294 => {
                // DSD256 -> 192k two‑stage path: (×5 -> /21) => 2.688 MHz -> /14 => 192k
                if out_rate == 192_000 && l == 5 {
                    debug!(
                        "Two-stage DSD256->192k: (×{} -> /21) -> /14 [DDRX10_21TO1 + 2.68MHz 14:1]",
                        l
                    );
                    return Ok(Self {
                        stage1_poly: Some(Stage1Poly::new(
                            &HTAPS_DDRX10_21TO1_EQ[..],
                            l,
                            21,
                        )),
                        stage2_decim: Some(DecimFIRSym::new_from_half(
                            &HTAPS_2_68MHZ_14TO1_EQ[..],
                            14,
                        )),
                        stage3_decim: None,
                        s2_scratch: Vec::new(),
                        s1_scratch: Vec::new(),
                    });
                }
                // Original cascade Stage1 definitions
                debug!(
                    "Equiripple L/M path: L={} M=294 — (×L -> /14 -> /7 -> /3) [Stage2/3 direct].",
                    l
                );
                return Ok(Self {
                    // Stage 2 (decimator by 7)
                    stage2_decim: Some(DecimFIRSym::new_from_half(
                        &HTAPS_2MHZ_7TO1_EQ,
                        7,
                    )),
                    // Stage 3 (decimator by 3)
                    stage3_decim: Some(DecimFIRSym::new_from_half(
                        &HTAPS_288K_3TO1_EQ,
                        3,
                    )),
                    stage1_poly: Some(Stage1Poly::new(
                        &HTAPS_DDRX5_14TO1_EQ,
                        l,
                        14,
                    )),
                    s2_scratch: Vec::new(),
                    s1_scratch: Vec::new(),
                });
            }
            147 => {
                // DSD128 -> 384k two‑stage path (×L -> /21) -> /7
                if out_rate == 384_000 {
                    debug!(
                        "Two-stage L={}/M=147 path enabled: (×L -> /21 (poly) -> /7) => 384k",
                        l
                    );
                    return Ok(Self {
                        stage1_poly: Some(Stage1Poly::new(
                            &HTAPS_DDRX10_21TO1_EQ[..],
                            l,
                            21,
                        )),
                        stage2_decim: Some(DecimFIRSym::new_from_half(
                            &HTAPS_2_68MHZ_7TO1_EQ[..],
                            7,
                        )),
                        stage3_decim: None,
                        s2_scratch: Vec::new(),
                        s1_scratch: Vec::new(),
                    });
                }

                if out_rate == 192_000 {
                    if l == 5 {
                        // DSD128 -> 192k three-stage path
                        debug!(
                            "Three-stage L=5/M=147 path enabled: (×5 -> /7 (poly) -> /7 -> /3) => 192k"
                        );
                        return Ok(Self {
                            stage1_poly: Some(Stage1Poly::new(
                                &HTAPS_DDRX5_7TO_1_EQ[..],
                                l,
                                7,
                            )),
                            stage2_decim: Some(
                                DecimFIRSym::new_from_half(
                                    &HTAPS_4MHZ_7TO1_EQ[..],
                                    7,
                                ),
                            ),
                            stage3_decim: Some(
                                DecimFIRSym::new_from_half(
                                    &HTAPS_576K_3TO1_EQ[..],
                                    3,
                                ),
                            ),
                            s2_scratch: Vec::new(),
                            s1_scratch: Vec::new(),
                        });
                    } else if l == 10 {
                        // DSD64 -> 192k two-stage path (existing)
                        debug!(
                            "Two-stage L=10/M=147 path enabled: (×10 -> /21 (poly) -> /7) => 192k"
                        );
                        return Ok(Self {
                            stage1_poly: Some(Stage1Poly::new(
                                &HTAPS_DSDX10_21TO1_EQ[..],
                                l,
                                21,
                            )),
                            stage2_decim: Some(
                                DecimFIRSym::new_from_half(
                                    &HTAPS_1_34MHZ_7TO1_EQ[..],
                                    7,
                                ),
                            ),
                            stage3_decim: None,
                            s2_scratch: Vec::new(),
                            s1_scratch: Vec::new(),
                        });
                    }
                }

                debug!(
                    "Equiripple L/M path: L={} M=147 — (×L -> /7 -> /7 -> /3) [Stage2/3 direct] => 96K",
                    l
                );
                return Ok(Self {
                    stage1_poly: Some(Stage1Poly::new(
                        &HTAPS_DSDX5_7TO1_EQ[..],
                        l,
                        7,
                    )),
                    // Stage 2 (decimator by 7)
                    stage2_decim: Some(DecimFIRSym::new_from_half(
                        &HTAPS_2MHZ_7TO1_EQ[..],
                        7,
                    )),
                    // Stage 3 (decimator by 3)
                    stage3_decim: Some(DecimFIRSym::new_from_half(
                        &HTAPS_288K_3TO1_EQ[..],
                        3,
                    )),
                    s2_scratch: Vec::new(),
                    s1_scratch: Vec::new(),
                });
            }
            _ => return Err("Unsupported L/M combination".into()),
        }
    }

    // Returns number of PCM frames produced into `out`.
    #[inline(always)]
    pub fn process_bytes_lm(
        &mut self,
        bytes: &[u8],
        out: &mut [f64],
    ) -> usize {
        let s1 = match self.stage1_poly.as_mut() {
            Some(x) => x,
            None => return 0,
        };
        let p2 = match self.stage2_decim.as_mut() {
            Some(x) => x,
            None => return 0,
        };
        let mut p3_opt = self.stage3_decim.as_mut();

        let mut produced_total = 0usize;
        let mut i = 0usize; // byte cursor

        // Precompute an upper bound on stage1 outputs/byte to size chunks conservatively.
        let y1_per_byte_ub =
            ((8 * s1.l as usize) + (s1.m as usize) - 1) / (s1.m as usize);
        let y1_per_byte_ub = y1_per_byte_ub.max(1);

        // Helper to emit stage1 outputs for a byte into s1_scratch
        let push_byte =
            |b: u8, s1: &mut Stage1Poly, dst: &mut Vec<f64>| {
                for bit in 0..8 {
                    s1.push_all((b >> bit) & 1, |y1| dst.push(y1));
                }
            };

        while i < bytes.len() && produced_total < out.len() {
            // Budget frames we can still write this call
            let out_budget = out.len() - produced_total;
            // Derive upstream budgets based on whether Stage3 exists
            let (need_s2_in, need_s1_out) = if let Some(ref p3) = p3_opt {
                let s2 = out_budget.saturating_mul(p3.decim);
                (s2, s2.saturating_mul(p2.decim))
            } else {
                // Two-stage: Stage2 writes straight to out
                (out_budget, out_budget.saturating_mul(p2.decim))
            };

            // Take at most this many bytes this iteration so that, even in the worst case,
            // stage1 outputs won't exceed what downstream can consume.
            // ceil(need_s1_out / y1_per_byte_ub)
            let mut take_bytes = if need_s1_out == 0 {
                0
            } else {
                (need_s1_out + y1_per_byte_ub - 1) / y1_per_byte_ub
            };
            take_bytes = take_bytes.min(bytes.len() - i);
            if take_bytes == 0 {
                break;
            }

            // 1) Stage1: generate into s1_scratch
            self.s1_scratch.clear();
            // Reserve enough for worst case to avoid reallocation branches
            let reserve = take_bytes.saturating_mul(y1_per_byte_ub);
            if self.s1_scratch.capacity() < reserve {
                self.s1_scratch
                    .reserve(reserve - self.s1_scratch.capacity());
            }
            let mut consumed_bytes = 0usize;
            for &byte in &bytes[i..i + take_bytes] {
                push_byte(byte, s1, &mut self.s1_scratch);
                consumed_bytes += 1;
                if self.s1_scratch.len() >= need_s1_out {
                    break;
                }
            }

            // 2) Stage2: decimate; target is either s2_scratch (3-stage) or out (2-stage)
            let used_s1 =
                core::cmp::min(self.s1_scratch.len(), need_s1_out);
            if let Some(ref mut p3) = p3_opt {
                let cap_s2 = need_s2_in.max(1);
                if self.s2_scratch.len() < cap_s2 {
                    self.s2_scratch.resize(cap_s2, 0.0);
                }
                let n2 = p2.process_block(
                    &self.s1_scratch[..used_s1],
                    &mut self.s2_scratch[..cap_s2],
                );
                // 3) Stage3: decimate into out
                let n3 = p3.process_block(
                    &self.s2_scratch[..n2],
                    &mut out[produced_total..],
                );
                produced_total += n3;
            } else {
                // Two-stage: write directly to out
                let n2 = p2.process_block(
                    &self.s1_scratch[..used_s1],
                    &mut out[produced_total..],
                );
                produced_total += n2;
            }

            // Advance byte cursor by the number of bytes we actually consumed in Stage1.
            i += consumed_bytes;
        }
        produced_total
    }

    #[inline(always)]
    pub fn process_interleaved_bytes_lm(
        &mut self,
        bytes: &[u8],
        channel: usize,
        channels: usize,
        reverse_bits: bool,
        out: &mut [f64],
    ) -> usize {
        let s1 = match self.stage1_poly.as_mut() {
            Some(x) => x,
            None => return 0,
        };
        let p2 = match self.stage2_decim.as_mut() {
            Some(x) => x,
            None => return 0,
        };
        if channels == 0 || channel >= bytes.len() {
            return 0;
        }
        let mut p3_opt = self.stage3_decim.as_mut();

        let mut produced_total = 0usize;
        let mut consumed_total = 0usize;
        let total_bytes = (bytes.len() - channel).div_ceil(channels);
        let mut pos = channel;
        let y1_per_byte_ub =
            ((8 * s1.l as usize) + (s1.m as usize) - 1) / (s1.m as usize);
        let y1_per_byte_ub = y1_per_byte_ub.max(1);

        let push_byte =
            |b: u8, s1: &mut Stage1Poly, dst: &mut Vec<f64>| {
                for bit in 0..8 {
                    s1.push_all((b >> bit) & 1, |y1| dst.push(y1));
                }
            };

        while consumed_total < total_bytes && produced_total < out.len() {
            let out_budget = out.len() - produced_total;
            let (need_s2_in, need_s1_out) = if let Some(ref p3) = p3_opt {
                let s2 = out_budget.saturating_mul(p3.decim);
                (s2, s2.saturating_mul(p2.decim))
            } else {
                (out_budget, out_budget.saturating_mul(p2.decim))
            };

            let mut take_bytes = if need_s1_out == 0 {
                0
            } else {
                need_s1_out.div_ceil(y1_per_byte_ub)
            };
            take_bytes = take_bytes.min(total_bytes - consumed_total);
            if take_bytes == 0 {
                break;
            }

            self.s1_scratch.clear();
            let reserve = take_bytes.saturating_mul(y1_per_byte_ub);
            if self.s1_scratch.capacity() < reserve {
                self.s1_scratch
                    .reserve(reserve - self.s1_scratch.capacity());
            }
            let mut consumed_bytes = 0usize;
            for _ in 0..take_bytes {
                let mut byte = bytes[pos];
                if reverse_bits {
                    byte = byte.reverse_bits();
                }
                push_byte(byte, s1, &mut self.s1_scratch);
                consumed_bytes += 1;
                pos += channels;
                if self.s1_scratch.len() >= need_s1_out {
                    break;
                }
            }

            let used_s1 =
                core::cmp::min(self.s1_scratch.len(), need_s1_out);
            if let Some(ref mut p3) = p3_opt {
                let cap_s2 = need_s2_in.max(1);
                if self.s2_scratch.len() < cap_s2 {
                    self.s2_scratch.resize(cap_s2, 0.0);
                }
                let n2 = p2.process_block(
                    &self.s1_scratch[..used_s1],
                    &mut self.s2_scratch[..cap_s2],
                );
                let n3 = p3.process_block(
                    &self.s2_scratch[..n2],
                    &mut out[produced_total..],
                );
                produced_total += n3;
            } else {
                let n2 = p2.process_block(
                    &self.s1_scratch[..used_s1],
                    &mut out[produced_total..],
                );
                produced_total += n2;
            }

            consumed_total += consumed_bytes;
        }
        produced_total
    }
}
