// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[inline]
pub(super) fn round_up_to_multiple(x: usize, a: usize) -> usize {
    if a == 0 {
        return x;
    }
    if x == 0 {
        return 0;
    }
    ((x + a - 1) / a) * a
}

#[inline]
pub(super) fn round_down_to_multiple(x: usize, a: usize) -> usize {
    if a == 0 {
        return x;
    }
    (x / a) * a
}
