// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::compute::compute_stage1_chunk;
use super::consts::ST1_DIAG_ONCE;
use super::env_mod::any_env_present;
use super::get::get_or_build_stage1_lut;
use super::get::get_stage1_chunk_params;
use super::types::Stage1Mode;
use log::debug;
use std::sync::Arc;

#[derive(Debug)]
pub(super) struct Stage1Poly {
    // Shared
    pub(super) l: u32,
    pub(super) m: u32,
    // Bit-packed ring (one bit per input sample): 1 for +1, 0 for -1
    pub(super) ring_bits: Vec<u64>,
    pub(super) bits_mask: usize, // same capacity as ring (power of 2) - 1
    pub(super) wbits: usize,     // next write bit index
    pub(super) mode: Stage1Mode,
    // Precomputed LUTs (f64 only)
    pub(super) lut_f64: Option<Arc<Vec<Vec<[f64; 256]>>>>,
    // Byte-oriented ring mirroring newest-first 8-bit windows per input bit
    pub(super) byte_ring: Vec<u8>,
    pub(super) byte_mask: usize,
    pub(super) wbyte: usize,
    pub(super) rolling_byte: u8,
    // Legacy SlotSim fields removed
    pub(super) delay_high: u64,
    pub(super) high_index: u64,
    pub(super) phase1: u32,
    // Accum fields
    pub(super) acc: u32,
    pub(super) phase_mod: u32,
    pub(super) input_count: u64,
    pub(super) input_delay: u64,
    // Common
    pub(super) primed: bool,
}

impl Stage1Poly {
    pub(super) fn new(right_half: &[f64], l: u32, m: u32) -> Self {
        // Full symmetric taps length when mirroring right_half as [rev(right_half), right_half]
        let n = (right_half.len() * 2) as u64;
        let delay_high = (n - 1) / 2; // (N-1)/2
        // Max taps per phase is ceil(n / l)
        let max_len = ((n as usize) + l as usize - 1) / l as usize;
        let cap = max_len.next_power_of_two().max(128);
        let input_delay = (delay_high + (l as u64 - 1)) / l as u64; // used only in Accum. Always use f64 LUTs
        let lut_f64: Option<Arc<Vec<Vec<[f64; 256]>>>> =
            Some(get_or_build_stage1_lut(right_half, l));
        // Determine maximum groups across phases to size the byte ring
        let mut groups_max = 0usize;
        if let Some(ref tbl) = lut_f64 {
            for phase in tbl.iter() {
                groups_max = groups_max.max(phase.len());
            }
        }
        let byte_cap = (groups_max + 16).next_power_of_two().max(32);
        let me = Self {
            l,
            m,
            ring_bits: vec![0u64; (cap + 63) / 64],
            bits_mask: cap - 1,
            wbits: 0,
            mode: if m == 21 {
                Stage1Mode::Accum
            } else {
                Stage1Mode::SlotSim
            },
            delay_high,
            high_index: 0,
            phase1: 0,
            lut_f64,
            byte_ring: vec![0u8; byte_cap],
            byte_mask: byte_cap - 1,
            wbyte: 0,
            rolling_byte: 0,
            acc: 0,
            phase_mod: 0,
            input_count: 0,
            input_delay,
            primed: false,
        };

        // One-time Stage1 diagnostics when env vars are set (prints to stderr, without -v)
        if ST1_DIAG_ONCE.set(()).is_ok()
            && any_env_present(&[
                "DSD2DXD_STAGE1_CHUNK_MULT",
                "DSD2DXD_STAGE1_CHUNK_TARGET",
                "DSD2DXD_STAGE1_CHUNK_ALIGN",
            ])
        {
            // Report groups/phase range and effective chunk + threading summary
            let (min_g, max_g) = if let Some(ref tbl) = me.lut_f64 {
                if tbl.is_empty() {
                    (0, 0)
                } else {
                    let mut min_g = usize::MAX;
                    let mut max_g = 0usize;
                    for phase in tbl.iter() {
                        let g = phase.len();
                        if g < min_g {
                            min_g = g;
                        }
                        if g > max_g {
                            max_g = g;
                        }
                    }
                    (min_g, max_g)
                }
            } else {
                (0, 0)
            };
            let (st1_mult, st1_align, st1_target) =
                get_stage1_chunk_params();
            let example_groups = max_g;
            let chunk_eff = if example_groups > 0 {
                compute_stage1_chunk(example_groups, m as usize, l)
            } else {
                0
            };
            debug!(
                "[CFG] Stage1 L={} M={}: groups/phase={}..{}, chunk_eff={} mode=lut(f64) (params: MULT={}, TARGET={}, ALIGN={} [0=>M])",
                l,
                m,
                min_g,
                max_g,
                chunk_eff,
                st1_mult,
                st1_target,
                st1_align
            );
        }
        me
    }

    #[inline(always)]
    pub(super) fn set_next_bit(&mut self, is_pos: bool) {
        let word = self.wbits >> 6;
        let bit = self.wbits & 63;
        if is_pos {
            self.ring_bits[word] |= 1u64 << bit;
        } else {
            self.ring_bits[word] &= !(1u64 << bit);
        }
        self.wbits = (self.wbits + 1) & self.bits_mask;
        // Update rolling byte (newest-first in LSB) and write to byte ring
        let b = if is_pos { 1u8 } else { 0u8 };
        self.rolling_byte = ((self.rolling_byte << 1) & 0xFF) | b;
        self.byte_ring[self.wbyte] = self.rolling_byte;
        self.wbyte = (self.wbyte + 1) & self.byte_mask;
    }

    #[inline(always)]
    pub(super) fn push_all<F: FnMut(f64)>(
        &mut self,
        bit: u8,
        mut emit: F,
    ) {
        match self.mode {
            Stage1Mode::Accum => {
                self.push_accum_all(bit, emit);
            }
            Stage1Mode::SlotSim => {
                // Original slot simulation at high-rate: write once, advance L slots
                self.set_next_bit(bit != 0);
                for _ in 0..self.l {
                    self.sim_high_slot(&mut emit);
                }
            }
        }
    }

    #[inline]
    pub(super) fn sim_high_slot<F: FnMut(f64)>(&mut self, emit: &mut F) {
        let idx_high = self.high_index;
        self.high_index += 1;
        if !self.primed {
            if idx_high >= self.delay_high {
                self.primed = true;
                self.phase1 = 0;
            }
            return;
        }
        self.phase1 += 1;
        if self.phase1 != self.m {
            return;
        }
        self.phase1 = 0;
        let phase = (idx_high % self.l as u64) as usize;
        let tbl = self.lut_f64.as_ref().unwrap();
        // Use chunked summation with baked chunk size
        let chunk = compute_stage1_chunk(
            tbl[phase].len(),
            self.m as usize,
            self.l,
        );
        let sum = self.sum_phase_groups_chunked(&tbl[phase][..], chunk);
        emit(sum);
    }

    // Accumulator mode: emit all outputs scheduled for this input bit
    #[inline(always)]
    pub(super) fn push_accum_all<F: FnMut(f64)>(
        &mut self,
        bit: u8,
        mut emit: F,
    ) {
        // Update bitset only
        self.set_next_bit(bit != 0);
        self.input_count += 1;
        self.acc += self.l;
        // Possibly produce multiple outputs if acc exceeds m multiple times
        while self.acc >= self.m {
            self.acc -= self.m;
            if !self.primed {
                if self.input_count >= self.input_delay {
                    self.primed = true;
                } else {
                    // Advance phase even when not emitting to keep alignment
                    self.phase_mod =
                        (self.phase_mod + (self.m % self.l)) % self.l;
                    continue;
                }
            }
            let phase = self.phase_mod as usize;
            let tbl = self.lut_f64.as_ref().unwrap();
            let chunk = compute_stage1_chunk(
                tbl[phase].len(),
                self.m as usize,
                self.l,
            );
            let sum =
                self.sum_phase_groups_chunked(&tbl[phase][..], chunk);
            emit(sum);
            self.phase_mod = (self.phase_mod + (self.m % self.l)) % self.l;
        }
    }

    // Sum all phase groups using the bit-packed ring and per-group
    // LUTs, but process groups in chunks of up to `chunk_bytes` to
    // reduce loop overhead and improve locality of byte extraction.
    #[inline]
    pub(super) fn sum_phase_groups_chunked(
        &self,
        phase_lut: &[[f64; 256]],
        chunk_bytes: usize,
    ) -> f64 {
        let mut sum = 0.0;
        let total_groups = phase_lut.len();
        if total_groups == 0 {
            return 0.0;
        }
        // Start at last written rolling byte (newest 8-bit window)
        let mut bidx =
            (self.wbyte.wrapping_add(self.byte_mask)) & self.byte_mask; // newest byte index (time t)
        let capb = self.byte_mask + 1;
        let mask = self.byte_mask;
        let mut g = 0usize;
        while g < total_groups {
            let this_chunk = core::cmp::min(chunk_bytes, total_groups - g);
            // Non-unrolled inner loop
            let mut k = 0usize;
            while k < this_chunk {
                let idx = bidx
                    .wrapping_add(capb)
                    .wrapping_sub((k as usize) << 3)
                    & mask;
                let byte = self.byte_ring[idx] as usize;
                sum += phase_lut[g + k][byte];
                k += 1;
            }
            // Advance bidx by the number of groups processed in this chunk
            bidx = bidx
                .wrapping_add(capb)
                .wrapping_sub((this_chunk as usize) << 3)
                & mask;
            g += this_chunk;
        }
        sum
    }
}
