// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Stage1Mode {
    SlotSim,
    Accum,
}

pub(super) type Stage1LutTable = Vec<Vec<[f64; 256]>>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) struct Stage1LutKey {
    pub(super) l: u32,
    pub(super) n: u32,
    pub(super) hash: u64,
}
