// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::DEFAULT_WAV_RATE;
use super::misc::area_label;
use super::misc::sanitize;
use super::output_format::OutputFormat;
use super::output_format::print_usage;
use super::types::ExampleResult;
use super::write::write_track_as_wav;
use std::env;
use std::fs::{self, File};
use std::io::BufWriter;
use std::path::{Path, PathBuf};
use symphonia_format_sacd::{SacdAreaKind, SacdError, SacdIso, write_track_as_dsf};

pub(super) fn run() -> ExampleResult<()> {
    let args = Args::parse()?;
    fs::create_dir_all(&args.output_dir)?;
    let iso = SacdIso::open(&args.input)?;
    let mut extracted = 0usize;

    for area in &iso.disc().areas {
        if !args.include_area(area.kind) {
            continue;
        }

        for track in &area.tracks {
            if let Some(selected) = args.track
                && track.number != selected
            {
                continue;
            }

            let filename = format!(
                "{:02}-{}-{}.{}",
                track.number,
                area_label(area.kind),
                sanitize(track.metadata.title.as_deref().unwrap_or("track")),
                args.format.extension(),
            );
            let path = args.output_dir.join(filename);
            let reader = iso.packet_reader(area.index, track.index)?;
            let output = BufWriter::new(File::create(&path)?);
            let frames = match args.format {
                OutputFormat::Dsf => write_track_as_dsf(output, reader)?,
                OutputFormat::WavPcm24 | OutputFormat::WavF32 => {
                    let encoding = args
                        .format
                        .wav_encoding()
                        .ok_or(SacdError::InvalidIso("selected format is not WAV"))?;
                    write_track_as_wav(output, reader, encoding, args.wav_rate)?
                }
            };
            println!("wrote {} ({} SACD frames)", path.display(), frames);
            extracted += 1;
        }
    }

    if extracted == 0 {
        return Err(SacdError::InvalidIso("no matching tracks were extracted").into());
    }

    Ok(())
}

#[derive(Debug)]
pub(super) struct Args {
    pub(super) input: PathBuf,
    pub(super) output_dir: PathBuf,
    pub(super) stereo: bool,
    pub(super) multichannel: bool,
    pub(super) track: Option<u8>,
    pub(super) format: OutputFormat,
    pub(super) wav_rate: u32,
}

impl Args {
    pub(super) fn parse() -> ExampleResult<Self> {
        Self::parse_from(env::args().skip(1))
    }

    pub(super) fn parse_from<I>(args: I) -> ExampleResult<Self>
    where
        I: IntoIterator<Item = String>,
    {
        let mut input = None;
        let mut output_dir = None;
        let mut stereo = false;
        let mut multichannel = false;
        let mut track = None;
        let mut format = OutputFormat::default();
        let mut wav_rate = DEFAULT_WAV_RATE;
        let mut iter = args.into_iter();

        while let Some(arg) = iter.next() {
            match arg.as_str() {
                "--stereo" => stereo = true,
                "--multichannel" => multichannel = true,
                "--all" => {
                    stereo = true;
                    multichannel = true;
                }
                "--track" => {
                    let Some(value) = iter.next() else {
                        return Err(SacdError::InvalidIso("--track requires a track number").into());
                    };
                    track = Some(
                        value
                            .parse::<u8>()
                            .map_err(|_| SacdError::InvalidIso("invalid --track value"))?,
                    );
                }
                "--format" | "--output-format" => {
                    let Some(value) = iter.next() else {
                        return Err(SacdError::InvalidIso("--format requires a value").into());
                    };
                    format = OutputFormat::parse(&value)?;
                }
                "--wav-rate" => {
                    let Some(value) = iter.next() else {
                        return Err(SacdError::InvalidIso("--wav-rate requires a value").into());
                    };
                    wav_rate = value
                        .parse::<u32>()
                        .map_err(|_| SacdError::InvalidIso("invalid --wav-rate value"))?;
                }
                "--help" | "-h" => {
                    print_usage();
                    std::process::exit(0);
                }
                _ if input.is_none() => input = Some(PathBuf::from(arg)),
                _ if output_dir.is_none() => output_dir = Some(PathBuf::from(arg)),
                _ => return Err(SacdError::InvalidIso("unexpected argument").into()),
            }
        }

        let Some(input) = input else {
            print_usage();
            return Err(SacdError::InvalidIso("missing input SACD ISO").into());
        };
        let output_dir = output_dir.unwrap_or_else(|| Path::new(".").to_path_buf());

        if !stereo && !multichannel {
            stereo = true;
            multichannel = true;
        }

        Ok(Self {
            input,
            output_dir,
            stereo,
            multichannel,
            track,
            format,
            wav_rate,
        })
    }

    pub(super) fn include_area(&self, kind: SacdAreaKind) -> bool {
        match kind {
            SacdAreaKind::Stereo => self.stereo,
            SacdAreaKind::Multichannel => self.multichannel,
        }
    }
}
