// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use symphonia_format_sacd::SacdAreaKind;

pub(super) const DEFAULT_WAV_RATE: u32 = 176_400;

pub(super) const DST_DECODE_CHUNK_FRAMES: usize = 512;

pub(super) fn wav_channel_mask(channels: u8) -> u32 {
    match channels {
        1 => 0x0004,
        2 => 0x0003,
        5 => 0x0037,
        6 => 0x003f,
        _ => 0,
    }
}

pub(super) fn area_label(kind: SacdAreaKind) -> &'static str {
    match kind {
        SacdAreaKind::Stereo => "stereo",
        SacdAreaKind::Multichannel => "multichannel",
    }
}

pub(super) fn sanitize(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_') {
            out.push(ch);
        } else if ch.is_whitespace() {
            out.push('_');
        }
    }
    if out.is_empty() {
        "track".to_string()
    } else {
        out
    }
}
