// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::DEFAULT_WAV_RATE;
use super::types::ExampleResult;
use super::wav_encoding::WavEncoding;
use symphonia_format_sacd::SacdError;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) enum OutputFormat {
    #[default]
    Dsf,
    WavPcm24,
    WavF32,
}

impl OutputFormat {
    pub(super) fn parse(value: &str) -> ExampleResult<Self> {
        match value.to_ascii_lowercase().as_str() {
            "dsf" => Ok(Self::Dsf),
            "wav" | "wave" | "wav-pcm" | "wav-pcm24" | "wav24" => Ok(Self::WavPcm24),
            "wav-f32" | "wav-float" | "wave-f32" | "wave-float" => Ok(Self::WavF32),
            _ => Err(SacdError::InvalidIso("invalid --format value").into()),
        }
    }

    pub(super) fn extension(self) -> &'static str {
        match self {
            Self::Dsf => "dsf",
            Self::WavPcm24 | Self::WavF32 => "wav",
        }
    }

    pub(super) fn supported_values() -> &'static str {
        "dsf, wav, wav-f32"
    }

    pub(super) fn wav_encoding(self) -> Option<WavEncoding> {
        match self {
            Self::Dsf => None,
            Self::WavPcm24 => Some(WavEncoding::Pcm24),
            Self::WavF32 => Some(WavEncoding::Float32),
        }
    }
}

pub(super) fn print_usage() {
    eprintln!(
        "Usage: extract_sacd <input.iso> [output-dir] [--format FORMAT] [--wav-rate HZ] [--stereo] [--multichannel] [--all] [--track N]\n\nFormats: {}\nDefault WAV rate: {}",
        OutputFormat::supported_values(),
        DEFAULT_WAV_RATE
    );
}
