// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::args;
use super::args::Args;
use super::misc::DEFAULT_WAV_RATE;
use super::output_format::OutputFormat;
use super::wav_encoding::WavEncoding;
use super::wav_writer::WavWriter;
use rayon::prelude::*;
use std::path::PathBuf;

use super::*;

#[test]
fn parse_defaults_to_dsf() {
    let args = Args::parse_from(vec!["disc.iso".to_string()]).unwrap();
    assert_eq!(args.format, OutputFormat::Dsf);
    assert_eq!(args.wav_rate, DEFAULT_WAV_RATE);
}

#[test]
fn parse_wav_output_format() {
    let args = Args::parse_from(vec![
        "disc.iso".to_string(),
        "out".to_string(),
        "--format".to_string(),
        "wav".to_string(),
    ])
    .unwrap();
    assert_eq!(args.format, OutputFormat::WavPcm24);
    assert_eq!(args.output_dir, PathBuf::from("out"));
}

#[test]
fn parse_wav_rate() {
    let args = Args::parse_from(vec![
        "disc.iso".to_string(),
        "--format".to_string(),
        "wav".to_string(),
        "--wav-rate".to_string(),
        "88200".to_string(),
    ])
    .unwrap();
    assert_eq!(args.wav_rate, 88_200);
}

#[test]
fn parse_float_wav_output_format() {
    let args = Args::parse_from(vec![
        "disc.iso".to_string(),
        "--format".to_string(),
        "wav-f32".to_string(),
    ])
    .unwrap();
    assert_eq!(args.format, OutputFormat::WavF32);
}

#[test]
fn wav_writer_defaults_to_pcm24_header() {
    let cursor = std::io::Cursor::new(Vec::new());
    let mut writer = WavWriter::new(cursor, 2, 176_400, WavEncoding::Pcm24).unwrap();
    writer.write_pcm_bytes(&[0; 12]).unwrap();
    let cursor = writer.finalize().unwrap();
    let data = cursor.into_inner();

    assert_eq!(&data[0..4], b"RIFF");
    assert_eq!(
        u32::from_le_bytes([data[16], data[17], data[18], data[19]]),
        40
    );
    assert_eq!(u16::from_le_bytes([data[20], data[21]]), 0xfffe);
    assert_eq!(u16::from_le_bytes([data[22], data[23]]), 2);
    assert_eq!(
        u32::from_le_bytes([data[24], data[25], data[26], data[27]]),
        176_400
    );
    assert_eq!(u16::from_le_bytes([data[34], data[35]]), 24);
    assert_eq!(u16::from_le_bytes([data[38], data[39]]), 24);
    assert_eq!(
        u32::from_le_bytes([data[40], data[41], data[42], data[43]]),
        3
    );
    let data_chunk = find_chunk(&data, b"data").unwrap();
    assert_eq!(
        u32::from_le_bytes([
            data[data_chunk + 4],
            data[data_chunk + 5],
            data[data_chunk + 6],
            data[data_chunk + 7]
        ]),
        12
    );
}

#[test]
fn wav_writer_can_emit_float32_header() {
    let cursor = std::io::Cursor::new(Vec::new());
    let mut writer = WavWriter::new(cursor, 2, 176_400, WavEncoding::Float32).unwrap();
    writer.write_pcm_bytes(&[0; 8]).unwrap();
    let cursor = writer.finalize().unwrap();
    let data = cursor.into_inner();

    assert_eq!(u16::from_le_bytes([data[20], data[21]]), 3);
    assert_eq!(u16::from_le_bytes([data[34], data[35]]), 32);
    let data_chunk = find_chunk(&data, b"data").unwrap();
    assert_eq!(
        u32::from_le_bytes([
            data[data_chunk + 4],
            data[data_chunk + 5],
            data[data_chunk + 6],
            data[data_chunk + 7]
        ]),
        8
    );
}

fn find_chunk(data: &[u8], marker: &[u8; 4]) -> Option<usize> {
    data.windows(marker.len())
        .position(|window| window == marker)
}
