// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::types::ExampleResult;
use super::wav_encoding::WavEncoding;
use super::write::write_dsd_packet_as_wav;
use super::write::write_wav_header;
use rayon::prelude::*;
use rdsd2pcm::{DsdPcmConverter, PcmOutputEncoding};
use std::io::{Seek, SeekFrom, Write};
use symphonia_codec_dst::DstDsdDecoder;
use symphonia_format_sacd::{SACD_SAMPLING_FREQUENCY, SacdError};

pub(super) fn decode_dst_chunk_to_wav<W: Write + Seek>(
    encoded_packets: &[Vec<u8>],
    channel_count: usize,
    converter: &mut DsdPcmConverter,
    wav: &mut WavWriter<W>,
    scratch: &mut Vec<u8>,
) -> ExampleResult<()> {
    let probe_decoder = DstDsdDecoder::new(channel_count, SACD_SAMPLING_FREQUENCY as usize)
        .map_err(|err| SacdError::DstDecode(err.to_string()))?;
    let decoded_frame_bytes = probe_decoder.dsd_frame_bytes();
    let decoded_frames: Result<Vec<Vec<u8>>, SacdError> = encoded_packets
        .par_iter()
        .map_init(
            || {
                DstDsdDecoder::new(channel_count, SACD_SAMPLING_FREQUENCY as usize)
                    .map_err(|err| err.to_string())
            },
            |decoder, encoded| {
                let decoder = decoder
                    .as_mut()
                    .map_err(|err| SacdError::DstDecode(err.clone()))?;
                let mut decoded = vec![0u8; decoded_frame_bytes];
                let written = decoder
                    .decode_frame(encoded, &mut decoded)
                    .map_err(|err| SacdError::DstDecode(err.to_string()))?;
                if written % channel_count != 0 {
                    return Err(SacdError::DstDecode(
                        "decoded frame is not channel aligned".to_string(),
                    ));
                }
                decoded.truncate(written);
                Ok(decoded)
            },
        )
        .collect();

    for decoded in decoded_frames? {
        write_dsd_packet_as_wav(converter, &decoded, wav, scratch)?;
    }
    Ok(())
}

pub(super) struct WavWriter<W> {
    pub(super) writer: W,
    pub(super) channels: u8,
    pub(super) sample_rate: u32,
    pub(super) encoding: WavEncoding,
    pub(super) data_len: u64,
}

impl<W: Write + Seek> WavWriter<W> {
    pub(super) fn new(
        mut writer: W,
        channels: u8,
        sample_rate: u32,
        encoding: WavEncoding,
    ) -> ExampleResult<Self> {
        write_wav_header(&mut writer, channels, sample_rate, encoding, 0)?;
        Ok(Self {
            writer,
            channels,
            sample_rate,
            encoding,
            data_len: 0,
        })
    }

    pub(super) fn write_pcm_bytes(&mut self, bytes: &[u8]) -> ExampleResult<()> {
        let new_data_len = self
            .data_len
            .checked_add(bytes.len() as u64)
            .ok_or(SacdError::InvalidIso("WAV data size overflows"))?;
        if new_data_len > u64::from(u32::MAX - self.encoding.riff_overhead()) {
            return Err(SacdError::InvalidIso("WAV output exceeds the RIFF size limit").into());
        }
        self.writer.write_all(bytes)?;
        self.data_len = new_data_len;
        Ok(())
    }

    pub(super) fn pcm_encoding(&self) -> PcmOutputEncoding {
        self.encoding.pcm_output_encoding()
    }

    pub(super) fn finalize(mut self) -> ExampleResult<W> {
        self.writer.seek(SeekFrom::Start(0))?;
        let data_len = u32::try_from(self.data_len)
            .map_err(|_| SacdError::InvalidIso("WAV output exceeds the RIFF size limit"))?;
        write_wav_header(
            &mut self.writer,
            self.channels,
            self.sample_rate,
            self.encoding,
            data_len,
        )?;
        self.writer.flush()?;
        Ok(self.writer)
    }
}
