// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use rdsd2pcm::PcmOutputEncoding;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum WavEncoding {
    Pcm24,
    Float32,
}

impl WavEncoding {
    pub(super) fn audio_format(self) -> u16 {
        match self {
            Self::Pcm24 => 0xfffe,
            Self::Float32 => 3,
        }
    }

    pub(super) fn bits_per_sample(self) -> u16 {
        match self {
            Self::Pcm24 => 24,
            Self::Float32 => 32,
        }
    }

    pub(super) fn bytes_per_sample(self) -> usize {
        usize::from(self.bits_per_sample() / 8)
    }

    pub(super) fn fmt_len(self) -> u32 {
        match self {
            Self::Pcm24 => 40,
            Self::Float32 => 16,
        }
    }

    pub(super) fn riff_overhead(self) -> u32 {
        20 + self.fmt_len()
    }

    pub(super) fn pcm_output_encoding(self) -> PcmOutputEncoding {
        match self {
            Self::Pcm24 => PcmOutputEncoding::Pcm24Le,
            Self::Float32 => PcmOutputEncoding::Float32Le,
        }
    }
}
