// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::DST_DECODE_CHUNK_FRAMES;
use super::misc::wav_channel_mask;
use super::types::ExampleResult;
use super::wav_encoding::WavEncoding;
use super::wav_writer::WavWriter;
use super::wav_writer::decode_dst_chunk_to_wav;
use rdsd2pcm::{DsdPcmConverter, DsdPcmOptions};
use std::io::{Seek, Write};
use symphonia_format_sacd::{SacdError, SacdFrameFormat, SacdPacket, SacdPacketReader};

pub(super) fn write_track_as_wav<W: Write + Seek, R: std::io::Read + Seek>(
    writer: W,
    mut packets: SacdPacketReader<R>,
    encoding: WavEncoding,
    output_sample_rate: u32,
) -> ExampleResult<u64> {
    let Some(first_packet) = packets.next_packet()? else {
        return Err(SacdError::InvalidIso("selected track contains no packets").into());
    };

    let channel_count = usize::from(first_packet.channel_count);
    let mut converter = DsdPcmConverter::new(DsdPcmOptions {
        output_sample_rate,
        ..DsdPcmOptions::sacd(channel_count)
    })?;
    let mut wav = WavWriter::new(
        writer,
        first_packet.channel_count,
        converter.output_sample_rate(),
        encoding,
    )?;
    let mut scratch = Vec::with_capacity(
        converter.max_output_frames(first_packet.data.len())
            * channel_count
            * encoding.bytes_per_sample(),
    );
    let mut encoded_chunk = Vec::with_capacity(DST_DECODE_CHUNK_FRAMES);
    let mut frames = 0u64;

    match first_packet.frame_format {
        SacdFrameFormat::Dst => {
            encoded_chunk.push(first_packet.data);
            while let Some(packet) = packets.next_packet()? {
                encoded_chunk.push(packet.data);
                if encoded_chunk.len() == DST_DECODE_CHUNK_FRAMES {
                    frames += encoded_chunk.len() as u64;
                    decode_dst_chunk_to_wav(
                        &encoded_chunk,
                        channel_count,
                        &mut converter,
                        &mut wav,
                        &mut scratch,
                    )?;
                    encoded_chunk.clear();
                }
            }
            if !encoded_chunk.is_empty() {
                frames += encoded_chunk.len() as u64;
                decode_dst_chunk_to_wav(
                    &encoded_chunk,
                    channel_count,
                    &mut converter,
                    &mut wav,
                    &mut scratch,
                )?;
            }
        }
        SacdFrameFormat::Dsd3In14 | SacdFrameFormat::Dsd3In16 => {
            write_packet_as_wav(first_packet, &mut converter, &mut wav, &mut scratch)?;
            frames += 1;
            while let Some(packet) = packets.next_packet()? {
                write_packet_as_wav(packet, &mut converter, &mut wav, &mut scratch)?;
                frames += 1;
            }
        }
    }

    let _ = wav.finalize()?;
    Ok(frames)
}

pub(super) fn write_packet_as_wav<W: Write + Seek>(
    packet: SacdPacket,
    converter: &mut DsdPcmConverter,
    wav: &mut WavWriter<W>,
    scratch: &mut Vec<u8>,
) -> ExampleResult<()> {
    write_dsd_packet_as_wav(converter, &packet.data, wav, scratch)
}

pub(super) fn write_dsd_packet_as_wav<W: Write + Seek>(
    converter: &mut DsdPcmConverter,
    dsd: &[u8],
    wav: &mut WavWriter<W>,
    scratch: &mut Vec<u8>,
) -> ExampleResult<()> {
    converter.convert_interleaved_to_bytes(dsd, wav.pcm_encoding(), scratch)?;
    wav.write_pcm_bytes(scratch)?;
    Ok(())
}

pub(super) fn write_wav_header<W: Write>(
    writer: &mut W,
    channels: u8,
    sample_rate: u32,
    encoding: WavEncoding,
    data_len: u32,
) -> std::io::Result<()> {
    let channels = channels.max(1);
    let sample_rate = sample_rate.max(1);
    let byte_rate = sample_rate * u32::from(channels) * encoding.bytes_per_sample() as u32;
    let block_align = u16::from(channels) * encoding.bytes_per_sample() as u16;
    let fmt_len = encoding.fmt_len();
    let riff_len = encoding.riff_overhead().saturating_add(data_len);

    writer.write_all(b"RIFF")?;
    writer.write_all(&riff_len.to_le_bytes())?;
    writer.write_all(b"WAVE")?;
    writer.write_all(b"fmt ")?;
    writer.write_all(&fmt_len.to_le_bytes())?;
    writer.write_all(&encoding.audio_format().to_le_bytes())?;
    writer.write_all(&u16::from(channels).to_le_bytes())?;
    writer.write_all(&sample_rate.to_le_bytes())?;
    writer.write_all(&byte_rate.to_le_bytes())?;
    writer.write_all(&block_align.to_le_bytes())?;
    writer.write_all(&encoding.bits_per_sample().to_le_bytes())?;
    if encoding == WavEncoding::Pcm24 {
        writer.write_all(&22u16.to_le_bytes())?;
        writer.write_all(&encoding.bits_per_sample().to_le_bytes())?;
        writer.write_all(&wav_channel_mask(channels).to_le_bytes())?;
        writer.write_all(&[
            0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38,
            0x9b, 0x71,
        ])?;
    }
    writer.write_all(b"data")?;
    writer.write_all(&data_len.to_le_bytes())?;
    Ok(())
}
