// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// Direct ID3 text-frame -> Vorbis comment field mappings (one-to-one).
/// Frames with special parsing (TRCK, TPOS, TDRC, COMM, USLT, TIPL, TMCL,
/// UFID, W-frames, TXXX) are handled separately in `id3_to_flac_meta`.
pub(super) const ID3_VORBIS_MAP: &[(&str, &str)] = &[
    ("TPE1", "ARTIST"),
    ("TPE2", "ALBUMARTIST"),
    ("TSO2", "ALBUMARTISTSORT"),
    ("TSOA", "ALBUMSORT"),
    ("TSOP", "ARTISTSORT"),
    ("TALB", "ALBUM"),
    ("TIT2", "TITLE"),
    ("TBPM", "BPM"),
    ("TCOM", "COMPOSER"),
    ("TSOC", "COMPOSERSORT"),
    ("TPE3", "CONDUCTOR"),
    ("TCOP", "COPYRIGHT"),
    ("TCON", "GENRE"),
    ("TIT1", "GROUPING"),
    ("TKEY", "KEY"),
    ("TSRC", "ISRC"),
    ("TPUB", "LABEL"),
    ("TLAN", "LANGUAGE"),
    ("TEXT", "LYRICIST"),
    ("TMED", "MEDIA"),
    ("TMOO", "MOOD"),
    ("MVNM", "MOVEMENTNAME"),
    ("TOFN", "ORIGINALFILENAME"),
    ("TDRL", "RELEASEDATE"),
    ("TPE4", "REMIXER"),
    ("TIT3", "SUBTITLE"),
    ("TSOT", "TITLESORT"),
    ("TENC", "ENCODEDBY"),
    ("TSSE", "ENCODERSETTINGS"),
    ("TCMP", "COMPILATION"),
    ("TSST", "DISCSUBTITLE"),
];

/// TXXX description -> Vorbis field name, for entries where they differ.
/// Descriptions not listed here are copied as-is (e.g. REPLAYGAIN_*, ASIN).
pub(super) const ID3_TXXX_VORBIS_MAP: &[(&str, &str)] = &[
    ("MusicBrainz Artist Id", "MUSICBRAINZ_ARTISTID"),
    ("MusicBrainz Album Id", "MUSICBRAINZ_ALBUMID"),
    ("MusicBrainz Album Artist Id", "MUSICBRAINZ_ALBUMARTISTID"),
    ("MusicBrainz Release Group Id", "MUSICBRAINZ_RELEASEGROUPID"),
    ("MusicBrainz Release Track Id", "MUSICBRAINZ_RELEASETRACKID"),
    ("MusicBrainz TRM Id", "MUSICBRAINZ_TRMID"),
    ("MusicBrainz Work Id", "MUSICBRAINZ_WORKID"),
    ("MusicBrainz Disc Id", "MUSICBRAINZ_DISCID"),
    (
        "MusicBrainz Original Artist Id",
        "MUSICBRAINZ_ORIGINALARTISTID",
    ),
    (
        "MusicBrainz Original Album Id",
        "MUSICBRAINZ_ORIGINALALBUMID",
    ),
    ("MusicBrainz Album Release Country", "RELEASECOUNTRY"),
    ("MusicBrainz Album Status", "RELEASESTATUS"),
    ("MusicBrainz Album Type", "RELEASETYPE"),
    ("Acoustid Id", "ACOUSTID_ID"),
    ("Acoustid Fingerprint", "ACOUSTID_FINGERPRINT"),
    ("MusicIP PUID", "MUSICIP_PUID"),
    ("Writer", "WRITER"),
];

/// TIPL/IPLS role string -> Vorbis field name.
pub(super) const ID3_TIPL_VORBIS_MAP: &[(&str, &str)] = &[
    ("arranger", "ARRANGER"),
    ("engineer", "ENGINEER"),
    ("dj-mix", "DJMIXER"),
    ("mix", "MIXER"),
    ("producer", "PRODUCER"),
];
