// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::error::SacdError;
use super::types::SacdResult;

pub(super) fn be_u16(data: &[u8], offset: usize) -> SacdResult<u16> {
    if offset + 2 > data.len() {
        return Err(SacdError::InvalidIso("unexpected end of structure"));
    }
    Ok(u16::from_be_bytes([data[offset], data[offset + 1]]))
}

pub(super) fn be_u32(data: &[u8], offset: usize) -> SacdResult<u32> {
    if offset + 4 > data.len() {
        return Err(SacdError::InvalidIso("unexpected end of structure"));
    }
    Ok(u32::from_be_bytes([
        data[offset],
        data[offset + 1],
        data[offset + 2],
        data[offset + 3],
    ]))
}
