// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::MAX_PACKET_SIZE;
use super::consts::SACD_LSN_SIZE;
use super::consts::time_to_frames;
use super::error::SacdError;
use super::frame_accumulator::FrameAccumulator;
use super::misc::dst_channel_count;
use super::sacd_area::SacdArea;
use super::types::CompleteFrame;
use super::types::FrameInfo;
use super::types::PacketInfo;
use super::types::PacketTrack;
use super::types::SacdResult;
use super::types::SacdTrack;
use symphonia_core::formats::prelude::*;
use symphonia_core::packet::Packet;

pub(super) fn process_audio_sector(
    sector: &[u8; SACD_LSN_SIZE],
    area: &SacdArea,
    track: &SacdTrack,
    pending: &mut FrameAccumulator,
    last_sector: bool,
) -> SacdResult<Vec<CompleteFrame>> {
    let header = sector[0];
    let dst_encoded = (header & 0x01) != 0;
    let frame_info_count = (header >> 2) & 0x07;
    let packet_info_count = (header >> 5) & 0x07;

    if packet_info_count > 7 {
        return Err(SacdError::CorruptTrackTable(
            "audio sector has too many packets",
        ));
    }

    let mut cursor = 1usize;
    let mut packet_infos = Vec::with_capacity(packet_info_count as usize);
    for _ in 0..packet_info_count {
        if cursor + 2 > sector.len() {
            return Err(SacdError::CorruptTrackTable(
                "audio sector packet table is truncated",
            ));
        }
        let b0 = sector[cursor];
        let b1 = sector[cursor + 1];
        cursor += 2;
        let info = PacketInfo {
            frame_start: (b0 & 0x80) != 0,
            data_type: (b0 >> 3) & 0x07,
            packet_length: (((b0 & 0x07) as usize) << 8) | b1 as usize,
        };
        if info.packet_length > MAX_PACKET_SIZE {
            return Err(SacdError::CorruptTrackTable(
                "audio packet exceeds SACD packet limit",
            ));
        }
        packet_infos.push(info);
    }

    let mut frame_infos = Vec::with_capacity(frame_info_count as usize);
    for _ in 0..frame_info_count {
        let info_len = if dst_encoded { 4 } else { 3 };
        if cursor + info_len > sector.len() {
            return Err(SacdError::CorruptTrackTable(
                "audio sector frame table is truncated",
            ));
        }
        let minutes = sector[cursor];
        let seconds = sector[cursor + 1];
        let frames = sector[cursor + 2];
        let flags = if dst_encoded { sector[cursor + 3] } else { 0 };
        cursor += info_len;
        frame_infos.push(FrameInfo {
            timecode_frames: time_to_frames(minutes, seconds, frames),
            sector_count: (flags >> 2) & 0x1f,
            channel_count: dst_channel_count(flags).unwrap_or(area.channel_count),
        });
    }

    let mut completed = Vec::new();
    let mut frame_info_idx = 0usize;

    for info in packet_infos {
        if cursor + info.packet_length > sector.len() {
            return Err(SacdError::CorruptTrackTable(
                "audio packet data is truncated",
            ));
        }
        let packet_data = &sector[cursor..cursor + info.packet_length];
        cursor += info.packet_length;

        if info.data_type != 2 {
            continue;
        }

        if info.frame_start {
            if let Some(frame) = pending.take_if_complete(area) {
                completed.push(frame);
            }
            let frame_info = frame_infos
                .get(frame_info_idx)
                .copied()
                .unwrap_or(FrameInfo {
                    timecode_frames: Some(
                        track.start_frames.saturating_add(completed.len() as u32),
                    ),
                    sector_count: 0,
                    channel_count: area.channel_count,
                });
            frame_info_idx += 1;
            pending.begin(
                dst_encoded,
                frame_info.sector_count,
                frame_info.channel_count,
                frame_info.timecode_frames,
            );
        }

        if pending.started {
            pending.append(packet_data)?;
        }
    }

    if last_sector && let Some(frame) = pending.take_if_complete(area) {
        completed.push(frame);
    }

    Ok(completed)
}

pub(super) fn make_symphonia_packet(
    packet_track: &mut PacketTrack,
    track: &SacdTrack,
    frame: CompleteFrame,
) -> Packet {
    let pts = frame.timecode_frames.unwrap_or_else(|| {
        track
            .start_frames
            .saturating_add(packet_track.packet_index as u32)
    });
    packet_track.packet_index += 1;
    Packet::new(
        packet_track.symphonia_track_id,
        Timestamp::new(pts as i64),
        Duration::new(1),
        frame.data,
    )
}
