// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::num::NonZero;
use symphonia_core::common::FourCc;
use symphonia_core::formats::prelude::*;
use symphonia_core::meta::{MetadataId, MetadataInfo};

pub const SACD_LSN_SIZE: usize = 2048;

pub const SACD_SAMPLING_FREQUENCY: u32 = 2_822_400;

pub const SACD_FRAME_RATE: u32 = 75;

pub const SAMPLES_PER_FRAME: u64 = 588;

pub const FRAME_SIZE_64: usize = 4704;

pub const START_OF_MASTER_TOC: u32 = 510;

pub(super) const MASTER_TOC_LEN: u32 = 10;

pub(super) const MAX_AREA_TOC_SIZE_LSN: u16 = 96;

pub(super) const MAX_PACKET_SIZE: usize = 2045;

pub(super) const MAX_DST_SIZE: usize = 1024 * 64;

pub(super) const SUPPORTED_VERSION_MAJOR: u8 = 1;

pub(super) const SUPPORTED_VERSION_MINOR: u8 = 20;

pub(super) const FORMAT_INFO: FormatInfo = FormatInfo {
    format: FormatId::new(FourCc::new(*b"SACD")),
    short_name: "sacd",
    long_name: "Super Audio CD ISO",
};

pub(super) const METADATA_INFO: MetadataInfo = MetadataInfo {
    metadata: MetadataId::new(FourCc::new(*b"SACD")),
    short_name: "sacd",
    long_name: "Super Audio CD metadata",
};

pub(super) fn time_to_frames(minutes: u8, seconds: u8, frames: u8) -> Option<u32> {
    if seconds >= 60 || frames >= SACD_FRAME_RATE as u8 {
        return None;
    }
    Some(minutes as u32 * 60 * SACD_FRAME_RATE + seconds as u32 * SACD_FRAME_RATE + frames as u32)
}

pub(super) fn sacd_time_base() -> TimeBase {
    TimeBase::new(
        NonZero::new(1).unwrap(),
        NonZero::new(SACD_FRAME_RATE).unwrap(),
    )
}
