// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::io::{self};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum SacdError {
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),
    #[error("invalid SACD ISO: {0}")]
    InvalidIso(&'static str),
    #[error("unsupported SACD version {major}.{minor:02}")]
    UnsupportedVersion { major: u8, minor: u8 },
    #[error("SACD ISO contains no supported stereo or multichannel area")]
    MissingArea,
    #[error("corrupt SACD track table: {0}")]
    CorruptTrackTable(&'static str),
    #[error("track selection is out of range")]
    TrackOutOfRange,
    #[error("SACD seek is unsupported for this request")]
    UnsupportedSeek,
    #[error("DST-to-DSD decode failed: {0}")]
    DstDecode(String),
}
