// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::FRAME_SIZE_64;
use super::consts::MAX_DST_SIZE;
use super::error::SacdError;
use super::sacd_area::SacdArea;
use super::types::CompleteFrame;
use super::types::SacdResult;

#[derive(Debug, Clone, Default)]
pub(super) struct FrameAccumulator {
    pub(super) data: Vec<u8>,
    pub(super) started: bool,
    pub(super) dst_encoded: bool,
    pub(super) sector_count: i32,
    pub(super) channel_count: u8,
    pub(super) timecode_frames: Option<u32>,
}

impl FrameAccumulator {
    pub(super) fn begin(
        &mut self,
        dst_encoded: bool,
        sector_count: u8,
        channel_count: u8,
        timecode_frames: Option<u32>,
    ) {
        self.data.clear();
        self.started = true;
        self.dst_encoded = dst_encoded;
        self.sector_count = i32::from(sector_count);
        self.channel_count = channel_count;
        self.timecode_frames = timecode_frames;
    }

    pub(super) fn append(&mut self, data: &[u8]) -> SacdResult<()> {
        if self.data.len() + data.len() > MAX_DST_SIZE {
            self.started = false;
            return Err(SacdError::CorruptTrackTable(
                "audio frame exceeds maximum packet size",
            ));
        }
        self.data.extend_from_slice(data);
        if self.dst_encoded {
            self.sector_count -= 1;
        }
        Ok(())
    }

    pub(super) fn take_if_complete(&mut self, area: &SacdArea) -> Option<CompleteFrame> {
        if !self.started || self.data.is_empty() {
            return None;
        }

        let complete = if self.dst_encoded {
            self.sector_count <= 0
        } else {
            self.data.len() == usize::from(area.channel_count) * FRAME_SIZE_64
        };

        if complete {
            self.started = false;
            Some(CompleteFrame {
                data: std::mem::take(&mut self.data),
                timecode_frames: self.timecode_frames,
            })
        } else {
            None
        }
    }
}
