// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub use symphonia_codec_dsd::{
    CODEC_ID_DSD, DsdPcmAudioDecoder, DsdPcmAudioDecoder as SacdDsdPcmAudioDecoder,
    register_decoders as register_dsd_decoders,
};
pub use symphonia_codec_dst::{
    CODEC_ID_DST, DstAudioDecoder, DstAudioDecoder as SacdDstAudioDecoder,
    register_decoders as register_dst_decoders,
};

mod be;
mod complete_frame;
mod consts;
mod error;
mod frame_accumulator;
mod misc;
mod read;
mod register;
mod sacd_area;
mod sacd_disc;
mod sacd_error;
mod sacd_format_reader;
mod sacd_frame_format;
mod sacd_iso;
mod sacd_metadata;
mod sacd_packet_reader;
#[cfg(test)]
mod tests;
mod types;
mod write;

pub use consts::*;
pub use error::*;
pub use register::*;
pub use sacd_area::*;
pub use sacd_disc::*;
pub use sacd_format_reader::*;
pub use sacd_frame_format::*;
pub use sacd_iso::*;
pub use sacd_metadata::*;
pub use sacd_packet_reader::*;
pub use types::*;
pub use write::*;
