// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use encoding_rs::{Encoding, ISO_8859_10, SHIFT_JIS, UTF_8};

pub(super) fn dsf_channel_type(channel_count: u8) -> u32 {
    match channel_count {
        1 => 1,
        2 => 2,
        5 => 5,
        6 => 6,
        _ => 0,
    }
}

pub(super) fn dst_channel_count(flags: u8) -> Option<u8> {
    let bit_2 = (flags & 0x02) != 0;
    let bit_3 = (flags & 0x01) != 0;
    match (bit_2, bit_3) {
        (true, false) => Some(6),
        (false, true) => Some(5),
        _ => None,
    }
}

pub(super) fn detect_encoding(raw: &[u8]) -> &'static Encoding {
    if std::str::from_utf8(raw).is_ok() {
        UTF_8
    } else if raw.iter().any(|byte| *byte >= 0x80) {
        SHIFT_JIS
    } else {
        ISO_8859_10
    }
}

pub(super) fn find_chunk(data: &[u8], marker: &[u8; 8]) -> Option<usize> {
    data.windows(marker.len())
        .position(|window| window == marker)
}

pub(super) fn symphonia_track_id(area_index: usize, track_index: usize) -> u32 {
    (area_index as u32) * 1000 + track_index as u32 + 1
}
