// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::be::be_u16;
use super::be::be_u32;
use super::consts::MASTER_TOC_LEN;
use super::consts::MAX_AREA_TOC_SIZE_LSN;
use super::consts::SACD_LSN_SIZE;
use super::consts::START_OF_MASTER_TOC;
use super::consts::time_to_frames;
use super::error::SacdError;
use super::misc::detect_encoding;
use super::misc::find_chunk;
use super::sacd_area::SacdArea;
use super::sacd_error::check_version;
use super::sacd_frame_format::SacdFrameFormat;
use super::sacd_metadata::SacdMetadata;
use super::types::MasterToc;
use super::types::SacdAreaKind;
use super::types::SacdResult;
use super::types::SacdTrack;
use super::types::SacdTrackMetadata;
use std::io::{self, Read, Seek, SeekFrom};

pub(super) fn read_master_toc<R: Read + Seek>(reader: &mut R) -> SacdResult<MasterToc> {
    let mut data = vec![0u8; MASTER_TOC_LEN as usize * SACD_LSN_SIZE];
    read_sectors(reader, START_OF_MASTER_TOC, MASTER_TOC_LEN, &mut data)?;

    if &data[0..8] != b"SACDMTOC" {
        return Err(SacdError::InvalidIso("missing SACDMTOC marker"));
    }

    let major = data[8];
    let minor = data[9];
    check_version(major, minor)?;

    Ok(MasterToc {
        area_1_toc_1_start: be_u32(&data, 64)?,
        area_1_toc_2_start: be_u32(&data, 68)?,
        area_2_toc_1_start: be_u32(&data, 72)?,
        area_2_toc_2_start: be_u32(&data, 76)?,
        area_1_toc_size: be_u16(&data, 84)?,
        area_2_toc_size: be_u16(&data, 86)?,
    })
}

pub(super) fn read_master_text<R: Read + Seek>(reader: &mut R) -> SacdResult<SacdMetadata> {
    let mut sector = [0u8; SACD_LSN_SIZE];
    read_sector(reader, START_OF_MASTER_TOC + 1, &mut sector)?;
    if &sector[0..8] != b"SACDText" {
        return Ok(SacdMetadata::default());
    }

    Ok(SacdMetadata {
        album_title: read_text_at(&sector, be_u16(&sector, 16)? as usize),
        album_artist: read_text_at(&sector, be_u16(&sector, 18)? as usize),
        disc_title: read_text_at(&sector, be_u16(&sector, 32)? as usize),
        disc_artist: read_text_at(&sector, be_u16(&sector, 34)? as usize),
    })
}

pub(super) fn read_area_with_backup<R: Read + Seek>(
    reader: &mut R,
    index: usize,
    primary_lsn: u32,
    backup_lsn: u32,
    toc_size: u16,
) -> SacdResult<Option<SacdArea>> {
    if toc_size == 0 {
        return Ok(None);
    }
    if toc_size > MAX_AREA_TOC_SIZE_LSN {
        return Err(SacdError::InvalidIso(
            "area TOC is larger than the SACD limit",
        ));
    }

    match read_area(reader, index, primary_lsn, toc_size) {
        Ok(area) => Ok(Some(area)),
        Err(primary_err) if backup_lsn > 0 => {
            match read_area(reader, index, backup_lsn, toc_size) {
                Ok(area) => Ok(Some(area)),
                Err(_) => Err(primary_err),
            }
        }
        Err(err) => Err(err),
    }
}

pub(super) fn read_area<R: Read + Seek>(
    reader: &mut R,
    index: usize,
    toc_lsn: u32,
    toc_size: u16,
) -> SacdResult<SacdArea> {
    let mut data = vec![0u8; toc_size as usize * SACD_LSN_SIZE];
    read_sectors(reader, toc_lsn, toc_size as u32, &mut data)?;

    let id = &data[0..8];
    let kind = match id {
        b"TWOCHTOC" => SacdAreaKind::Stereo,
        b"MULCHTOC" => SacdAreaKind::Multichannel,
        _ => return Err(SacdError::InvalidIso("missing area TOC marker")),
    };

    check_version(data[8], data[9])?;

    let declared_size = be_u16(&data, 10)?;
    if declared_size == 0 || declared_size > toc_size {
        return Err(SacdError::InvalidIso("invalid area TOC size"));
    }

    let frame_format = match data[21] & 0x0f {
        0 => SacdFrameFormat::Dst,
        2 => SacdFrameFormat::Dsd3In14,
        3 => SacdFrameFormat::Dsd3In16,
        _ => return Err(SacdError::InvalidIso("unsupported SACD frame format")),
    };

    let channel_count = data[32];
    let config = data[33];
    let extra_settings = config & 0x07;
    let loudspeaker_config = config >> 3;
    let total_frames = time_to_frames(data[64], data[65], data[66]).unwrap_or(0);
    let track_count = data[69] as usize;
    let track_start_lsn = be_u32(&data, 72)?;
    let track_end_lsn = be_u32(&data, 76)?;

    if track_count == 0 {
        return Err(SacdError::CorruptTrackTable("area contains no tracks"));
    }

    let track_offsets = find_chunk(&data, b"SACDTRL1").ok_or(SacdError::CorruptTrackTable(
        "missing SACDTRL1 track LSN table",
    ))?;
    let track_times = find_chunk(&data, b"SACDTRL2").ok_or(SacdError::CorruptTrackTable(
        "missing SACDTRL2 track time table",
    ))?;
    let track_text = find_chunk(&data, b"SACDTTxt");

    let mut tracks = Vec::with_capacity(track_count);
    for track_idx in 0..track_count {
        let start = be_u32(&data, track_offsets + 8 + track_idx * 4)?;
        let declared_len = be_u32(&data, track_offsets + 8 + 255 * 4 + track_idx * 4)?;
        let next_start = if track_idx + 1 < track_count {
            be_u32(&data, track_offsets + 8 + (track_idx + 1) * 4)?
        } else {
            track_end_lsn
                .checked_add(1)
                .ok_or(SacdError::CorruptTrackTable("track end LSN overflows"))?
        };
        let length = next_start
            .checked_sub(start)
            .ok_or(SacdError::CorruptTrackTable(
                "track starts are not monotonic",
            ))?;
        let length = if declared_len > 0 {
            declared_len.min(length)
        } else {
            length
        };

        if start < track_start_lsn || start > track_end_lsn || length == 0 {
            return Err(SacdError::CorruptTrackTable(
                "track LSN range is outside area",
            ));
        }

        let start_time_off = track_times + 8 + track_idx * 4;
        let duration_time_off = track_times + 8 + 255 * 4 + track_idx * 4;
        let start_frames = time_to_frames(
            data[start_time_off],
            data[start_time_off + 1],
            data[start_time_off + 2],
        )
        .unwrap_or(0);
        let duration_frames = time_to_frames(
            data[duration_time_off],
            data[duration_time_off + 1],
            data[duration_time_off + 2],
        )
        .unwrap_or(0);

        tracks.push(SacdTrack {
            index: track_idx,
            number: track_idx.saturating_add(1).min(u8::MAX as usize) as u8,
            start_lsn: start,
            length_lsn: length,
            start_frames,
            duration_frames,
            metadata: track_text
                .and_then(|offset| read_track_text(&data, offset, track_idx).ok())
                .unwrap_or_default(),
        });
    }

    Ok(SacdArea {
        index,
        kind,
        frame_format,
        channel_count,
        loudspeaker_config,
        extra_settings,
        track_start_lsn,
        track_end_lsn,
        total_frames,
        tracks,
    })
}

pub(super) fn read_track_text(
    data: &[u8],
    chunk_offset: usize,
    track_idx: usize,
) -> SacdResult<SacdTrackMetadata> {
    let Some(pos_off) = chunk_offset
        .checked_add(8)
        .and_then(|x| x.checked_add(track_idx.checked_mul(2)?))
    else {
        return Ok(SacdTrackMetadata::default());
    };
    if pos_off + 2 > data.len() {
        return Ok(SacdTrackMetadata::default());
    }
    let rel = be_u16(data, pos_off)? as usize;
    if rel == 0 {
        return Ok(SacdTrackMetadata::default());
    }
    let Some(mut cursor) = chunk_offset.checked_add(rel) else {
        return Ok(SacdTrackMetadata::default());
    };
    if cursor + 4 > data.len() {
        return Ok(SacdTrackMetadata::default());
    }

    let count = data[cursor] as usize;
    cursor += 4;
    let mut metadata = SacdTrackMetadata::default();

    for _ in 0..count {
        if cursor + 2 > data.len() {
            break;
        }
        let text_type = data[cursor];
        cursor += 2;
        let Some((text, next)) = read_c_string(data, cursor) else {
            break;
        };
        cursor = next;
        match text_type {
            0x01 => metadata.title = Some(text),
            0x02 => metadata.performer = Some(text),
            0x04 => metadata.composer = Some(text),
            _ => {}
        }
    }

    Ok(metadata)
}

pub(super) fn read_text_at(data: &[u8], offset: usize) -> Option<String> {
    if offset == 0 || offset >= data.len() {
        return None;
    }
    read_c_string(data, offset).map(|(text, _)| text)
}

pub(super) fn read_c_string(data: &[u8], offset: usize) -> Option<(String, usize)> {
    let end = data[offset..]
        .iter()
        .position(|byte| *byte == 0)
        .map(|pos| offset + pos)
        .unwrap_or(data.len());
    if end <= offset {
        return None;
    }
    let raw = &data[offset..end];
    let encoding = detect_encoding(raw);
    let (text, _, _) = encoding.decode(raw);
    let text = text.trim_matches(char::from(0)).trim().to_string();
    if text.is_empty() {
        None
    } else {
        Some((text, end.saturating_add(1)))
    }
}

pub(super) fn read_sector<R: Read + Seek>(
    reader: &mut R,
    lsn: u32,
    dest: &mut [u8; SACD_LSN_SIZE],
) -> io::Result<()> {
    reader.seek(SeekFrom::Start(u64::from(lsn) * SACD_LSN_SIZE as u64))?;
    reader.read_exact(dest)?;
    Ok(())
}

pub(super) fn read_sectors<R: Read + Seek>(
    reader: &mut R,
    start_lsn: u32,
    count: u32,
    dest: &mut [u8],
) -> io::Result<()> {
    let expected = count as usize * SACD_LSN_SIZE;
    if dest.len() != expected {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "destination length does not match sector count",
        ));
    }
    reader.seek(SeekFrom::Start(u64::from(start_lsn) * SACD_LSN_SIZE as u64))?;
    reader.read_exact(dest)?;
    Ok(())
}
