// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::sacd_format_reader::SacdFormatReader;
pub use symphonia_codec_dsd::register_decoders as register_dsd_decoders;
pub use symphonia_codec_dst::register_decoders as register_dst_decoders;
use symphonia_core::codecs::registry::CodecRegistry;
use symphonia_core::formats::probe::Probe;

pub fn register_all(probe: &mut Probe) {
    probe.register_format::<SacdFormatReader<'_>>();
}

pub fn register_decoders(registry: &mut CodecRegistry) {
    register_dsd_decoders(registry);
    register_dst_decoders(registry);
}
