// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::sacd_disc::SacdDisc;
use super::sacd_packet_reader::SacdPacketReader;
use super::types::SacdResult;
use std::fs::File;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct SacdIso {
    pub(super) path: PathBuf,
    pub(super) disc: SacdDisc,
}

impl SacdIso {
    pub fn open<P: AsRef<Path>>(path: P) -> SacdResult<Self> {
        let path = path.as_ref().to_path_buf();
        let mut file = File::open(&path)?;
        let disc = SacdDisc::read_from(&mut file)?;
        Ok(Self { path, disc })
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn disc(&self) -> &SacdDisc {
        &self.disc
    }

    pub fn packet_reader(
        &self,
        area_index: usize,
        track_index: usize,
    ) -> SacdResult<SacdPacketReader<File>> {
        let file = File::open(&self.path)?;
        SacdPacketReader::new(file, self.disc.clone(), area_index, track_index)
    }
}
