// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::complete_frame::process_audio_sector;
use super::consts::SACD_LSN_SIZE;
use super::error::SacdError;
use super::frame_accumulator::FrameAccumulator;
use super::read::read_sector;
use super::sacd_area::SacdArea;
use super::sacd_disc::SacdDisc;
use super::types::CompleteFrame;
use super::types::SacdPacket;
use super::types::SacdResult;
use super::types::SacdTrack;
use std::io::{Read, Seek};

pub struct SacdPacketReader<R> {
    pub(super) reader: R,
    pub(super) area: SacdArea,
    pub(super) track: SacdTrack,
    pub(super) current_lsn: u32,
    pub(super) end_lsn: u32,
    pub(super) pending: FrameAccumulator,
    pub(super) packet_index: u64,
}

impl<R: Read + Seek> SacdPacketReader<R> {
    pub fn new(
        reader: R,
        disc: SacdDisc,
        area_index: usize,
        track_index: usize,
    ) -> SacdResult<Self> {
        let area = disc
            .areas
            .get(area_index)
            .cloned()
            .ok_or(SacdError::TrackOutOfRange)?;
        let track = area
            .tracks
            .get(track_index)
            .cloned()
            .ok_or(SacdError::TrackOutOfRange)?;
        let current_lsn = track.start_lsn;
        let end_lsn = track
            .start_lsn
            .checked_add(track.length_lsn)
            .ok_or(SacdError::CorruptTrackTable("track LSN range overflows"))?;

        Ok(Self {
            reader,
            area,
            track,
            current_lsn,
            end_lsn,
            pending: FrameAccumulator::default(),
            packet_index: 0,
        })
    }

    pub fn next_packet(&mut self) -> SacdResult<Option<SacdPacket>> {
        let mut sector = [0u8; SACD_LSN_SIZE];

        while self.current_lsn < self.end_lsn {
            read_sector(&mut self.reader, self.current_lsn, &mut sector)?;
            self.current_lsn += 1;
            let is_last = self.current_lsn >= self.end_lsn;
            let frames =
                process_audio_sector(&sector, &self.area, &self.track, &mut self.pending, is_last)?;

            if let Some(frame) = frames.into_iter().next() {
                let packet = self.frame_to_packet(frame);
                return Ok(Some(packet));
            }
        }

        if let Some(frame) = self.pending.take_if_complete(&self.area) {
            return Ok(Some(self.frame_to_packet(frame)));
        }

        Ok(None)
    }

    pub(super) fn frame_to_packet(&mut self, frame: CompleteFrame) -> SacdPacket {
        let pts = frame.timecode_frames.unwrap_or_else(|| {
            self.track
                .start_frames
                .saturating_add(self.packet_index as u32)
        }) as u64;
        self.packet_index += 1;
        SacdPacket {
            area_index: self.area.index,
            track_index: self.track.index,
            pts,
            duration: 1,
            frame_format: self.area.frame_format,
            channel_count: self.area.channel_count,
            data: frame.data,
        }
    }
}
