// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::METADATA_INFO;
use super::error::SacdError;
use super::misc::symphonia_track_id;
use super::read::read_area_with_backup;
use super::read::read_master_text;
use super::read::read_master_toc;
use super::sacd_area::SacdArea;
use super::sacd_metadata::SacdMetadata;
use super::types::SacdAreaKind;
use super::types::SacdResult;
use std::io::{Read, Seek};
use std::sync::Arc;
use symphonia_core::meta::{
    MetadataBuilder, MetadataLog, PerTrackMetadataBuilder, StandardTag, Tag,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SacdDisc {
    pub metadata: SacdMetadata,
    pub areas: Vec<SacdArea>,
}

impl SacdDisc {
    pub fn stereo_area(&self) -> Option<&SacdArea> {
        self.areas
            .iter()
            .find(|area| area.kind == SacdAreaKind::Stereo)
    }

    pub fn multichannel_area(&self) -> Option<&SacdArea> {
        self.areas
            .iter()
            .find(|area| area.kind == SacdAreaKind::Multichannel)
    }

    pub fn area(&self, kind: SacdAreaKind) -> Option<&SacdArea> {
        self.areas.iter().find(|area| area.kind == kind)
    }
}

impl SacdDisc {
    pub fn read_from<R: Read + Seek>(reader: &mut R) -> SacdResult<Self> {
        parse_disc(reader)
    }
}

fn parse_disc<R: Read + Seek>(reader: &mut R) -> SacdResult<SacdDisc> {
    let master = read_master_toc(reader)?;
    let metadata = read_master_text(reader).unwrap_or_default();
    let mut areas = Vec::new();

    if master.area_1_toc_1_start > 0
        && let Some(area) = read_area_with_backup(
            reader,
            areas.len(),
            master.area_1_toc_1_start,
            master.area_1_toc_2_start,
            master.area_1_toc_size,
        )?
    {
        areas.push(area);
    }

    if master.area_2_toc_1_start > 0
        && let Some(area) = read_area_with_backup(
            reader,
            areas.len(),
            master.area_2_toc_1_start,
            master.area_2_toc_2_start,
            master.area_2_toc_size,
        )?
    {
        areas.push(area);
    }

    if areas.is_empty() {
        return Err(SacdError::MissingArea);
    }

    Ok(SacdDisc { metadata, areas })
}

pub(super) fn build_metadata_log(disc: &SacdDisc) -> MetadataLog {
    let mut log = MetadataLog::default();
    let mut builder = MetadataBuilder::new(METADATA_INFO);
    if let Some(title) = disc.metadata.display_title() {
        builder.add_tag(Tag::new_from_parts(
            "TITLE",
            title,
            Some(StandardTag::Album(Arc::new(title.to_string()))),
        ));
    }
    if let Some(artist) = disc.metadata.display_artist() {
        builder.add_tag(Tag::new_from_parts(
            "ARTIST",
            artist,
            Some(StandardTag::AlbumArtist(Arc::new(artist.to_string()))),
        ));
    }

    for area in &disc.areas {
        for track in &area.tracks {
            let mut per_track = PerTrackMetadataBuilder::new(u64::from(symphonia_track_id(
                area.index,
                track.index,
            )));
            if let Some(title) = &track.metadata.title {
                per_track.add_tag(Tag::new_from_parts(
                    "TITLE",
                    title.as_str(),
                    Some(StandardTag::TrackTitle(Arc::new(title.clone()))),
                ));
            }
            if let Some(performer) = &track.metadata.performer {
                per_track.add_tag(Tag::new_from_parts(
                    "PERFORMER",
                    performer.as_str(),
                    Some(StandardTag::Artist(Arc::new(performer.clone()))),
                ));
            }
            builder.add_track(per_track.build());
        }
    }

    log.push(builder.build());
    log
}
