// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::SUPPORTED_VERSION_MAJOR;
use super::consts::SUPPORTED_VERSION_MINOR;
use super::error::SacdError;
use super::types::SacdResult;
use symphonia_codec_dst::DstDsdDecoder;
use symphonia_core::errors::{Error as SymphoniaError, SeekErrorKind};

pub(super) fn decode_dst_packet(
    decoder: &mut DstDsdDecoder,
    encoded: &[u8],
    decoded: &mut Vec<u8>,
) -> SacdResult<usize> {
    let required = decoder.dsd_frame_bytes();
    if decoded.len() < required {
        decoded.resize(required, 0);
    }
    decoder
        .decode_frame(encoded, decoded)
        .map_err(|err| SacdError::DstDecode(err.to_string()))
}

pub(super) fn check_version(major: u8, minor: u8) -> SacdResult<()> {
    if major > SUPPORTED_VERSION_MAJOR
        || (major == SUPPORTED_VERSION_MAJOR && minor > SUPPORTED_VERSION_MINOR)
    {
        Err(SacdError::UnsupportedVersion { major, minor })
    } else {
        Ok(())
    }
}

pub(super) fn to_symphonia_error(error: SacdError) -> SymphoniaError {
    match error {
        SacdError::Io(err) => SymphoniaError::IoError(err),
        SacdError::UnsupportedSeek => SymphoniaError::SeekError(SeekErrorKind::OutOfRange),
        SacdError::DstDecode(_) => SymphoniaError::DecodeError("sacd: DST-to-DSD decode failed"),
        _ => SymphoniaError::DecodeError("sacd: invalid or unsupported SACD ISO"),
    }
}
