// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::error::SacdError;
use super::sacd_frame_format::SacdFrameFormat;
use super::types::SacdAreaKind;
use super::types::SacdResult;
use super::types::SacdTrack;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SacdArea {
    pub index: usize,
    pub kind: SacdAreaKind,
    pub frame_format: SacdFrameFormat,
    pub channel_count: u8,
    pub loudspeaker_config: u8,
    pub extra_settings: u8,
    pub track_start_lsn: u32,
    pub track_end_lsn: u32,
    pub total_frames: u32,
    pub tracks: Vec<SacdTrack>,
}

impl SacdArea {
    pub fn track(&self, index: usize) -> SacdResult<&SacdTrack> {
        self.tracks.get(index).ok_or(SacdError::TrackOutOfRange)
    }
}
