// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::complete_frame::make_symphonia_packet;
use super::complete_frame::process_audio_sector;
use super::consts::FORMAT_INFO;
use super::consts::SACD_LSN_SIZE;
use super::consts::SACD_SAMPLING_FREQUENCY;
use super::consts::SAMPLES_PER_FRAME;
use super::consts::sacd_time_base;
use super::frame_accumulator::FrameAccumulator;
use super::misc::symphonia_track_id;
use super::read::read_sector;
use super::sacd_disc::SacdDisc;
use super::sacd_disc::build_metadata_log;
use super::sacd_error::to_symphonia_error;
use super::types::PacketTrack;
use symphonia_core::audio::Channels;
use symphonia_core::codecs::CodecParameters;
use symphonia_core::codecs::audio::AudioCodecParameters;
use symphonia_core::errors::{
    Error as SymphoniaError, Result as SymphoniaResult, SeekErrorKind, seek_error,
};
use symphonia_core::formats::TrackFlags;
use symphonia_core::formats::prelude::*;
use symphonia_core::formats::probe::{ProbeFormatData, ProbeableFormat, Score, Scoreable};
use symphonia_core::io::{MediaSourceStream, ScopedStream};
use symphonia_core::meta::{Metadata, MetadataLog};
use symphonia_core::packet::Packet;
use symphonia_core::support_format;
use symphonia_core::units::Time;

pub struct SacdFormatReader<'s> {
    pub(super) reader: MediaSourceStream<'s>,
    pub(super) disc: SacdDisc,
    pub(super) media_info: MediaInfo,
    pub(super) tracks: Vec<Track>,
    pub(super) packet_tracks: Vec<PacketTrack>,
    pub(super) packet_track_index: usize,
    pub(super) pending: FrameAccumulator,
    pub(super) metadata: MetadataLog,
}

impl<'s> SacdFormatReader<'s> {
    pub fn try_new(
        mut reader: MediaSourceStream<'s>,
        _opts: FormatOptions,
    ) -> SymphoniaResult<Self> {
        let disc = SacdDisc::read_from(&mut reader).map_err(to_symphonia_error)?;
        let mut tracks = Vec::new();
        let mut packet_tracks = Vec::new();

        for area in &disc.areas {
            for track in &area.tracks {
                let sym_id = symphonia_track_id(area.index, track.index);
                let mut codec_params = AudioCodecParameters::new();
                codec_params
                    .for_codec(area.frame_format.codec_id())
                    .with_sample_rate(SACD_SAMPLING_FREQUENCY)
                    .with_bits_per_sample(1)
                    .with_bits_per_coded_sample(1)
                    .with_channels(Channels::Discrete(u16::from(area.channel_count)))
                    .with_max_frames_per_packet(SAMPLES_PER_FRAME)
                    .with_frames_per_block(SAMPLES_PER_FRAME);

                let mut sym_track = Track::new(sym_id);
                sym_track
                    .with_codec_params(CodecParameters::Audio(codec_params))
                    .with_time_base(sacd_time_base())
                    .with_duration(Duration::new(track.duration_frames as u64))
                    .with_num_frames(track.duration_frames as u64)
                    .with_start_ts(Timestamp::new(track.start_frames as i64));
                if tracks.is_empty() {
                    sym_track.with_flags(TrackFlags::DEFAULT);
                }
                tracks.push(sym_track);

                packet_tracks.push(PacketTrack {
                    symphonia_track_id: sym_id,
                    area_index: area.index,
                    track_index: track.index,
                    current_lsn: track.start_lsn,
                    end_lsn: track.start_lsn.saturating_add(track.length_lsn),
                    packet_index: 0,
                });
            }
        }

        let media_info = MediaInfo::from_tracks(&tracks);
        let metadata = build_metadata_log(&disc);

        Ok(Self {
            reader,
            disc,
            media_info,
            tracks,
            packet_tracks,
            packet_track_index: 0,
            pending: FrameAccumulator::default(),
            metadata,
        })
    }
}

impl Scoreable for SacdFormatReader<'_> {
    fn score(_src: ScopedStream<&mut MediaSourceStream<'_>>) -> SymphoniaResult<Score> {
        Ok(Score::Supported(1))
    }
}

impl ProbeableFormat<'_> for SacdFormatReader<'_> {
    fn try_probe_new(
        mss: MediaSourceStream<'_>,
        opts: FormatOptions,
    ) -> SymphoniaResult<Box<dyn FormatReader + '_>> {
        Ok(Box::new(SacdFormatReader::try_new(mss, opts)?))
    }

    fn probe_data() -> &'static [ProbeFormatData] {
        &[support_format!(
            FORMAT_INFO,
            &["iso"],
            &["application/x-sacd-iso"],
            &[b"SACD"]
        )]
    }
}

impl FormatReader for SacdFormatReader<'_> {
    fn format_info(&self) -> &FormatInfo {
        &FORMAT_INFO
    }

    fn media_info(&self) -> &MediaInfo {
        &self.media_info
    }

    fn metadata(&mut self) -> Metadata<'_> {
        self.metadata.metadata()
    }

    fn seek(&mut self, _mode: SeekMode, to: SeekTo) -> SymphoniaResult<SeekedTo> {
        let (track_id, required_ts) = match to {
            SeekTo::Time { time, track_id } => {
                if time != Time::ZERO {
                    return seek_error(SeekErrorKind::OutOfRange);
                }
                (
                    track_id.unwrap_or_else(|| self.tracks.first().map(|t| t.id).unwrap_or(0)),
                    Timestamp::ZERO,
                )
            }
            SeekTo::Timestamp { ts, track_id } => {
                if ts != Timestamp::ZERO {
                    return seek_error(SeekErrorKind::OutOfRange);
                }
                (track_id, ts)
            }
        };

        self.packet_track_index = 0;
        self.pending = FrameAccumulator::default();
        for packet_track in &mut self.packet_tracks {
            let area = self
                .disc
                .areas
                .get(packet_track.area_index)
                .ok_or(SymphoniaError::SeekError(SeekErrorKind::InvalidTrack))?;
            let track = area
                .tracks
                .get(packet_track.track_index)
                .ok_or(SymphoniaError::SeekError(SeekErrorKind::InvalidTrack))?;
            packet_track.current_lsn = track.start_lsn;
            packet_track.packet_index = 0;
        }

        Ok(SeekedTo {
            track_id,
            required_ts,
            actual_ts: Timestamp::ZERO,
        })
    }

    fn tracks(&self) -> &[Track] {
        &self.tracks
    }

    fn next_packet(&mut self) -> SymphoniaResult<Option<Packet>> {
        let mut sector = [0u8; SACD_LSN_SIZE];

        loop {
            let Some(packet_track) = self.packet_tracks.get_mut(self.packet_track_index) else {
                return Ok(None);
            };
            let area = self
                .disc
                .areas
                .get(packet_track.area_index)
                .ok_or(SymphoniaError::DecodeError("sacd: area index is invalid"))?;
            let track = area
                .tracks
                .get(packet_track.track_index)
                .ok_or(SymphoniaError::DecodeError("sacd: track index is invalid"))?;

            if packet_track.current_lsn >= packet_track.end_lsn {
                if let Some(frame) = self.pending.take_if_complete(area) {
                    let packet = make_symphonia_packet(packet_track, track, frame);
                    return Ok(Some(packet));
                }
                self.packet_track_index += 1;
                self.pending = FrameAccumulator::default();
                continue;
            }

            read_sector(&mut self.reader, packet_track.current_lsn, &mut sector)?;
            packet_track.current_lsn += 1;
            let last = packet_track.current_lsn >= packet_track.end_lsn;
            let mut frames = process_audio_sector(&sector, area, track, &mut self.pending, last)
                .map_err(to_symphonia_error)?;
            if let Some(frame) = frames.drain(..).next() {
                let packet = make_symphonia_packet(packet_track, track, frame);
                return Ok(Some(packet));
            }
        }
    }

    fn into_inner<'s>(self: Box<Self>) -> MediaSourceStream<'s>
    where
        Self: 's,
    {
        self.reader
    }
}
