// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SacdMetadata {
    pub album_title: Option<String>,
    pub album_artist: Option<String>,
    pub disc_title: Option<String>,
    pub disc_artist: Option<String>,
}

impl SacdMetadata {
    pub(super) fn display_title(&self) -> Option<&str> {
        self.disc_title.as_deref().or(self.album_title.as_deref())
    }

    pub(super) fn display_artist(&self) -> Option<&str> {
        self.disc_artist.as_deref().or(self.album_artist.as_deref())
    }
}
