// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub use symphonia_codec_dsd::CODEC_ID_DSD;
pub use symphonia_codec_dst::CODEC_ID_DST;
use symphonia_core::codecs::audio::AudioCodecId;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SacdFrameFormat {
    Dst,
    Dsd3In14,
    Dsd3In16,
}

impl SacdFrameFormat {
    pub fn is_dst(self) -> bool {
        matches!(self, Self::Dst)
    }

    pub(super) fn codec_id(self) -> AudioCodecId {
        if self.is_dst() {
            CODEC_ID_DST
        } else {
            CODEC_ID_DSD
        }
    }
}
