// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::FRAME_SIZE_64;
use super::consts::MASTER_TOC_LEN;
use super::consts::SACD_LSN_SIZE;
use super::consts::START_OF_MASTER_TOC;
use super::error::SacdError;
use super::read;
use super::register::register_all;
use super::register::register_decoders;
use super::sacd_disc::SacdDisc;
use super::sacd_frame_format::SacdFrameFormat;
use super::sacd_packet_reader::SacdPacketReader;
use super::types::SacdAreaKind;
use super::write::write_track_as_dsf;
use std::io::{self, Read, Seek, SeekFrom};
pub use symphonia_codec_dsd::CODEC_ID_DSD;
pub use symphonia_codec_dst::CODEC_ID_DST;
use symphonia_core::audio::Channels;
use symphonia_core::codecs::CodecParameters;
use symphonia_core::codecs::registry::CodecRegistry;
use symphonia_core::formats::prelude::*;
use symphonia_core::formats::probe::Probe;
use symphonia_core::io::MediaSourceStream;

use std::io::Cursor;

use symphonia_core::audio::{Audio, GenericAudioBufferRef};
use symphonia_core::codecs::audio::AudioDecoderOptions;
use symphonia_core::formats::probe::Hint;
use symphonia_core::io::{MediaSource, MediaSourceStreamOptions};

#[test]
fn read_track_text_overflow_returns_default() {
    let data = vec![0u8; 16];
    let result = read::read_track_text(&data, usize::MAX - 1, 0).unwrap();
    assert_eq!(result, super::SacdTrackMetadata::default());
}

#[test]
fn rejects_bad_master_magic() {
    let mut image =
        vec![0u8; (START_OF_MASTER_TOC as usize + MASTER_TOC_LEN as usize) * SACD_LSN_SIZE];
    let err = SacdDisc::read_from(&mut Cursor::new(&mut image)).unwrap_err();
    assert!(matches!(err, SacdError::InvalidIso(_)));
}

#[test]
fn parses_stereo_only_disc() {
    let image = fixture(false, false);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    assert_eq!(disc.areas.len(), 1);
    let area = disc.stereo_area().unwrap();
    assert_eq!(area.kind, SacdAreaKind::Stereo);
    assert_eq!(area.channel_count, 2);
    assert_eq!(area.tracks[0].start_lsn, 600);
    assert_eq!(area.tracks[0].length_lsn, 5);
    assert_eq!(area.tracks[0].duration_frames, 2);
}

#[test]
fn parses_dual_area_disc() {
    let image = fixture(true, false);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    assert!(disc.stereo_area().is_some());
    assert!(disc.multichannel_area().is_some());
    assert_eq!(disc.multichannel_area().unwrap().channel_count, 6);
}

#[test]
fn uses_backup_area_toc() {
    let mut image = fixture(false, false);
    let area1 = 520 * SACD_LSN_SIZE;
    image[area1..area1 + 8].copy_from_slice(b"BAD-TOC!");
    let backup = 525 * SACD_LSN_SIZE;
    write_area_toc(&mut image, 525, b"TWOCHTOC", 2, 3, 2, 600, 604, false);
    write_master(&mut image, 520, 525, 3, 0, 0, 0);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    assert_eq!(disc.stereo_area().unwrap().tracks[0].start_lsn, 600);
    assert_eq!(&image[backup..backup + 8], b"TWOCHTOC");
}

#[test]
fn dst_area_reports_preserved_dst_format() {
    let image = fixture(false, true);
    let disc = SacdDisc::read_from(&mut Cursor::new(image)).unwrap();
    let area = disc.stereo_area().unwrap();
    assert_eq!(area.frame_format, SacdFrameFormat::Dst);
    assert_eq!(area.frame_format.codec_id(), CODEC_ID_DST);
}

#[test]
fn packet_reader_extracts_uncompressed_frame() {
    let image = fixture(false, false);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    let mut packets = SacdPacketReader::new(Cursor::new(image), disc, 0, 0).unwrap();
    let packet = packets.next_packet().unwrap().unwrap();
    assert_eq!(packet.channel_count, 2);
    assert_eq!(packet.frame_format, SacdFrameFormat::Dsd3In16);
    assert_eq!(packet.data.len(), 2 * FRAME_SIZE_64);
    assert!(packets.next_packet().unwrap().is_none());
}

#[test]
fn symphonia_probe_reads_first_packet() {
    let image = fixture(false, false);
    let source = TestSource::new(image);
    let mss = MediaSourceStream::new(Box::new(source), MediaSourceStreamOptions::default());
    let mut probe = Probe::new();
    register_all(&mut probe);
    let mut hint = Hint::new();
    hint.with_extension("iso");
    let mut format = probe
        .probe(&hint, mss, Default::default(), Default::default())
        .unwrap();
    assert_eq!(format.tracks().len(), 1);
    let track_id = format.tracks()[0].id;
    let params = match &format.tracks()[0].codec_params {
        Some(CodecParameters::Audio(params)) => params,
        _ => panic!("missing audio params"),
    };
    assert_eq!(params.codec, CODEC_ID_DSD);
    assert_eq!(params.channels, Some(Channels::Discrete(2u16)));
    let packet = format.next_packet().unwrap().unwrap();
    assert_eq!(packet.track_id, track_id);
    assert_eq!(packet.dur, Duration::new(1));
    assert_eq!(packet.data.len(), 2 * FRAME_SIZE_64);
}

#[test]
fn symphonia_decoder_converts_uncompressed_sacd_packet_to_pcm() {
    let image = fixture(false, false);
    let source = TestSource::new(image);
    let mss = MediaSourceStream::new(Box::new(source), MediaSourceStreamOptions::default());
    let mut probe = Probe::new();
    register_all(&mut probe);
    let mut hint = Hint::new();
    hint.with_extension("iso");
    let mut format = probe
        .probe(&hint, mss, Default::default(), Default::default())
        .unwrap();
    let params = match &format.tracks()[0].codec_params {
        Some(CodecParameters::Audio(params)) => params.clone(),
        _ => panic!("missing audio params"),
    };
    let packet = format.next_packet().unwrap().unwrap();

    let mut registry = CodecRegistry::new();
    register_decoders(&mut registry);
    let mut decoder = registry
        .make_audio_decoder(&params, &AudioDecoderOptions::default())
        .unwrap();
    let decoded = decoder.decode_ref(&packet.as_packet_ref()).unwrap();
    let GenericAudioBufferRef::F32(buffer) = decoded else {
        panic!("expected decoded f32 PCM");
    };
    assert_eq!(buffer.spec().rate(), 176_400);
    assert_eq!(buffer.spec().channels().count(), 2);
    assert_eq!(buffer.frames(), 2352);
}

#[test]
fn dsf_writer_reports_dst_decode_errors() {
    let image = fixture(false, true);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    let packets = SacdPacketReader::new(Cursor::new(image), disc, 0, 0).unwrap();
    let mut output = Vec::new();
    let err = write_track_as_dsf(&mut output, packets).unwrap_err();
    assert!(matches!(err, SacdError::DstDecode(_)));
}

#[test]
fn dsf_writer_emits_header_for_uncompressed_track() {
    let image = fixture(false, false);
    let disc = SacdDisc::read_from(&mut Cursor::new(image.clone())).unwrap();
    let packets = SacdPacketReader::new(Cursor::new(image), disc, 0, 0).unwrap();
    let mut output = Vec::new();
    let frames = write_track_as_dsf(&mut output, packets).unwrap();
    assert_eq!(frames, 1);
    assert_eq!(&output[0..4], b"DSD ");
    assert_eq!(&output[28..32], b"fmt ");
    assert_eq!(&output[80..84], b"data");
    assert_eq!(u32::from_le_bytes(output[52..56].try_into().unwrap()), 2);
}

#[derive(Debug)]
struct TestSource {
    inner: Cursor<Vec<u8>>,
}

impl TestSource {
    fn new(data: Vec<u8>) -> Self {
        Self {
            inner: Cursor::new(data),
        }
    }
}

impl Read for TestSource {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        self.inner.read(buf)
    }
}

impl Seek for TestSource {
    fn seek(&mut self, pos: SeekFrom) -> io::Result<u64> {
        self.inner.seek(pos)
    }
}

impl MediaSource for TestSource {
    fn is_seekable(&self) -> bool {
        true
    }

    fn byte_len(&self) -> Option<u64> {
        Some(self.inner.get_ref().len() as u64)
    }
}

fn fixture(include_multichannel: bool, dst: bool) -> Vec<u8> {
    let max_lsn = if include_multichannel { 640 } else { 610 };
    let mut image = vec![0u8; (max_lsn + 1) * SACD_LSN_SIZE];
    write_master(
        &mut image,
        520,
        0,
        3,
        if include_multichannel { 540 } else { 0 },
        0,
        if include_multichannel { 3 } else { 0 },
    );
    write_master_text(&mut image);
    write_area_toc(
        &mut image,
        520,
        b"TWOCHTOC",
        2,
        if dst { 0 } else { 3 },
        2,
        600,
        604,
        dst,
    );
    if dst {
        write_dst_sector(&mut image, 600, 2);
    } else {
        write_dsd_frame_sectors(&mut image, 600, 2);
    }
    if include_multichannel {
        write_area_toc(&mut image, 540, b"MULCHTOC", 6, 3, 6, 610, 614, false);
        write_dsd_frame_sectors(&mut image, 610, 6);
    }
    image
}

fn write_master(
    image: &mut [u8],
    area1_start: u32,
    area1_backup: u32,
    area1_size: u16,
    area2_start: u32,
    area2_backup: u32,
    area2_size: u16,
) {
    let off = START_OF_MASTER_TOC as usize * SACD_LSN_SIZE;
    image[off..off + 8].copy_from_slice(b"SACDMTOC");
    image[off + 8] = 1;
    image[off + 9] = 20;
    put_be_u32(image, off + 64, area1_start);
    put_be_u32(image, off + 68, area1_backup);
    put_be_u32(image, off + 72, area2_start);
    put_be_u32(image, off + 76, area2_backup);
    put_be_u16(image, off + 84, area1_size);
    put_be_u16(image, off + 86, area2_size);
}

fn write_master_text(image: &mut [u8]) {
    let off = (START_OF_MASTER_TOC as usize + 1) * SACD_LSN_SIZE;
    image[off..off + 8].copy_from_slice(b"SACDText");
    put_be_u16(image, off + 16, 64);
    put_be_u16(image, off + 18, 80);
    image[off + 64..off + 74].copy_from_slice(b"Test Album");
    image[off + 80..off + 91].copy_from_slice(b"Test Artist");
}

fn write_area_toc(
    image: &mut [u8],
    lsn: u32,
    id: &[u8; 8],
    channels: u8,
    frame_format: u8,
    duration_frames: u8,
    track_start: u32,
    track_end: u32,
    dst: bool,
) {
    let off = lsn as usize * SACD_LSN_SIZE;
    image[off..off + 8].copy_from_slice(id);
    image[off + 8] = 1;
    image[off + 9] = 20;
    put_be_u16(image, off + 10, 3);
    image[off + 20] = 4;
    image[off + 21] = frame_format;
    image[off + 32] = channels;
    image[off + 33] = if channels == 6 { 4 } else { 0 };
    image[off + 66] = duration_frames;
    image[off + 69] = 1;
    put_be_u32(image, off + 72, track_start);
    put_be_u32(image, off + 76, track_end);

    let trl1 = (lsn as usize + 1) * SACD_LSN_SIZE;
    image[trl1..trl1 + 8].copy_from_slice(b"SACDTRL1");
    put_be_u32(image, trl1 + 8, track_start);
    put_be_u32(image, trl1 + 8 + 255 * 4, track_end - track_start + 1);

    let trl2 = (lsn as usize + 2) * SACD_LSN_SIZE;
    image[trl2..trl2 + 8].copy_from_slice(b"SACDTRL2");
    image[trl2 + 8 + 255 * 4 + 2] = if dst { 1 } else { duration_frames };
}

fn write_dsd_frame_sectors(image: &mut [u8], start_lsn: usize, channels: u8) {
    let total = usize::from(channels) * FRAME_SIZE_64;
    let mut remaining = total;
    let mut written = 0usize;
    let mut sector_idx = 0usize;
    while remaining > 0 {
        let off = (start_lsn + sector_idx) * SACD_LSN_SIZE;
        let len = remaining.min(2000);
        image[off] = (1 << 5) | if sector_idx == 0 { 1 << 2 } else { 0 };
        let packet_info = ((2u16 << 3) << 8) | len as u16;
        image[off + 1] = if sector_idx == 0 {
            0x80 | ((packet_info >> 8) as u8 & 0x7f)
        } else {
            (packet_info >> 8) as u8 & 0x7f
        };
        image[off + 2] = packet_info as u8;
        let data_off = if sector_idx == 0 {
            image[off + 3] = 0;
            image[off + 4] = 0;
            image[off + 5] = 0;
            off + 6
        } else {
            off + 3
        };
        for byte in &mut image[data_off..data_off + len] {
            *byte = (written % 251) as u8;
            written += 1;
        }
        remaining -= len;
        sector_idx += 1;
    }
}

fn write_dst_sector(image: &mut [u8], lsn: usize, channels: u8) {
    let off = lsn * SACD_LSN_SIZE;
    let len = 12usize;
    image[off] = 1 | (1 << 2) | (1 << 5);
    let packet_info = ((2u16 << 3) << 8) | len as u16;
    image[off + 1] = 0x80 | ((packet_info >> 8) as u8 & 0x7f);
    image[off + 2] = packet_info as u8;
    image[off + 3] = 0;
    image[off + 4] = 0;
    image[off + 5] = 0;
    image[off + 6] = (1 << 2) | if channels == 5 { 1 } else { 0 };
    image[off + 7..off + 7 + len].copy_from_slice(b"DST-FRAME-01");
}

fn put_be_u16(data: &mut [u8], offset: usize, value: u16) {
    data[offset..offset + 2].copy_from_slice(&value.to_be_bytes());
}

fn put_be_u32(data: &mut [u8], offset: usize, value: u32) {
    data[offset..offset + 4].copy_from_slice(&value.to_be_bytes());
}
