// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::error::SacdError;
use super::sacd_frame_format::SacdFrameFormat;

pub type SacdResult<T> = Result<T, SacdError>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SacdAreaKind {
    Stereo,
    Multichannel,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SacdTrackMetadata {
    pub title: Option<String>,
    pub performer: Option<String>,
    pub composer: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SacdTrack {
    pub index: usize,
    pub number: u8,
    pub start_lsn: u32,
    pub length_lsn: u32,
    pub start_frames: u32,
    pub duration_frames: u32,
    pub metadata: SacdTrackMetadata,
}

#[derive(Debug, Clone)]
pub struct SacdPacket {
    pub area_index: usize,
    pub track_index: usize,
    pub pts: u64,
    pub duration: u64,
    pub frame_format: SacdFrameFormat,
    pub channel_count: u8,
    pub data: Vec<u8>,
}

#[derive(Debug)]
pub(super) struct CompleteFrame {
    pub(super) data: Vec<u8>,
    pub(super) timecode_frames: Option<u32>,
}

#[derive(Debug, Clone, Copy)]
pub(super) struct PacketInfo {
    pub(super) frame_start: bool,
    pub(super) data_type: u8,
    pub(super) packet_length: usize,
}

#[derive(Debug, Clone, Copy)]
pub(super) struct FrameInfo {
    pub(super) timecode_frames: Option<u32>,
    pub(super) sector_count: u8,
    pub(super) channel_count: u8,
}

#[derive(Debug, Clone, Copy)]
pub(super) struct MasterToc {
    pub(super) area_1_toc_1_start: u32,
    pub(super) area_1_toc_2_start: u32,
    pub(super) area_2_toc_1_start: u32,
    pub(super) area_2_toc_2_start: u32,
    pub(super) area_1_toc_size: u16,
    pub(super) area_2_toc_size: u16,
}

#[derive(Debug, Clone)]
pub(super) struct PacketTrack {
    pub(super) symphonia_track_id: u32,
    pub(super) area_index: usize,
    pub(super) track_index: usize,
    pub(super) current_lsn: u32,
    pub(super) end_lsn: u32,
    pub(super) packet_index: u64,
}
