// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::SACD_SAMPLING_FREQUENCY;
use super::error::SacdError;
use super::misc::dsf_channel_type;
use super::sacd_error::decode_dst_packet;
use super::sacd_packet_reader::SacdPacketReader;
use super::types::SacdResult;
use rayon::prelude::*;
use std::io::{self, Read, Seek, Write};
use symphonia_codec_dst::DstDsdDecoder;

pub fn write_track_as_dsf<W: Write, R: Read + Seek>(
    mut writer: W,
    mut packets: SacdPacketReader<R>,
) -> SacdResult<u64> {
    let channel_count = packets.area.channel_count;
    let mut audio = Vec::new();
    let mut frames = 0u64;

    if packets.area.frame_format.is_dst() {
        let mut encoded_packets = Vec::new();
        while let Some(packet) = packets.next_packet()? {
            encoded_packets.push(packet.data);
        }
        frames = encoded_packets.len() as u64;

        let probe_decoder =
            DstDsdDecoder::new(usize::from(channel_count), SACD_SAMPLING_FREQUENCY as usize)
                .map_err(|err| SacdError::DstDecode(err.to_string()))?;
        let decoded_frame_bytes = probe_decoder.dsd_frame_bytes();
        let decoded_frames: SacdResult<Vec<Vec<u8>>> = encoded_packets
            .par_iter()
            .map_init(
                || {
                    DstDsdDecoder::new(usize::from(channel_count), SACD_SAMPLING_FREQUENCY as usize)
                        .map_err(|err| err.to_string())
                },
                |decoder, encoded| {
                    let decoder = decoder
                        .as_mut()
                        .map_err(|err| SacdError::DstDecode(err.clone()))?;
                    let mut decoded = vec![0u8; decoded_frame_bytes];
                    let written = decode_dst_packet(decoder, encoded, &mut decoded)?;
                    if written % usize::from(channel_count) != 0 {
                        return Err(SacdError::DstDecode(
                            "decoded frame is not channel aligned".to_string(),
                        ));
                    }
                    decoded.truncate(written);
                    Ok(decoded)
                },
            )
            .collect();

        let decoded_frames = decoded_frames?;
        audio.reserve(decoded_frames.iter().map(Vec::len).sum());
        for decoded in decoded_frames {
            audio.extend_from_slice(&decoded);
        }
    } else {
        while let Some(packet) = packets.next_packet()? {
            audio.extend_from_slice(&packet.data);
            frames += 1;
        }
    }

    let sample_count_per_channel = (audio.len() as u64 / u64::from(channel_count)) * 8;
    write_dsf_header(
        &mut writer,
        channel_count,
        sample_count_per_channel,
        audio.len() as u64,
    )?;
    writer.write_all(&audio)?;
    Ok(frames)
}

fn write_dsf_header<W: Write>(
    writer: &mut W,
    channel_count: u8,
    sample_count_per_channel: u64,
    audio_len: u64,
) -> io::Result<()> {
    let total_size = 28 + 52 + 12 + audio_len;
    writer.write_all(b"DSD ")?;
    writer.write_all(&28u64.to_le_bytes())?;
    writer.write_all(&total_size.to_le_bytes())?;
    writer.write_all(&0u64.to_le_bytes())?;

    writer.write_all(b"fmt ")?;
    writer.write_all(&52u64.to_le_bytes())?;
    writer.write_all(&1u32.to_le_bytes())?;
    writer.write_all(&0u32.to_le_bytes())?;
    writer.write_all(&dsf_channel_type(channel_count).to_le_bytes())?;
    writer.write_all(&(channel_count as u32).to_le_bytes())?;
    writer.write_all(&SACD_SAMPLING_FREQUENCY.to_le_bytes())?;
    writer.write_all(&1u32.to_le_bytes())?;
    writer.write_all(&sample_count_per_channel.to_le_bytes())?;
    writer.write_all(&4096u32.to_le_bytes())?;
    writer.write_all(&0u32.to_le_bytes())?;

    writer.write_all(b"data")?;
    writer.write_all(&(audio_len + 12).to_le_bytes())?;
    Ok(())
}
