// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::dsd_reader::DsdReader;
use super::misc::DSD_SILENCE;
use super::misc::RETRIES;
use log::{debug, error, warn};
use std::error::Error;
use std::fs::File;
use std::io::{self, BufReader, ErrorKind, Read, Seek, SeekFrom};
use std::vec;

/// DSD data iterator that yields frames of DSD data. Provided by [DsdReader].
pub struct DsdIter {
    pub(super) std_in: bool,
    pub(super) bytes_remaining: u64,
    pub(super) channels_num: usize,
    pub(super) out_buffers: Vec<Box<[u8]>>, // Gets resized when set_block_size is called, and each buffer is filled with the bytes for one channel or block of the current frame
    pub(super) block_size: u32,
    pub(super) reader: Box<dyn Read + Send>,
    pub(super) frame_size: u32,
    pub(super) interleaved: bool,
    pub(super) lsbit_first: bool,
    pub(super) in_buffer: Vec<u8>,
    pub(super) file: Option<File>,
    pub(super) audio_pos: u64,
    pub(super) retries: usize,
    pub(super) out_interleaved: bool,
    pub(super) out_lsbf: bool,
    pub(super) out_block_size: u32,
    pub(super) in_index: usize,
    pub(super) equal_size_blocks: bool,
    pub(super) block_padding: usize,
    pub(super) in_buffer_remaining: usize,
}

impl DsdIter {
    pub fn new(
        dsd_input: &DsdReader,
        out_interleaved: bool,
        out_lsbf: bool,
        out_block_size: Option<u32>,
    ) -> Result<Self, Box<dyn Error>> {
        if let Some(out_block_size) = out_block_size {
            if out_block_size == 0 || out_block_size > dsd_input.block_size
            {
                return Err("Block size must be greater than 0 and less than or equal to input block size".into());
            }
            if dsd_input.block_size % out_block_size != 0 {
                return Err("Output block size must be a factor of input block size".into());
            }
        }
        let mut ctx = DsdIter {
            std_in: dsd_input.std_in,
            bytes_remaining: if dsd_input.std_in {
                dsd_input.block_size as u64 * dsd_input.channels_num as u64
            } else {
                dsd_input.audio_length
            },
            channels_num: dsd_input.channels_num,
            out_buffers: Vec::new(),
            block_size: dsd_input.block_size,
            reader: Box::new(io::empty()),
            frame_size: 0,
            interleaved: dsd_input.interleaved,
            lsbit_first: dsd_input.lsbit_first,
            in_buffer: vec![
                DSD_SILENCE;
                dsd_input.block_size as usize
                    * dsd_input.channels_num
            ],
            file: if let Some(file) = &dsd_input.file {
                Some(file.try_clone()?)
            } else {
                None
            },
            audio_pos: dsd_input.audio_pos,
            retries: 0,
            out_interleaved,
            out_lsbf,
            out_block_size: if let Some(out_block_size) = out_block_size {
                out_block_size
            } else {
                dsd_input.block_size
            },
            in_index: 0,
            equal_size_blocks: false,
            block_padding: 0,
            in_buffer_remaining: 0,
        };
        ctx.equal_size_blocks = ctx.block_size == ctx.out_block_size;
        ctx.set_block_size(dsd_input.block_size);
        ctx.set_reader()?;
        ctx.in_index = ctx.load_frame()?;
        Ok(ctx)
    }

    /// Read one frame of DSD data into the channel buffers and return the index of the
    /// first valid byte in the input buffer.
    #[inline(always)]
    pub(super) fn load_frame(&mut self) -> Result<usize, Box<dyn Error>> {
        //stdin always reads frame_size
        let partial_frame = if self.bytes_remaining
            < self.frame_size as u64
            && !self.std_in
        {
            true
        } else {
            false
        };

        if self.interleaved {
            if partial_frame {
                // For interleaved (e.g. dff), we resize block/frame/buffer size
                // right away since there is no zero padding to calculate on incomplete blocks.
                self.set_block_size(
                    (self.bytes_remaining / self.channels_num as u64)
                        as u32,
                );
            }
            self.reader.read_exact(&mut self.in_buffer)?;
        } else {
            // Planar (e.g. DSF): Each input channel block is fixed size (block_size)
            // and the last input frame may contain zero-padded tail inside each channel block.
            // We compare the bytes remaining to each full input channel block size
            // to determine how many padding bytes exist, skipping over
            // this zero padding later.

            // 1st read full frame into in_buffer, which may contain zero padding
            // if partial frame. We need to do this before resetting block size
            self.reader.read_exact(&mut self.in_buffer)?;

            if partial_frame {
                let valid_for_chan = (self.bytes_remaining
                    / self.channels_num as u64)
                    as usize;
                self.block_padding =
                    self.block_size as usize - valid_for_chan;
                debug!(
                    "Partial frame detected. Valid bytes for each channel: {}. Padding bytes per channel: {}. Input index: {}.",
                    valid_for_chan, self.block_padding, self.in_index
                );
                // Now we resize the block size and corresponding output buffers, since we've
                // calculated the valid bytes/padding for this frame's blocks.
                // Block size will effectively be the valid bytes for each input channel block.
                // This should be the last frame read.
                self.set_block_size(valid_for_chan as u32);
            }
        }
        // For now we always return 0 as reading should begin at the first byte in the
        // input buffer
        Ok(0)
    }

    /// Delegate to the appropriate block writing function based on whether the input is interleaved or planar,
    /// and return the number of audio bytes read (not including padding when input is planar).
    #[inline(always)]
    pub(super) fn write_blocks(
        &mut self,
    ) -> Result<usize, Box<dyn Error>> {
        if self.in_buffer_remaining == 0 {
            self.in_index = self.load_frame()?;
            self.in_buffer_remaining = self.in_buffer.len();
        }
        let bytes_read = if self.interleaved {
            self.write_blocks_from_interl()
        } else {
            self.write_blocks_from_planar()
        };
        self.in_buffer_remaining = if let Some(new_buff_remaining) =
            self.in_buffer_remaining.checked_sub(bytes_read)
        {
            new_buff_remaining
        } else {
            warn!("Input buffer remaining underflowed; setting to 0.");
            0
        };

        Ok(bytes_read)
    }

    /// Take frame of planar DSD bytes from input and write one channel
    /// or block to the buffer(s) with the endianness we need, returning
    /// the number of audio bytes read (not including padding).
    #[inline(always)]
    pub(super) fn write_blocks_from_planar(&mut self) -> usize {
        let full_block = self.block_size as usize + self.block_padding;

        for chan in 0..self.channels_num {
            if self.out_interleaved {
                // lsbf planar -> interleaved
                // One out-block-size slice from planar input data at a time
                for (i, in_idx) in (self.in_index
                    ..(self.in_index + self.out_block_size as usize))
                    .enumerate()
                {
                    let b = self.in_buffer[in_idx];
                    // One big output buffer for the whole frame. Hardcode zero index.
                    self.out_buffers[0][chan + i * self.channels_num] =
                        if self.lsbit_first == self.out_lsbf {
                            b
                        } else {
                            b.reverse_bits()
                        };
                }
            } else {
                for (i, &b) in self.in_buffer[self.in_index
                    ..(self.in_index + self.out_block_size as usize)]
                    .iter()
                    .enumerate()
                {
                    self.out_buffers[chan][i] =
                        if self.lsbit_first == self.out_lsbf {
                            b
                        } else {
                            b.reverse_bits()
                        };
                }
            }
            self.in_index += full_block;
        }
        // If necessary, wrap input index around to beginning of next block's starting point
        self.in_index = (self.in_index + self.out_block_size as usize)
            % self.in_buffer.len();
        self.out_block_size as usize * self.channels_num
    }

    /// Take frame of interleaved DSD bytes from input and write one
    /// channel or block to the buffer(s) with the endianness we need,
    /// returning the number of audio bytes read
    #[inline(always)]
    pub(super) fn write_blocks_from_interl(&mut self) -> usize {
        let out_frame_size: usize =
            self.out_block_size as usize * self.channels_num;

        if self.out_interleaved {
            // interleaved -> interleaved, single output slice for whole frame
            for (i, &b) in self.in_buffer
                [self.in_index..(self.in_index + out_frame_size)]
                .iter()
                .enumerate()
            {
                self.out_buffers[0][i] =
                    if self.lsbit_first == self.out_lsbf {
                        b
                    } else {
                        b.reverse_bits()
                    };
            }
        } else {
            // interleaved -> planar, output slice per channel
            for (byte_idx, chunk) in self.in_buffer
                [self.in_index..(self.in_index + out_frame_size)]
                .chunks_exact(self.channels_num)
                .enumerate()
            {
                for (chan, &byte) in chunk.iter().enumerate() {
                    self.out_buffers[chan][byte_idx] =
                        if self.lsbit_first == self.out_lsbf {
                            byte
                        } else {
                            byte.reverse_bits()
                        };
                }
            }
        }
        self.in_index += out_frame_size;
        out_frame_size
    }

    /// Set block size and update frame and buffer sizes accordingly.
    pub(super) fn set_block_size(&mut self, block_size: u32) {
        self.block_size = block_size;
        self.frame_size = self.block_size * self.channels_num as u32;

        self.out_block_size = if self.equal_size_blocks {
            block_size
        } else if (self.out_block_size * self.channels_num as u32) as u64
            > self.bytes_remaining
        {
            (self.bytes_remaining / self.channels_num as u64) as u32
        } else {
            self.out_block_size
        };

        let blocks_per_frame = if self.out_interleaved {
            1
        } else {
            self.channels_num
        };

        self.out_buffers = (0..blocks_per_frame)
            .map(|_| {
                if self.out_interleaved {
                    // For interleaved output, we use a single buffer for the whole frame.
                    vec![
                        DSD_SILENCE;
                        (self.out_block_size * self.channels_num as u32)
                            as usize
                    ]
                    .into_boxed_slice()
                } else {
                    // For planar output, we use one buffer per channel block.
                    vec![DSD_SILENCE; self.out_block_size as usize]
                        .into_boxed_slice()
                }
            })
            .collect();
        // Constant input buffer size for planar, interleaved gets resized since
        // there is no padding keeping the frame size constant
        if self.interleaved {
            self.in_buffer = vec![DSD_SILENCE; self.frame_size as usize];
        }
        self.in_buffer_remaining = self.in_buffer.len();

        debug!(
            "Set block_size={}. {} blocks per frame. Out block size={}.",
            self.block_size, blocks_per_frame, self.out_block_size
        );
    }

    pub(super) fn set_reader(&mut self) -> Result<(), Box<dyn Error>> {
        if self.std_in {
            // Use Stdin (not StdinLock) so the reader is 'static + Send for threaded use
            self.reader = Box::new(BufReader::with_capacity(
                self.frame_size as usize * 8,
                io::stdin(),
            ));
            return Ok(());
        }
        // Obtain an owned File by cloning the handle from InputContext, then seek if needed.
        let mut file = self
            .file
            .as_ref()
            .ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::Other,
                    "Missing input file handle",
                )
            })?
            .try_clone()?;

        if self.audio_pos > 0 {
            file.seek(SeekFrom::Start(self.audio_pos as u64))?;
            debug!(
                "Seeked to audio start position: {}",
                file.stream_position()?
            );
        }
        self.reader = Box::new(BufReader::with_capacity(
            self.frame_size as usize * 8,
            file,
        ));
        Ok(())
    }

    /// Returns true if we have reached the end of file for non-stdin inputs
    #[inline(always)]
    pub(super) fn is_eof(&self) -> bool {
        !self.std_in && self.bytes_remaining == 0
    }
}

impl Iterator for DsdIter {
    /// For planar output: Item is (frame_read_size, Vec<channel_data_bytes>),
    /// where each channel_data_bytes is a boxed slice of bytes for a channel.
    /// The Vec of channels is in order [[ch1_byte1, ch1_byte2, ...], [ch2_byte1, ch2_byte2, ...], ...].
    /// For interleaved output: Item is (frame_read_size, Vec<interleaved_channel_data_bytes>),
    /// where the single element in the Vec is a boxed slice of interleaved bytes for all channels in the frame.
    /// The Vec has the ordering: [[ch1_byte1, ch2_byte1, ch1_byte2, ch2_byte2, ...]]
    type Item = (usize, Vec<Box<[u8]>>);

    fn next(&mut self) -> Option<Self::Item> {
        if self.is_eof() {
            return None;
        }
        match self.write_blocks() {
            Ok(read_size) => {
                self.retries = 0;
                if !self.std_in {
                    self.bytes_remaining = if let Some(
                        new_bytes_remaining,
                    ) =
                        self.bytes_remaining.checked_sub(read_size as u64)
                    {
                        new_bytes_remaining
                    } else {
                        warn!(
                            "Bytes remaining underflowed; setting to 0."
                        );
                        0
                    };
                }
                return Some((read_size, self.out_buffers.clone()));
            }
            Err(e) => {
                if let Some(io_err) = e.downcast_ref::<io::Error>() {
                    match io_err.kind() {
                        ErrorKind::Interrupted => {
                            if self.retries < RETRIES {
                                warn!("I/O interrupted, retrying read.");
                                self.retries += 1;
                                return self.next();
                            } else {
                                error!(
                                    "Max retries reached for interrupted I/O."
                                );
                                return None;
                            }
                        }
                        _ => {
                            return None;
                        }
                    }
                }
                error!("Error reading DSD frame: {}", e);
                return None;
            }
        }
    }
}
