// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::convert::TryFrom;

/// DSD rate multiplier
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DsdRate {
    #[default]
    DSD64 = 1,
    DSD128 = 2,
    DSD256 = 4,
    DSD512 = 8,
}

impl TryFrom<u32> for DsdRate {
    type Error = &'static str;
    fn try_from(v: u32) -> Result<Self, Self::Error> {
        match v {
            1 => Ok(DsdRate::DSD64),
            2 => Ok(DsdRate::DSD128),
            4 => Ok(DsdRate::DSD256),
            8 => Ok(DsdRate::DSD512),
            _ => Err("Invalid DSD rate multiplier (expected 1,2,4,8)"),
        }
    }
}
