// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub(super) const RETRIES: usize = 1; // Max retries for progress send

pub(super) const DSD_SILENCE: u8 = 0x69; // The byte value used to fill channel buffers when padding or on partial frames. 0x69 is the standard value for silence in DSD.
