// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::dsd_file::DsdFileFormat;
use std::ffi::OsString;
use std::path::PathBuf;

/// DSD bit endianness
#[derive(Copy, Clone, PartialEq, Debug)]
pub enum Endianness {
    LsbFirst,
    MsbFirst,
}

/// DSD channel format
#[derive(Copy, Clone, PartialEq, Debug)]
pub enum FmtType {
    /// Block per channel
    Planar,
    /// Byte per channel
    Interleaved,
}

pub(super) struct InputPathAttrs {
    pub(super) std_in: bool,
    pub(super) file_format: Option<DsdFileFormat>,
    pub(super) parent_path: Option<PathBuf>,
    pub(super) file_name: OsString,
}
