// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub trait AudioSample: Copy + Send + Sync {
    fn to_i16(self) -> i16;
    fn to_i24(self) -> i32;
    fn to_i32(self) -> i32;
    fn to_f32(self) -> f32;
    fn is_float() -> bool;
}

impl AudioSample for f32 {
    fn to_i16(self) -> i16 {
        (self.clamp(-1.0, 1.0) * 32767.0) as i16
    }
    fn to_i24(self) -> i32 {
        (self.clamp(-1.0, 1.0) * 8388607.0) as i32
    }
    fn to_i32(self) -> i32 {
        (self.clamp(-1.0, 1.0) * 2147483647.0) as i32
    }
    fn to_f32(self) -> f32 {
        self
    }
    fn is_float() -> bool {
        true
    }
}

impl AudioSample for i32 {
    // For 16-bit output, pipeline already scales to ±32767; clamp and pass through.
    fn to_i16(self) -> i16 {
        let v = self.max(-32768).min(32767);
        v as i16
    }
    fn to_i24(self) -> i32 {
        self
    }
    fn to_i32(self) -> i32 {
        self
    }
    fn to_f32(self) -> f32 {
        self as f32 / 2147483647.0
    }
    fn is_float() -> bool {
        false
    }
}
