// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::consts::FINAL_BLOCK;
use super::super::consts::FLOAT_DATA;
use super::super::consts::ID_CHANNEL_INFO;
use super::super::consts::ID_ODD_SIZE;
use super::super::consts::INITIAL_BLOCK;
use super::super::consts::SRATE_LSB;
use super::super::consts::WAVPACK_HEADER_LEN;
use super::super::consts::WAVPACK_MARKER;
use super::super::consts::WAVPACK_MAX_STREAM_VERSION;
use super::super::consts::WAVPACK_MIN_CK_SIZE;
use super::super::wav_pack_reader::WavPackReader;
use std::io::Cursor;
use symphonia_core::audio::sample::SampleFormat;
use symphonia_core::codecs::CodecParameters;
use symphonia_core::formats::prelude::*;
use symphonia_core::io::MediaSourceStream;
use symphonia_core::units::Timestamp;

pub(super) fn make_test_block(
    flags: u32,
    total_samples: Option<u32>,
    block_samples: u32,
    body: &[u8],
) -> Vec<u8> {
    let ck_size = WAVPACK_MIN_CK_SIZE + body.len() as u32;
    let mut data = Vec::with_capacity(WAVPACK_HEADER_LEN + body.len());

    data.extend_from_slice(&WAVPACK_MARKER);
    data.extend_from_slice(&ck_size.to_le_bytes());
    data.extend_from_slice(&WAVPACK_MAX_STREAM_VERSION.to_le_bytes());
    data.push(0);
    data.push(0);
    data.extend_from_slice(&total_samples.unwrap_or(u32::MAX).to_le_bytes());
    data.extend_from_slice(&0u32.to_le_bytes());
    data.extend_from_slice(&block_samples.to_le_bytes());
    data.extend_from_slice(&flags.to_le_bytes());
    data.extend_from_slice(&0u32.to_le_bytes());
    data.extend_from_slice(body);
    data
}

pub(super) fn make_test_block_with_crc(
    flags: u32,
    total_samples: Option<u32>,
    block_samples: u32,
    crc: u32,
    body: &[u8],
) -> Vec<u8> {
    let mut data = make_test_block(flags, total_samples, block_samples, body);
    data[28..32].copy_from_slice(&crc.to_le_bytes());
    data
}

fn make_test_block_at_index(
    flags: u32,
    total_samples: Option<u32>,
    block_index: u32,
    block_samples: u32,
    body: &[u8],
) -> Vec<u8> {
    let mut data = make_test_block(flags, total_samples, block_samples, body);
    data[16..20].copy_from_slice(&block_index.to_le_bytes());
    data
}

#[test]
fn wavpack_reader_stops_at_total_samples_before_trailing_tag() {
    let flags = 1 | INITIAL_BLOCK | FINAL_BLOCK | (9 << SRATE_LSB);
    let mut data = make_test_block(flags, Some(1), 1, &[]);
    data.extend_from_slice(b"APETAGEX");

    let cursor = Cursor::new(data);
    let mss = MediaSourceStream::new(Box::new(cursor), Default::default());
    let mut reader = WavPackReader::try_new(mss, Default::default()).unwrap();

    assert!(reader.next_packet().unwrap().is_some());
    assert!(reader.next_packet().unwrap().is_none());
}

#[test]
fn wavpack_reader_treats_trailing_metadata_marker_as_eos() {
    let flags = 1 | INITIAL_BLOCK | FINAL_BLOCK | (9 << SRATE_LSB);
    let mut data = make_test_block(flags, None, 1, &[]);
    data.extend_from_slice(b"APETAGEX");

    let cursor = Cursor::new(data);
    let mss = MediaSourceStream::new(Box::new(cursor), Default::default());
    let mut reader = WavPackReader::try_new(mss, Default::default()).unwrap();

    assert!(reader.next_packet().unwrap().is_some());
    assert!(reader.next_packet().unwrap().is_none());
}

#[test]
fn wavpack_reader_exposes_ten_channel_stream_info() {
    let flags = FLOAT_DATA | 3 | INITIAL_BLOCK | FINAL_BLOCK | (10 << SRATE_LSB);
    let data = make_test_block(
        flags,
        Some(1),
        1,
        &[ID_CHANNEL_INFO | ID_ODD_SIZE, 3, 10, 0xff, 0x03, 0, 0, 0],
    );

    let cursor = Cursor::new(data);
    let mss = MediaSourceStream::new(Box::new(cursor), Default::default());
    let reader = WavPackReader::try_new(mss, Default::default()).unwrap();
    let track = reader.tracks().first().unwrap();
    let CodecParameters::Audio(params) = track.codec_params.as_ref().unwrap() else {
        panic!("expected audio codec params");
    };

    assert!(matches!(params.sample_format, Some(SampleFormat::F32)));
    assert_eq!(params.sample_rate, Some(48000));
    assert_eq!(params.channels.as_ref().unwrap().count(), 10);
}

#[test]
fn wavpack_reader_seeks_to_packet_boundary() {
    let flags = 1 | INITIAL_BLOCK | FINAL_BLOCK | (9 << SRATE_LSB);
    let mut data = make_test_block_at_index(flags, Some(11), 0, 1, &[]);
    data.extend_from_slice(&make_test_block_at_index(flags, Some(11), 10, 1, &[]));

    let cursor = Cursor::new(data);
    let mss = MediaSourceStream::new(Box::new(cursor), Default::default());
    let mut reader = WavPackReader::try_new(mss, Default::default()).unwrap();

    let seeked = reader
        .seek(
            SeekMode::Accurate,
            SeekTo::Timestamp {
                ts: Timestamp::new(10),
                track_id: 0,
            },
        )
        .unwrap();

    assert_eq!(seeked.actual_ts, Timestamp::new(10));
    let packet = reader.next_packet().unwrap().unwrap();
    assert_eq!(packet.pts, Timestamp::new(10));
}
