// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::consts::HYBRID_FLAG;
use super::super::consts::INT32_DATA;
use super::super::consts::MONO_FLAG;
use super::super::consts::fixup_samples;
use super::super::types::DecodedWord;
use super::super::types::EntropyVars;
use super::super::types::HybridProfile;
use super::super::types::Int32Info;
use super::super::types::WavPackBlock;
use super::super::wav_pack_bit_reader::WavPackBitReader;
use super::super::wav_pack_block_header::WavPackBlockHeader;
use super::super::words_decoder::WordsDecoder;

fn pack_bits(bits: &[u32]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut byte = 0u8;

    for (i, &bit) in bits.iter().enumerate() {
        if bit != 0 {
            byte |= 1 << (i & 7);
        }

        if i & 7 == 7 {
            out.push(byte);
            byte = 0;
        }
    }

    if bits.len() & 7 != 0 {
        out.push(byte);
    }

    out
}

pub(super) fn parse_test_block(data: &[u8]) -> WavPackBlock {
    let header = WavPackBlockHeader::parse(data).unwrap();
    WavPackBlock {
        header,
        data: Vec::from(data).into_boxed_slice(),
    }
}

#[test]
fn wavpack_bitreader_reads_lsb_first_codes() {
    let data = pack_bits(&[
        1, // maxcode=1.
        0, 1, 0, // maxcode=5, code=2.
        1, 1, 1, // maxcode=5, code=5.
    ]);
    let mut bits = WavPackBitReader::new(&data);

    assert_eq!(bits.read_code(0).unwrap(), 0);
    assert_eq!(bits.read_code(1).unwrap(), 1);
    assert_eq!(bits.read_code(5).unwrap(), 2);
    assert_eq!(bits.read_code(5).unwrap(), 5);
}

#[test]
fn wavpack_words_decoder_reads_zero_run() {
    let data = pack_bits(&[
        1, 1, 0, // zero-run unary length code: cbits=2.
        0, // zero-run payload -> two zeros.
    ]);
    let mut bits = WavPackBitReader::new(&data);
    let entropy = EntropyVars {
        median: [[0; 3]; 2],
    };
    let mut words = WordsDecoder::new(entropy, None, MONO_FLAG);

    assert_eq!(
        words.read_words(&mut bits, None, 2).unwrap(),
        vec![
            DecodedWord {
                value: 0,
                correction: 0
            },
            DecodedWord {
                value: 0,
                correction: 0
            },
        ]
    );
}

#[test]
fn wavpack_words_decoder_uses_only_channel_zero_for_mono() {
    let data = pack_bits(&[
        0, // ones_count = 0.
        1, 0, // magnitude 1 with channel 0 median.
        0, // positive sign.
        0, // ones_count = 0.
        1, 0, // magnitude 1 with channel 0 median again.
        0, // positive sign.
    ]);
    let mut bits = WavPackBitReader::new(&data);
    let entropy = EntropyVars {
        median: [[32, 0, 0], [0, 0, 0]],
    };
    let mut words = WordsDecoder::new(entropy, None, MONO_FLAG);

    assert_eq!(
        words.read_words(&mut bits, None, 2).unwrap(),
        vec![
            DecodedWord {
                value: 1,
                correction: 0
            },
            DecodedWord {
                value: -1,
                correction: 0
            },
        ]
    );
}

#[test]
fn wavpack_fixup_restores_wvx_low_bits() {
    let mut samples = vec![2];
    let int32 = Int32Info {
        sent_bits: 2,
        ..Default::default()
    };
    let wvx = pack_bits(&[1, 1]);

    fixup_samples(
        &mut samples,
        INT32_DATA,
        None,
        Some(int32),
        Some(&wvx),
        false,
        false,
    )
    .unwrap();

    assert_eq!(samples, vec![11]);
}

#[test]
fn wavpack_words_decoder_reads_hybrid_correction() {
    let entropy = EntropyVars {
        median: [[16, 0, 0], [16, 0, 0]],
    };
    let hybrid = HybridProfile {
        bitrate_acc: [0x0200 << 16, 0],
        ..Default::default()
    };
    let mut words = WordsDecoder::new(entropy, Some(hybrid), MONO_FLAG | HYBRID_FLAG);
    let main_data = pack_bits(&[
        0, // ones_count = 0.
        0, // positive sign.
    ]);
    let correction_data = pack_bits(&[
        0, // exact value below mid by one.
    ]);
    let mut main_bits = WavPackBitReader::new(&main_data);
    let mut correction_bits = WavPackBitReader::new(&correction_data);

    assert_eq!(
        words
            .read_words(&mut main_bits, Some(&mut correction_bits), 1)
            .unwrap(),
        vec![DecodedWord {
            value: 1,
            correction: -1
        }]
    );
}
