// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

#[path = "extract_sacd/args.rs"]
mod args;
#[path = "extract_sacd/misc.rs"]
mod misc;
#[path = "extract_sacd/output_format.rs"]
mod output_format;
#[cfg(test)]
#[path = "extract_sacd/tests.rs"]
mod tests;
#[path = "extract_sacd/types.rs"]
mod types;
#[path = "extract_sacd/wav_encoding.rs"]
mod wav_encoding;
#[path = "extract_sacd/wav_writer.rs"]
mod wav_writer;
#[path = "extract_sacd/write.rs"]
mod write;

use args::run;

fn main() {
    if let Err(err) = run() {
        eprintln!("error: {err}");
        std::process::exit(1);
    }
}
