// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use flac_codec::metadata::{Picture, VorbisComment};
use log::debug;
/** @file AudioFile.h
 *  @author Adam Stark
 *  @copyright Copyright (C) 2017  Adam Stark
 *
 *  Modified for Rust by clone206, 2025
 *
 * This file is part of the 'AudioFile' library
 *
 * MIT License
 *
 * Copyright (c) 2017 Adam Stark
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
//=======================================================================
use std::fs::File;
use std::io::{self, BufWriter, Write}; // add BufWriter
use std::path::Path;

mod audio_sample;
mod types;

pub use audio_sample::*;
pub use types::*;

#[derive(Clone)]
pub struct AudioFile<T> {
    samples: Vec<Vec<T>>,
    sample_rate: u32,
    bit_depth: usize,
    num_channels: usize,
}

impl<T> AudioFile<T>
where
    T: AudioSample,
{
    pub fn samples_mut(&mut self) -> &mut Vec<Vec<T>> {
        &mut self.samples
    }

    pub fn new(channels: usize, depth: usize, rate: u32) -> Self {
        Self {
            samples: vec![Vec::new(); channels],
            sample_rate: rate,
            bit_depth: depth,
            num_channels: channels,
        }
    }

    pub fn get_num_samples_per_channel(&self) -> usize {
        self.samples.first().map_or(0, |channel| channel.len())
    }

    pub fn save<P: AsRef<Path>>(
        &self,
        path: P,
        format: AudioFileFormat,
        vorbis: Option<VorbisComment>,
        pictures: Vec<Picture>,
    ) -> io::Result<()> {
        match format {
            AudioFileFormat::Wave => self.save_wave_file(path),
            AudioFileFormat::Aiff => self.save_aiff_file(path),
            AudioFileFormat::Aifc => self.save_aifc_file(path),
            AudioFileFormat::Flac => {
                self.save_flac_file(path, vorbis, pictures)
            }
        }
    }

    fn save_wave_file<P: AsRef<Path>>(&self, path: P) -> io::Result<()> {
        let file = File::create(path)?;
        // Use a large buffered writer (1 MiB); adjust if desired
        let mut w = BufWriter::with_capacity(1 << 20, file);

        let channels = self.num_channels;
        let bytes_per_sample = if self.bit_depth == 20 {
            3
        } else {
            self.bit_depth / 8
        };
        let block_align = channels * bytes_per_sample;
        let frames = self.get_num_samples_per_channel();
        let data_size =
            (frames * self.num_channels * bytes_per_sample) as u32;
        let file_size = data_size + 36;

        // RIFF header
        w.write_all(b"RIFF")?;
        w.write_all(&file_size.to_le_bytes())?;
        w.write_all(b"WAVE")?;

        // fmt chunk
        w.write_all(b"fmt ")?;
        w.write_all(&16u32.to_le_bytes())?;
        let format_tag = if T::is_float() { 3u16 } else { 1u16 };
        w.write_all(&format_tag.to_le_bytes())?;
        w.write_all(&(channels as u16).to_le_bytes())?;
        w.write_all(&self.sample_rate.to_le_bytes())?;
        let byte_rate = self.sample_rate as u32 * block_align as u32;
        w.write_all(&byte_rate.to_le_bytes())?;
        w.write_all(&(block_align as u16).to_le_bytes())?;
        w.write_all(&(self.bit_depth as u16).to_le_bytes())?;

        // data chunk
        w.write_all(b"data")?;
        w.write_all(&(data_size as u32).to_le_bytes())?;

        // Stream samples in blocks to reduce temporary allocation
        // Choose a frame block size that stays cache friendly
        const FRAME_BLOCK: usize = 16_384;
        let mut buf: Vec<u8> =
            Vec::with_capacity(FRAME_BLOCK * block_align);

        match self.bit_depth {
            16 => {
                for base in (0..frames).step_by(FRAME_BLOCK) {
                    buf.clear();
                    let end = (base + FRAME_BLOCK).min(frames);
                    for i in base..end {
                        for ch in 0..self.num_channels {
                            let s =
                                self.samples[ch][i].to_i16().to_le_bytes();
                            buf.extend_from_slice(&s);
                        }
                    }
                    w.write_all(&buf)?;
                }
            }
            24 | 20 => {
                for base in (0..frames).step_by(FRAME_BLOCK) {
                    buf.clear();
                    let end = (base + FRAME_BLOCK).min(frames);
                    for i in base..end {
                        for ch in 0..self.num_channels {
                            let mut v = self.samples[ch][i].to_i24();
                            if self.bit_depth == 20 {
                                v <<= 4;
                            }
                            buf.extend_from_slice(&[
                                (v & 0xFF) as u8,
                                ((v >> 8) & 0xFF) as u8,
                                ((v >> 16) & 0xFF) as u8,
                            ]);
                        }
                    }
                    w.write_all(&buf)?;
                }
            }
            32 if T::is_float() => {
                for base in (0..frames).step_by(FRAME_BLOCK) {
                    buf.clear();
                    let end = (base + FRAME_BLOCK).min(frames);
                    for i in base..end {
                        for ch in 0..self.num_channels {
                            let b =
                                self.samples[ch][i].to_f32().to_le_bytes();
                            buf.extend_from_slice(&b);
                        }
                    }
                    w.write_all(&buf)?;
                }
            }
            _ => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "Unsupported bit depth",
                ));
            }
        }

        w.flush()?;
        Ok(())
    }

    fn save_aiff_file<P: AsRef<Path>>(&self, path: P) -> io::Result<()> {
        let file = File::create(path)?;
        let mut w = BufWriter::with_capacity(1 << 20, file);

        let channels = self.num_channels;
        let bytes_per_sample = if self.bit_depth == 20 {
            3
        } else {
            self.bit_depth / 8
        };
        let block_align = channels * bytes_per_sample;
        let frames = self.get_num_samples_per_channel();
        let data_size =
            (frames * self.num_channels * bytes_per_sample) as u32;

        // FORM chunk
        w.write_all(b"FORM")?;
        w.write_all(&(data_size + 46).to_be_bytes())?;
        w.write_all(b"AIFF")?;

        // COMM chunk
        w.write_all(b"COMM")?;
        w.write_all(&18u32.to_be_bytes())?;
        w.write_all(&(channels as u16).to_be_bytes())?;
        w.write_all(&(frames as u32).to_be_bytes())?;
        w.write_all(&(self.bit_depth as u16).to_be_bytes())?;

        let sample_rate = self.sample_rate as f64;
        let mut extended = [0u8; 10];
        self.encode_extended(sample_rate, &mut extended);
        w.write_all(&extended)?;

        // SSND chunk
        w.write_all(b"SSND")?;
        w.write_all(&data_size.to_be_bytes())?;
        w.write_all(&0u32.to_be_bytes())?; // offset
        w.write_all(&0u32.to_be_bytes())?; // block size

        const FRAME_BLOCK: usize = 16_384;
        let mut buf: Vec<u8> =
            Vec::with_capacity(FRAME_BLOCK * block_align);

        match self.bit_depth {
            16 => {
                for base in (0..frames).step_by(FRAME_BLOCK) {
                    buf.clear();
                    let end = (base + FRAME_BLOCK).min(frames);
                    for i in base..end {
                        for ch in 0..self.num_channels {
                            let b =
                                self.samples[ch][i].to_i16().to_be_bytes();
                            buf.extend_from_slice(&b);
                        }
                    }
                    w.write_all(&buf)?;
                }
            }
            24 | 20 => {
                for base in (0..frames).step_by(FRAME_BLOCK) {
                    buf.clear();
                    let end = (base + FRAME_BLOCK).min(frames);
                    for i in base..end {
                        for ch in 0..self.num_channels {
                            let mut v = self.samples[ch][i].to_i24();
                            if self.bit_depth == 20 {
                                v <<= 4;
                            }
                            buf.extend_from_slice(&[
                                ((v >> 16) & 0xFF) as u8,
                                ((v >> 8) & 0xFF) as u8,
                                (v & 0xFF) as u8,
                            ]);
                        }
                    }
                    w.write_all(&buf)?;
                }
            }
            _ => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "Unsupported bit depth",
                ));
            }
        }

        w.flush()?;
        Ok(())
    }

    fn save_aifc_file<P: AsRef<Path>>(&self, path: P) -> io::Result<()> {
        let file = File::create(path)?;
        let mut w = BufWriter::with_capacity(1 << 20, file);

        let channels = self.num_channels;
        let is_float = T::is_float();
        let bytes_per_sample = if self.bit_depth == 20 {
            3
        } else {
            self.bit_depth / 8
        };
        let block_align = channels * bytes_per_sample;
        let frames = self.get_num_samples_per_channel();
        let data_size =
            (frames * self.num_channels * bytes_per_sample) as u32;

        // COMM compression type and Pascal string name.
        // All integer formats use big-endian byte order
        let (comp_type, comp_name_bytes): ([u8; 4], Vec<u8>) = if is_float
        {
            let s =
                b"Linear PCM, 32 bit big-endian floating point" as &[u8];
            let mut v = vec![s.len() as u8];
            v.extend_from_slice(s);
            (*b"fl32", v)
        } else if self.bit_depth == 16 {
            let s =
                b"Linear PCM, 16 bit big-endian signed integer" as &[u8];
            let mut v = vec![s.len() as u8];
            v.extend_from_slice(s);
            (*b"twos", v)
        } else {
            // 24-bit (and 20-bit packed into 24)
            let s =
                b"Linear PCM, 24 bit big-endian signed integer" as &[u8];
            let mut v = vec![s.len() as u8];
            v.extend_from_slice(s);
            // TODO: Apple afconvert and other software use "in24", but sox
            // does not understand; using "NONE" for sox compatibility
            (*b"NONE", v)
        };
        // channels(2) + frames(4) + bitDepth(2) + rate(10) + comp_type(4) + comp_name
        let comm_size: u32 = 22 + comp_name_bytes.len() as u32;
        let comm_size_padded = (comm_size + 1) & !1;

        // FLLR: pad so SSND audio data starts on a 4096-byte boundary.
        // before_fllr = FORM(8) + AIFC(4) + FVER(12) + COMM(8+comm_size_padded)
        //             = 32 + comm_size_padded
        let fllr_data_size: u32 = {
            const PAGE: u32 = 4096;
            let before_fllr = 32 + comm_size_padded;
            // +24: FLLR header(8) + SSND header(8) + SSND offset+block(8)
            let r = (before_fllr + 24) % PAGE;
            if r == 0 { 0 } else { PAGE - r }
        };
        let fllr_chunk_size: u32 = if fllr_data_size > 0 {
            8 + fllr_data_size
        } else {
            0
        };

        // FORM body = AIFC(4) + FVER(12) + COMM(8+comm_size_padded)
        //           + FLLR + SSND(8 + data_size+8)
        let form_size =
            40 + comm_size_padded + fllr_chunk_size + data_size;

        w.write_all(b"FORM")?;
        w.write_all(&form_size.to_be_bytes())?;
        w.write_all(b"AIFC")?;

        // FVER (mandatory for AIFC, version timestamp 0xA2805140)
        w.write_all(b"FVER")?;
        w.write_all(&4u32.to_be_bytes())?;
        w.write_all(&0xA2805140u32.to_be_bytes())?;

        // COMM
        w.write_all(b"COMM")?;
        w.write_all(&comm_size_padded.to_be_bytes())?;
        w.write_all(&(channels as u16).to_be_bytes())?;
        w.write_all(&(frames as u32).to_be_bytes())?;
        w.write_all(&(self.bit_depth as u16).to_be_bytes())?;
        let mut extended = [0u8; 10];
        self.encode_extended(self.sample_rate as f64, &mut extended);
        w.write_all(&extended)?;
        w.write_all(&comp_type)?;
        w.write_all(&comp_name_bytes)?;
        if comm_size % 2 != 0 {
            w.write_all(&[0u8])?;
        }

        // FLLR
        if fllr_data_size > 0 {
            w.write_all(b"FLLR")?;
            w.write_all(&fllr_data_size.to_be_bytes())?;
            w.write_all(&vec![0u8; fllr_data_size as usize])?;
        }

        // SSND
        w.write_all(b"SSND")?;
        w.write_all(&(data_size + 8).to_be_bytes())?;
        w.write_all(&0u32.to_be_bytes())?; // offset
        w.write_all(&0u32.to_be_bytes())?; // block size

        const FRAME_BLOCK: usize = 16_384;
        let mut buf: Vec<u8> =
            Vec::with_capacity(FRAME_BLOCK * block_align);

        if is_float {
            for base in (0..frames).step_by(FRAME_BLOCK) {
                buf.clear();
                let end = (base + FRAME_BLOCK).min(frames);
                for i in base..end {
                    for ch in 0..self.num_channels {
                        buf.extend_from_slice(
                            &self.samples[ch][i].to_f32().to_be_bytes(),
                        );
                    }
                }
                w.write_all(&buf)?;
            }
        } else {
            match self.bit_depth {
                16 => {
                    for base in (0..frames).step_by(FRAME_BLOCK) {
                        buf.clear();
                        let end = (base + FRAME_BLOCK).min(frames);
                        for i in base..end {
                            for ch in 0..self.num_channels {
                                buf.extend_from_slice(
                                    &self.samples[ch][i]
                                        .to_i16()
                                        .to_be_bytes(),
                                );
                            }
                        }
                        w.write_all(&buf)?;
                    }
                }
                24 | 20 => {
                    for base in (0..frames).step_by(FRAME_BLOCK) {
                        buf.clear();
                        let end = (base + FRAME_BLOCK).min(frames);
                        for i in base..end {
                            for ch in 0..self.num_channels {
                                let mut v = self.samples[ch][i].to_i24();
                                if self.bit_depth == 20 {
                                    v <<= 4;
                                }
                                buf.extend_from_slice(&[
                                    ((v >> 16) & 0xFF) as u8,
                                    ((v >> 8) & 0xFF) as u8,
                                    (v & 0xFF) as u8,
                                ]);
                            }
                        }
                        w.write_all(&buf)?;
                    }
                }
                _ => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "Unsupported bit depth",
                    ));
                }
            }
        }

        w.flush()?;
        Ok(())
    }

    fn save_flac_file<P: AsRef<Path>>(
        &self,
        path: P,
        vorbis: Option<VorbisComment>,
        pictures: Vec<Picture>,
    ) -> io::Result<()> {
        use flac_codec::byteorder::LittleEndian;
        use flac_codec::encode::{FlacByteWriter, Options};

        if self.num_channels == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "No channels",
            ));
        }
        let frames = self.get_num_samples_per_channel();
        if frames == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "No samples",
            ));
        }

        // Support 16 or 24 bit (truncate >24).
        let mut bits_per_sample = self.bit_depth;
        if bits_per_sample > 24 {
            bits_per_sample = 24;
        }
        if bits_per_sample != 16
            && bits_per_sample != 20
            && bits_per_sample != 24
        {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "FLAC: only 16, 20, or 24-bit supported",
            ));
        }

        let channels = self.num_channels;
        let bps = bits_per_sample as u32;
        let bytes_per_sample = if bits_per_sample == 20 {
            3
        } else {
            bits_per_sample / 8
        };
        let total_pcm_bytes =
            frames as u64 * channels as u64 * bytes_per_sample as u64;

        let mut opts = Options::default();

        if let Some(some_vorbis) = vorbis {
            opts = opts.comment(some_vorbis);
        }
        for pic in pictures {
            opts = opts.picture(pic);
        }

        // Create FLAC writer (LittleEndian because we feed little-endian sample bytes)
        let mut flac: FlacByteWriter<_, LittleEndian> =
            FlacByteWriter::create(
                path.as_ref(),
                opts,
                self.sample_rate,
                bps,
                channels.try_into().unwrap(),
                Some(total_pcm_bytes),
            )
            .map_err(|e| {
                io::Error::new(
                    io::ErrorKind::Other,
                    format!("FLAC create: {e}"),
                )
            })?;

        const FRAME_BLOCK: usize = 16_384;
        let mut buf: Vec<u8> =
            Vec::with_capacity(FRAME_BLOCK * channels * bytes_per_sample);

        if bits_per_sample == 16 {
            for base in (0..frames).step_by(FRAME_BLOCK) {
                buf.clear();
                let end = (base + FRAME_BLOCK).min(frames);
                for i in base..end {
                    for ch in 0..self.num_channels {
                        buf.extend_from_slice(
                            &self.samples[ch][i].to_i16().to_le_bytes(),
                        );
                    }
                }
                flac.write_all(&buf)?;
            }
        } else {
            // 24-bit
            for base in (0..frames).step_by(FRAME_BLOCK) {
                buf.clear();
                let end = (base + FRAME_BLOCK).min(frames);
                for i in base..end {
                    for ch in 0..self.num_channels {
                        let v = self.samples[ch][i].to_i24();
                        // little-endian 24-bit (LSB first)
                        buf.extend_from_slice(&[
                            (v & 0xFF) as u8,
                            ((v >> 8) & 0xFF) as u8,
                            ((v >> 16) & 0xFF) as u8,
                        ]);
                    }
                }
                flac.write_all(&buf)?;
            }
        }

        flac.finalize().map_err(|e| {
            io::Error::new(
                io::ErrorKind::Other,
                format!("FLAC finalize: {e}"),
            )
        })?;
        Ok(())
    }

    // Helper for AIFF extended float conversion
    fn encode_extended(&self, mut value: f64, buffer: &mut [u8; 10]) {
        // Encode AIFF 80-bit extended with the integer bit included in the mantissa.
        // Layout: 1 sign bit, 15-bit exponent (bias 16383), 1-bit integer + 63-bit fraction.
        for b in buffer.iter_mut() {
            *b = 0;
        }
        if value <= 0.0 {
            return;
        }

        // Normalize into [1.0, 2.0)
        let mut exp: i32 = 0;
        while value >= 2.0 {
            value *= 0.5;
            exp += 1;
        }
        while value < 1.0 {
            value *= 2.0;
            exp -= 1;
        }

        // Biased exponent
        let mut exp_field: u16 = (exp + 16383) as u16;

        // Mantissa includes the leading 1-bit (integer bit) in the top of the 64-bit field.
        // Compute with u128 to detect rounding overflow to 2^64, then downcast to u64.
        let mut mant128: u128 =
            (value * ((1u128 << 63) as f64)).round() as u128;
        if mant128 == (1u128 << 64) {
            // value rounded to 2.0; renormalize
            mant128 = 1u128 << 63;
            exp_field = exp_field.wrapping_add(1);
        }
        let mant: u64 = mant128 as u64;
        // Store big-endian
        buffer[0] = (exp_field >> 8) as u8;
        buffer[1] = (exp_field & 0xFF) as u8;
        buffer[2] = ((mant >> 56) & 0xFF) as u8;
        buffer[3] = ((mant >> 48) & 0xFF) as u8;
        buffer[4] = ((mant >> 40) & 0xFF) as u8;
        buffer[5] = ((mant >> 32) & 0xFF) as u8;
        buffer[6] = ((mant >> 24) & 0xFF) as u8;
        buffer[7] = ((mant >> 16) & 0xFF) as u8;
        buffer[8] = ((mant >> 8) & 0xFF) as u8;
        buffer[9] = (mant & 0xFF) as u8;
    }

    pub fn print_summary(&self) {
        debug!("Audio File Summary:");
        debug!("Bit Depth: {}", self.bit_depth);
        debug!("Sample Rate: {}", self.sample_rate);
        debug!("Num Channels: {}", self.num_channels);
        debug!(
            "Num Samples Per Channel: {}",
            self.get_num_samples_per_channel()
        );
    }
}
