// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

mod consts;

#[doc(inline)]
pub use consts::{
    HTAPS_1_34MHZ_7TO1_EQ, HTAPS_2_68MHZ_7TO1_EQ, HTAPS_2_68MHZ_14TO1_EQ,
    HTAPS_2_68MHZ_28TO1_EQ, HTAPS_2MHZ_7TO1_EQ, HTAPS_4MHZ_7TO1_EQ,
    HTAPS_288K_3TO1_EQ, HTAPS_576K_3TO1_EQ, HTAPS_DDRX5_7TO_1_EQ,
    HTAPS_DDRX5_14TO1_EQ, HTAPS_DDRX10_21TO1_EQ, HTAPS_DSDX5_7TO1_EQ,
    HTAPS_DSDX10_21TO1_EQ,
};
