// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::audio_file::{AudioFile, AudioFileFormat, AudioSample};
use crate::{Dither, DitherType, OutputType};
use flac_codec::metadata::{self, Picture, PictureType, VorbisComment};
use id3::TagLike;
use log::{debug, info};
use std::error::Error;
use std::io::Write;
use std::path::PathBuf;
use std::{io, vec};

mod consts;

use consts::ID3_TIPL_VORBIS_MAP;
use consts::ID3_TXXX_VORBIS_MAP;
use consts::ID3_VORBIS_MAP;

pub struct PcmWriter {
    float_data: Vec<f64>,
    scale_factor: f64,
    bits: usize,
    channels_num: usize,
    rate: u32,
    bytes_per_sample: usize,
    output: OutputType,
    path: Option<PathBuf>,
    peak_level: i32,
    clips: i32,
    dither: Dither,
    last_samps_clipped_low: i32,
    last_samps_clipped_high: i32,
    float_file: Option<AudioFile<f32>>,
    int_file: Option<AudioFile<i32>>,
    stdout_buf: Vec<u8>,
    vorbis: Option<VorbisComment>,
    pictures: Vec<Picture>,
}

impl PcmWriter {
    pub fn rate(&self) -> u32 {
        self.rate
    }
    pub fn channels_num(&self) -> usize {
        self.channels_num
    }
    pub fn clips(&self) -> i32 {
        self.clips
    }
    pub fn bytes_per_sample(&self) -> usize {
        self.bytes_per_sample
    }
    pub fn output(&self) -> OutputType {
        self.output
    }
    pub fn path(&self) -> &Option<PathBuf> {
        &self.path
    }
    pub fn scale_factor(&self) -> f64 {
        self.scale_factor
    }
    pub fn float_data_mut(&mut self) -> &mut Vec<f64> {
        &mut self.float_data
    }

    /// Create a PCM sink. Useful for level checks or whenever no file output is needed.
    /// 32 bit float PCM is assumed internally.
    /// * `out_rate` - output sample rate in Hz
    /// * `out_frames_capacity` - number of frames to allocate buffer for
    /// * `channels_num` - number of channels
    /// * `upsample_ratio` - upsample ratio (1 when not fractional)
    pub fn new_sink(
        out_rate: u32,
        out_frames_capacity: usize,
        channels_num: usize,
        upsample_ratio: u32,
    ) -> Result<Self, Box<dyn Error>> {
        Ok(Self {
            bits: 32,
            output: OutputType::Stdout,
            bytes_per_sample: 4,
            channels_num: channels_num,
            rate: out_rate,
            peak_level: 0,
            scale_factor: upsample_ratio as f64,
            float_file: None,
            int_file: None,
            stdout_buf: vec![0u8; out_frames_capacity * channels_num * 4],
            vorbis: None,
            pictures: Vec::new(),
            path: None,
            last_samps_clipped_low: 0,
            last_samps_clipped_high: 0,
            clips: 0,
            dither: Dither::new(DitherType::None)?,
            float_data: vec![0.0; out_frames_capacity],
        })
    }

    pub fn new(
        out_bits: usize,
        out_type: OutputType,
        out_vol: f64,
        out_rate: u32,
        out_path: Option<PathBuf>,
        dither: Dither,
        out_frames_capacity: usize,
        channels_num: usize,
        upsample_ratio: u32,
    ) -> Result<Self, Box<dyn Error>> {
        if ![16, 20, 24, 32].contains(&out_bits) {
            return Err("Unsupported bit depth".into());
        }

        if out_type == OutputType::Stdout && out_path.is_some() {
            return Err(
                "Cannot specify output path when outputting to stdout"
                    .into(),
            );
        }

        if out_bits == 32
            && out_type != OutputType::Stdout
            && out_type != OutputType::Wav
            && out_type != OutputType::Aifc
        {
            return Err(
                "32 bit float only allowed with wav, aifc, or stdout"
                    .into(),
            );
        }

        let bytes_per_sample =
            if out_bits == 20 { 3 } else { out_bits / 8 };

        let canon_path = if let Some(p) = &out_path {
            if !p.exists() {
                return Err(format!(
                    "Specified output path does not exist: {}",
                    p.display()
                )
                .into());
            }
            Some(p.canonicalize()?)
        } else {
            None
        };

        let mut ctx = Self {
            bits: out_bits,
            output: out_type,
            bytes_per_sample,
            channels_num: channels_num,
            rate: out_rate,
            peak_level: 0,
            scale_factor: 1.0,
            float_file: None,
            int_file: None,
            stdout_buf: vec![
                0u8;
                out_frames_capacity
                    * channels_num
                    * bytes_per_sample
            ],
            vorbis: None,
            pictures: Vec::new(),
            path: canon_path,
            last_samps_clipped_low: 0,
            last_samps_clipped_high: 0,
            clips: 0,
            dither,
            float_data: vec![0.0; out_frames_capacity],
        };
        debug!("Dither type: {:#?}", ctx.dither.dither_type());

        ctx.set_scaling(out_vol, upsample_ratio);

        if ctx.output != OutputType::Stdout {
            ctx.init_file();
        }

        Ok(ctx)
    }

    fn init_file(&mut self) {
        if self.bits == 32 {
            let float_file =
                AudioFile::new(self.channels_num, self.bits, self.rate);
            self.float_file = Some(float_file);
        } else {
            let int_file =
                AudioFile::new(self.channels_num, self.bits, self.rate);
            self.int_file = Some(int_file);
        }
    }

    fn add_picture(&mut self, pic: Picture) {
        self.pictures.push(pic);
    }

    fn set_vorbis(&mut self, vorbis: VorbisComment) {
        self.vorbis = Some(vorbis);
    }

    pub fn set_scaling(&mut self, volume: f64, upsample_ratio: u32) {
        let vol_scale = 10.0f64.powf(volume / 20.0);

        if self.bits != 32 {
            self.scale_factor = 2.0f64.powi(self.bits as i32 - 1);
        }

        self.peak_level = self.scale_factor.floor() as i32;
        self.scale_factor *= vol_scale;
        self.scale_factor *= upsample_ratio as f64
    }

    pub fn save_file(&self, out_path: &PathBuf) -> Result<(), String> {
        match self.output {
            OutputType::Wav => {
                self.save_and_print_file(out_path, AudioFileFormat::Wave)?;
            }
            OutputType::Aiff => {
                self.save_and_print_file(out_path, AudioFileFormat::Aiff)?;
            }
            OutputType::Aifc => {
                self.save_and_print_file(out_path, AudioFileFormat::Aifc)?;
            }
            OutputType::Flac => {
                self.save_and_print_file(out_path, AudioFileFormat::Flac)?;
            }
            _ => {}
        }
        Ok(())
    }

    /// Save audio file, forcibly overwriting any existing file at the target path
    pub fn save_and_print_file(
        &self,
        out_path: &PathBuf,
        fmt: AudioFileFormat,
    ) -> Result<(), String> {
        let path = out_path.as_path();
        if path.exists() {
            // Best effort remove; propagate error if it fails (e.g. permission issues)
            std::fs::remove_file(path).map_err(|e| {
                format!(
                    "Failed to remove existing file '{}': {}",
                    out_path.to_string_lossy(),
                    e
                )
            })?;
        }

        match (self.bits == 32, &self.float_file, &self.int_file) {
            (true, Some(file), _) => {
                file.save(
                    out_path,
                    fmt,
                    self.vorbis.clone(),
                    self.pictures.clone(),
                )
                .map_err(|e| e.to_string())?;
                file.print_summary();
            }
            (false, _, Some(file)) => {
                file.save(
                    out_path,
                    fmt,
                    self.vorbis.clone(),
                    self.pictures.clone(),
                )
                .map_err(|e| e.to_string())?;
                file.print_summary();
            }
            _ => return Err("No file initialized".to_string()),
        }

        info!("Wrote to file: {}", out_path.to_string_lossy());
        Ok(())
    }

    pub fn pack_float(&mut self, offset: &mut usize, sample: f64) {
        // Convert to f32 and write in little-endian
        let bytes = (sample as f32).to_le_bytes();
        self.stdout_buf[*offset..*offset + 4].copy_from_slice(&bytes);
        *offset += 4;
    }

    pub fn pack_int(&mut self, offset: &mut usize, value: i32) {
        if *offset + self.bytes_per_sample > self.stdout_buf.len() {
            return;
        }

        match self.bytes_per_sample {
            3 => {
                // 24-bit container (also used for 20-bit). For 20-bit we left-align by shifting 4.
                let mut v = value;
                if self.bits == 20 {
                    v <<= 4; // align 20 significant bits into the top of 24-bit word (LS 4 bits zero)
                }
                self.stdout_buf[*offset] = (v & 0xFF) as u8;
                self.stdout_buf[*offset + 1] = ((v >> 8) & 0xFF) as u8;
                self.stdout_buf[*offset + 2] = ((v >> 16) & 0xFF) as u8;
            }
            2 => {
                let v = value as i16;
                let b = v.to_le_bytes();
                self.stdout_buf[*offset..*offset + 2].copy_from_slice(&b);
            }
            _ => return,
        }
        *offset += self.bytes_per_sample;
    }

    pub fn write_stdout(
        &mut self,
        pcm_bytes: usize,
    ) -> Result<(), Box<dyn Error>> {
        if pcm_bytes == 0 || pcm_bytes > self.stdout_buf.len() {
            return Ok(());
        }

        io::stdout().write_all(&self.stdout_buf[..pcm_bytes])?;
        io::stdout().flush()?;
        Ok(())
    }

    pub fn push_samp<T: AudioSample>(&mut self, samp: T, channel: usize) {
        if self.bits == 32 {
            if let Some(file) = &mut self.float_file {
                file.samples_mut()[channel].push(samp.to_f32());
            }
        } else {
            if let Some(file) = &mut self.int_file {
                file.samples_mut()[channel].push(samp.to_i32());
            }
        }
    }

    /// Convert ID3 tag to FLAC VorbisComment metadata, following the
    /// same field mapping used by MusicBrainz Picard.
    pub fn id3_to_flac_meta(&mut self, tag: &id3::Tag) {
        let unix_datetime = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or_default();
        let mut vorbis = metadata::VorbisComment {
            vendor_string: format!(
                "dsd2dxd v{} Unix datetime {}",
                env!("CARGO_PKG_VERSION"),
                unix_datetime
            ),
            fields: Vec::new(),
        };

        // One-to-one text frame mappings via ID3_VORBIS_MAP
        for &(id3_id, vorbis_name) in ID3_VORBIS_MAP {
            if let Some(v) =
                tag.get(id3_id).and_then(|f| f.content().text())
            {
                for val in v.split('\0').filter(|s| !s.is_empty()) {
                    vorbis.insert(vorbis_name, val);
                }
            }
        }

        // TRCK -> TRACKNUMBER + TOTALTRACKS/TRACKTOTAL (parsed from "n/total")
        if let Some(n) = tag.track() {
            vorbis.insert("TRACKNUMBER", &n.to_string());
        }
        if let Some(n) = tag.total_tracks() {
            let s = n.to_string();
            vorbis.insert("TOTALTRACKS", &s);
            vorbis.insert("TRACKTOTAL", &s);
        }

        // TPOS -> DISCNUMBER + TOTALDISCS/DISCTOTAL (parsed from "n/total")
        if let Some(n) = tag.disc() {
            vorbis.insert("DISCNUMBER", &n.to_string());
        }
        if let Some(n) = tag.total_discs() {
            let s = n.to_string();
            vorbis.insert("TOTALDISCS", &s);
            vorbis.insert("DISCTOTAL", &s);
        }

        // TDRC -> DATE (full ISO timestamp); fall back to TYER year
        if let Some(date) = tag.date_recorded() {
            vorbis.insert("DATE", &date.to_string());
        } else if let Some(year) = tag.year() {
            vorbis.insert("DATE", &year.to_string());
        }

        // TDOR -> ORIGINALDATE; fall back to TORY (ID3v2.3 equivalent)
        if let Some(v) = tag
            .get("TDOR")
            .or_else(|| tag.get("TORY"))
            .and_then(|f| f.content().text())
        {
            vorbis.insert("ORIGINALDATE", v);
        }

        // MVIN -> MOVEMENTTOTAL + MOVEMENT (two Vorbis fields, one frame)
        if let Some(v) = tag.get("MVIN").and_then(|f| f.content().text()) {
            vorbis.insert("MOVEMENTTOTAL", v);
            vorbis.insert("MOVEMENT", v);
        }

        // COMM -> COMMENT
        if let Some(f) = tag.get("COMM") {
            if let id3::Content::Comment(comm) = f.content() {
                vorbis.insert("COMMENT", &comm.text);
            }
        }

        // USLT -> LYRICS
        if let Some(f) = tag.get("USLT") {
            if let id3::Content::Lyrics(lyrics) = f.content() {
                vorbis.insert("LYRICS", &lyrics.text);
            }
        }

        // TIPL/IPLS -> role-based fields via ID3_TIPL_VORBIS_MAP
        for frame in tag
            .frames()
            .filter(|f| f.id() == "TIPL" || f.id() == "IPLS")
        {
            if let id3::Content::InvolvedPeopleList(ip) = frame.content() {
                for item in &ip.items {
                    for &(r, vorbis_name) in ID3_TIPL_VORBIS_MAP {
                        if item.involvement.eq_ignore_ascii_case(r) {
                            vorbis.insert(vorbis_name, &item.involvee);
                        }
                    }
                }
            }
        }

        // TMCL -> PERFORMER "artist (instrument)"
        for frame in tag.frames().filter(|f| f.id() == "TMCL") {
            if let id3::Content::InvolvedPeopleList(mc) = frame.content() {
                for item in &mc.items {
                    vorbis.insert(
                        "PERFORMER",
                        &format!(
                            "{} ({})",
                            item.involvee, item.involvement
                        ),
                    );
                }
            }
        }

        // UFID:http://musicbrainz.org -> MUSICBRAINZ_TRACKID
        for frame in tag.frames().filter(|f| f.id() == "UFID") {
            if let id3::Content::UniqueFileIdentifier(ufid) =
                frame.content()
            {
                if ufid.owner_identifier == "http://musicbrainz.org" {
                    if let Ok(mbid) = std::str::from_utf8(&ufid.identifier)
                    {
                        vorbis.insert("MUSICBRAINZ_TRACKID", mbid);
                    }
                }
            }
        }

        // WCOP -> LICENSE, WOAR -> WEBSITE (web URL frames)
        for (frame_id, vorbis_name) in
            [("WCOP", "LICENSE"), ("WOAR", "WEBSITE")]
        {
            if let Some(f) = tag.get(frame_id) {
                if let id3::Content::Link(url) = f.content() {
                    vorbis.insert(vorbis_name, url);
                }
            }
        }

        // TXXX -> use ID3_TXXX_VORBIS_MAP for known descriptions that need
        // renaming; fall back to the description as-is for everything else
        // (ReplayGain, ASIN, BARCODE, CATALOGNUMBER, etc.).
        for et in tag.extended_texts() {
            if et.description.is_empty() {
                continue;
            }
            let vorbis_name = ID3_TXXX_VORBIS_MAP
                .iter()
                .find(|(desc, _)| {
                    desc.eq_ignore_ascii_case(&et.description)
                })
                .map(|&(_, name)| name)
                .unwrap_or(&et.description);
            for val in et.value.split('\0').filter(|s| !s.is_empty()) {
                vorbis.insert(vorbis_name, val);
            }
        }

        self.set_vorbis(vorbis);

        for pic in tag.pictures() {
            let pic_type: PictureType = if pic.picture_type
                == id3::frame::PictureType::CoverFront
            {
                flac_codec::metadata::PictureType::FrontCover
            } else if pic.picture_type
                == id3::frame::PictureType::CoverBack
            {
                flac_codec::metadata::PictureType::BackCover
            } else {
                continue;
            };
            debug!("Adding ID3 Picture: {}", pic);
            let picture = flac_codec::metadata::Picture::new(
                pic_type,
                pic.description.clone(),
                pic.data.clone(),
            );
            if let Ok(my_pic) = picture {
                self.add_picture(my_pic);
            }
        }
    }

    #[inline(always)]
    pub fn write_to_buffer(
        &mut self,
        samples_used_per_chan: usize,
        chan: usize,
    ) {
        // Output / packing for channel
        if self.output == OutputType::Stdout {
            // Interleave into pcm_data (handle float vs integer separately)
            let bps = self.bytes_per_sample; // 4 for 32-bit float
            let mut pcm_pos = chan * bps;
            for s in 0..samples_used_per_chan {
                let mut out_idx = pcm_pos;
                if self.bits == 32 {
                    // 32-bit float path
                    let mut q = self.float_data[s];
                    self.scale_and_dither(&mut q);
                    self.pack_float(&mut out_idx, q);
                } else {
                    // Integer path: dither + clamp + write_int
                    let mut qin: f64 = self.float_data[s];
                    self.scale_and_dither(&mut qin);
                    let quantized = self.quantize(&mut qin);
                    self.pack_int(&mut out_idx, quantized);
                }
                pcm_pos += self.channels_num * bps;
            }
        } else if self.bits == 32 {
            for s in 0..samples_used_per_chan {
                let mut q = self.float_data[s];
                self.scale_and_dither(&mut q);
                self.push_samp(q as f32, chan);
            }
        } else {
            for s in 0..samples_used_per_chan {
                let mut qin: f64 = self.float_data[s];
                self.scale_and_dither(&mut qin);
                let quantized = self.quantize(&mut qin);
                self.push_samp(quantized, chan);
            }
        }
    }

    #[inline(always)]
    fn scale_and_dither(&mut self, sample: &mut f64) {
        *sample *= self.scale_factor;
        self.dither.process_samp(sample);
    }

    // Helper function for clip stats
    #[inline(always)]
    fn update_clip_stats(&mut self, low: bool, high: bool) {
        if low {
            if self.last_samps_clipped_low == 1 {
                self.clips += 1;
            }
            self.last_samps_clipped_low += 1;
            return;
        }
        self.last_samps_clipped_low = 0;
        if high {
            if self.last_samps_clipped_high == 1 {
                self.clips += 1;
            }
            self.last_samps_clipped_high += 1;
            return;
        }
        self.last_samps_clipped_high = 0;
    }

    #[inline(always)]
    pub fn quantize(&mut self, qin: &mut f64) -> i32 {
        let value = Self::my_round(*qin) as i32;
        let peak = self.peak_level as i32;
        self.clamp_value(-peak, value, peak - 1)
    }

    #[inline(always)]
    fn clamp_value(&mut self, min: i32, value: i32, max: i32) -> i32 {
        return if value < min {
            self.update_clip_stats(true, false);
            min
        } else if value > max {
            self.update_clip_stats(false, true);
            max
        } else {
            self.update_clip_stats(false, false);
            value
        };
    }

    #[inline(always)]
    fn my_round(x: f64) -> i64 {
        if x < 0.0 {
            (x - 0.5).floor() as i64
        } else {
            (x + 0.5).floor() as i64
        }
    }
}
