// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::CROSS_DECORR;
use super::consts::HYBRID_FLAG;
use super::consts::HYBRID_SHAPE;
use super::consts::JOINT_STEREO;
use super::consts::MAX_TERM_USIZE;
use super::decorr::decorr_mono_pass;
use super::decorr::decorr_mono_sample;
use super::decorr::decorr_stereo_pass;
use super::decorr::decorr_stereo_sample;
use super::is::is_mono;
use super::misc::undo_joint_stereo;
use super::predict::preview_corrected_stereo_sample;
use super::shape::shape_corrected_output;
use super::shape::shape_hybrid_sample;
use super::types::DecodedWord;
use super::types::DecorrPass;
use super::types::ShapingInfo;
use symphonia_core::errors::{Result, decode_error};

pub(super) fn apply_weight(weight: i32, sample: i32) -> i32 {
    if sample == i32::from(sample as i16) {
        weight.wrapping_mul(sample).wrapping_add(512) >> 10
    } else {
        let low = ((sample & 0xffff).wrapping_mul(weight)) >> 9;
        let high = ((sample & !0xffff) >> 9).wrapping_mul(weight);
        low.wrapping_add(high).wrapping_add(1) >> 1
    }
}

pub(super) fn apply_decorr_passes(
    samples: &mut [i32],
    flags: u32,
    sample_count: usize,
    passes: &[DecorrPass],
) -> Result<()> {
    let channels = if is_mono(flags) { 1 } else { 2 };

    if samples.len() != sample_count * channels {
        return decode_error("wavpack: invalid decorrelation buffer length");
    }

    for pass in passes {
        let mut pass = *pass;

        if channels == 1 {
            decorr_mono_pass(&mut pass, samples);
        } else {
            decorr_stereo_pass(&mut pass, samples);
        }
    }

    if channels == 2 && flags & JOINT_STEREO != 0 {
        undo_joint_stereo(samples);
    }

    Ok(())
}

pub(super) fn apply_hybrid_correction_into(
    residuals: &[DecodedWord],
    flags: u32,
    sample_count: usize,
    passes: &[DecorrPass],
    shaping_info: Option<ShapingInfo>,
    samples: &mut Vec<i32>,
    decorr_passes: &mut Vec<DecorrPass>,
) -> Result<()> {
    if flags & HYBRID_FLAG == 0 {
        return decode_error("wavpack: correction bitstream without hybrid coding");
    }

    let channels = if is_mono(flags) { 1 } else { 2 };

    if residuals.len() != sample_count * channels {
        return decode_error("wavpack: invalid correction buffer length");
    }

    decorr_passes.clear();
    decorr_passes.extend_from_slice(passes);
    samples.clear();
    samples.reserve(residuals.len());

    let mut shaping = shaping_info.unwrap_or_default();
    let mut m = 0;

    if channels == 1 {
        for word in residuals {
            let mut sample = word.value;

            for pass in decorr_passes.iter_mut() {
                sample = decorr_mono_sample(pass, sample, m);
            }

            m = (m + 1) & (MAX_TERM_USIZE - 1);
            samples.push(shape_hybrid_sample(
                flags,
                &mut shaping,
                0,
                sample,
                word.correction,
            ));
        }
    } else {
        for frame in residuals.chunks_exact(2) {
            let mut left = frame[0].value;
            let mut right = frame[1].value;
            let corrections = [frame[0].correction, frame[1].correction];
            let mut left_c = 0;
            let mut right_c = 0;

            if flags & CROSS_DECORR != 0 {
                left_c = left.wrapping_add(corrections[0]);
                right_c = right.wrapping_add(corrections[1]);

                for pass in decorr_passes.iter() {
                    (left_c, right_c) = preview_corrected_stereo_sample(pass, left_c, right_c, m);
                }

                if flags & JOINT_STEREO != 0 {
                    right_c = right_c.wrapping_sub(left_c >> 1);
                    left_c = left_c.wrapping_add(right_c);
                }
            }

            for pass in decorr_passes.iter_mut() {
                (left, right) = decorr_stereo_sample(pass, left, right, m);
            }

            m = (m + 1) & (MAX_TERM_USIZE - 1);

            if flags & CROSS_DECORR == 0 {
                left_c = left.wrapping_add(corrections[0]);
                right_c = right.wrapping_add(corrections[1]);

                if flags & JOINT_STEREO != 0 {
                    right_c = right_c.wrapping_sub(left_c >> 1);
                    left_c = left_c.wrapping_add(right_c);
                }
            }

            if flags & JOINT_STEREO != 0 {
                right = right.wrapping_sub(left >> 1);
                left = left.wrapping_add(right);
            }

            if flags & HYBRID_SHAPE != 0 {
                left = shape_corrected_output(flags, &mut shaping, 0, left, left_c);
                right = shape_corrected_output(flags, &mut shaping, 1, right, right_c);
            } else {
                left = left_c;
                right = right_c;
            }

            samples.push(left);
            samples.push(right);
        }
    }

    Ok(())
}

pub(super) fn apply_int32_redundancy(sample: &mut i32, zeros: u32, ones: u32, dups: u32) {
    if zeros != 0 {
        *sample = ((*sample as u32) << zeros) as i32;
    } else if ones != 0 {
        *sample = (((*sample).wrapping_add(1) as u32) << ones).wrapping_sub(1) as i32;
    } else if dups != 0 {
        let low_bit = *sample & 1;
        *sample =
            (((*sample).wrapping_add(low_bit) as u32) << dups).wrapping_sub(low_bit as u32) as i32;
    }
}
