// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_weight;
use super::consts::MAX_TERM;
use super::consts::MAX_TERM_USIZE;
use super::predict::predict_term_17;
use super::predict::predict_term_18;
use super::predict::predict_term_18_stereo;
use super::types::DecorrPass;
use super::update::update_weight;
use super::update::update_weight_clip;

pub(super) fn decorr_mono_sample(pass: &mut DecorrPass, residual: i32, m: usize) -> i32 {
    let (sam, k) = if pass.term > MAX_TERM {
        let sam = if pass.term & 1 != 0 {
            predict_term_17(pass.samples_a[0], pass.samples_a[1])
        } else {
            predict_term_18(pass.samples_a[0], pass.samples_a[1])
        };

        pass.samples_a[1] = pass.samples_a[0];
        (sam, 0)
    } else {
        (
            pass.samples_a[m],
            (m + pass.term as usize) & (MAX_TERM_USIZE - 1),
        )
    };

    let sample = apply_weight(pass.weight_a, sam).wrapping_add(residual);
    update_weight(&mut pass.weight_a, pass.delta, sam, residual);
    pass.samples_a[k] = sample;
    sample
}

pub(super) fn decorr_stereo_sample(
    pass: &mut DecorrPass,
    mut left: i32,
    mut right: i32,
    m: usize,
) -> (i32, i32) {
    if pass.term > 0 {
        let (sam_a, sam_b, k) = if pass.term > MAX_TERM {
            let (sam_a, sam_b) = if pass.term & 1 != 0 {
                (
                    predict_term_17(pass.samples_a[0], pass.samples_a[1]),
                    predict_term_17(pass.samples_b[0], pass.samples_b[1]),
                )
            } else {
                (
                    predict_term_18(pass.samples_a[0], pass.samples_a[1]),
                    predict_term_18(pass.samples_b[0], pass.samples_b[1]),
                )
            };

            pass.samples_a[1] = pass.samples_a[0];
            pass.samples_b[1] = pass.samples_b[0];
            (sam_a, sam_b, 0)
        } else {
            (
                pass.samples_a[m],
                pass.samples_b[m],
                (m + pass.term as usize) & (MAX_TERM_USIZE - 1),
            )
        };

        let left2 = apply_weight(pass.weight_a, sam_a).wrapping_add(left);
        let right2 = apply_weight(pass.weight_b, sam_b).wrapping_add(right);

        update_weight(&mut pass.weight_a, pass.delta, sam_a, left);
        update_weight(&mut pass.weight_b, pass.delta, sam_b, right);

        pass.samples_a[k] = left2;
        pass.samples_b[k] = right2;
        left = left2;
        right = right2;
    } else if pass.term == -1 {
        let left2 = left.wrapping_add(apply_weight(pass.weight_a, pass.samples_a[0]));
        update_weight_clip(&mut pass.weight_a, pass.delta, pass.samples_a[0], left);
        left = left2;

        let right2 = right.wrapping_add(apply_weight(pass.weight_b, left2));
        update_weight_clip(&mut pass.weight_b, pass.delta, left2, right);
        pass.samples_a[0] = right2;
        right = right2;
    } else {
        let mut right2 = right.wrapping_add(apply_weight(pass.weight_b, pass.samples_b[0]));
        update_weight_clip(&mut pass.weight_b, pass.delta, pass.samples_b[0], right);
        right = right2;

        if pass.term == -3 {
            right2 = pass.samples_a[0];
            pass.samples_a[0] = right;
        }

        let left2 = left.wrapping_add(apply_weight(pass.weight_a, right2));
        update_weight_clip(&mut pass.weight_a, pass.delta, right2, left);
        pass.samples_b[0] = left2;
        left = left2;
    }

    (left, right)
}

pub(super) fn decorr_mono_pass(pass: &mut DecorrPass, samples: &mut [i32]) {
    match pass.term {
        17 => {
            for sample in samples {
                let sam_a = predict_term_17(pass.samples_a[0], pass.samples_a[1]);
                pass.samples_a[1] = pass.samples_a[0];
                let residual = *sample;
                pass.samples_a[0] = apply_weight(pass.weight_a, sam_a).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam_a, residual);
                *sample = pass.samples_a[0];
            }
        }
        18 => {
            for sample in samples {
                let sam_a = predict_term_18(pass.samples_a[0], pass.samples_a[1]);
                pass.samples_a[1] = pass.samples_a[0];
                let residual = *sample;
                pass.samples_a[0] = apply_weight(pass.weight_a, sam_a).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam_a, residual);
                *sample = pass.samples_a[0];
            }
        }
        _ => {
            let mut m = 0;
            let mut k = pass.term as usize & (MAX_TERM_USIZE - 1);

            for sample in samples {
                let sam_a = pass.samples_a[m];
                let residual = *sample;
                pass.samples_a[k] = apply_weight(pass.weight_a, sam_a).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam_a, residual);
                *sample = pass.samples_a[k];
                m = (m + 1) & (MAX_TERM_USIZE - 1);
                k = (k + 1) & (MAX_TERM_USIZE - 1);
            }

            if m != 0 {
                let temp_samples = pass.samples_a;

                for (k, sample) in pass.samples_a.iter_mut().enumerate() {
                    *sample = temp_samples[(m + k) & (MAX_TERM_USIZE - 1)];
                }
            }
        }
    }
}

pub(super) fn decorr_stereo_pass(pass: &mut DecorrPass, samples: &mut [i32]) {
    match pass.term {
        17 => {
            for frame in samples.chunks_exact_mut(2) {
                let sam = predict_term_17(pass.samples_a[0], pass.samples_a[1]);
                pass.samples_a[1] = pass.samples_a[0];
                let residual = frame[0];
                pass.samples_a[0] = apply_weight(pass.weight_a, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam, residual);
                frame[0] = pass.samples_a[0];

                let sam = predict_term_17(pass.samples_b[0], pass.samples_b[1]);
                pass.samples_b[1] = pass.samples_b[0];
                let residual = frame[1];
                pass.samples_b[0] = apply_weight(pass.weight_b, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_b, pass.delta, sam, residual);
                frame[1] = pass.samples_b[0];
            }
        }
        18 => {
            for frame in samples.chunks_exact_mut(2) {
                let sam = predict_term_18_stereo(pass.samples_a[0], pass.samples_a[1]);
                pass.samples_a[1] = pass.samples_a[0];
                let residual = frame[0];
                pass.samples_a[0] = apply_weight(pass.weight_a, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam, residual);
                frame[0] = pass.samples_a[0];

                let sam = predict_term_18_stereo(pass.samples_b[0], pass.samples_b[1]);
                pass.samples_b[1] = pass.samples_b[0];
                let residual = frame[1];
                pass.samples_b[0] = apply_weight(pass.weight_b, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_b, pass.delta, sam, residual);
                frame[1] = pass.samples_b[0];
            }
        }
        -1 => {
            for frame in samples.chunks_exact_mut(2) {
                let sam = frame[0].wrapping_add(apply_weight(pass.weight_a, pass.samples_a[0]));
                update_weight_clip(&mut pass.weight_a, pass.delta, pass.samples_a[0], frame[0]);
                frame[0] = sam;
                pass.samples_a[0] = frame[1].wrapping_add(apply_weight(pass.weight_b, sam));
                update_weight_clip(&mut pass.weight_b, pass.delta, sam, frame[1]);
                frame[1] = pass.samples_a[0];
            }
        }
        -2 => {
            for frame in samples.chunks_exact_mut(2) {
                let sam = frame[1].wrapping_add(apply_weight(pass.weight_b, pass.samples_b[0]));
                update_weight_clip(&mut pass.weight_b, pass.delta, pass.samples_b[0], frame[1]);
                frame[1] = sam;
                pass.samples_b[0] = frame[0].wrapping_add(apply_weight(pass.weight_a, sam));
                update_weight_clip(&mut pass.weight_a, pass.delta, sam, frame[0]);
                frame[0] = pass.samples_b[0];
            }
        }
        -3 => {
            for frame in samples.chunks_exact_mut(2) {
                let sam_a = frame[0].wrapping_add(apply_weight(pass.weight_a, pass.samples_a[0]));
                update_weight_clip(&mut pass.weight_a, pass.delta, pass.samples_a[0], frame[0]);
                let sam_b = frame[1].wrapping_add(apply_weight(pass.weight_b, pass.samples_b[0]));
                update_weight_clip(&mut pass.weight_b, pass.delta, pass.samples_b[0], frame[1]);
                pass.samples_b[0] = sam_a;
                pass.samples_a[0] = sam_b;
                frame[0] = sam_a;
                frame[1] = sam_b;
            }
        }
        _ => {
            let mut m = 0;
            let mut k = pass.term as usize & (MAX_TERM_USIZE - 1);

            for frame in samples.chunks_exact_mut(2) {
                let sam = pass.samples_a[m];
                let residual = frame[0];
                pass.samples_a[k] = apply_weight(pass.weight_a, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_a, pass.delta, sam, residual);
                frame[0] = pass.samples_a[k];

                let sam = pass.samples_b[m];
                let residual = frame[1];
                pass.samples_b[k] = apply_weight(pass.weight_b, sam).wrapping_add(residual);
                update_weight(&mut pass.weight_b, pass.delta, sam, residual);
                frame[1] = pass.samples_b[k];

                m = (m + 1) & (MAX_TERM_USIZE - 1);
                k = (k + 1) & (MAX_TERM_USIZE - 1);
            }
        }
    }
}
