// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::DECAY;
use super::consts::DOWN;
use super::consts::MAX_BYTES_PER_BIN;
use super::consts::MAX_HISTORY_BITS;
use super::consts::MONO_FLAG;
use super::consts::PRECISION;
use super::consts::PRECISION_USE;
use super::consts::PTABLE_MASK;
use super::consts::RATE_S;
use super::consts::UP;
use super::consts::VALUE_ONE;
use super::consts::init_dsd_ptable;
use super::dsd_scratch::DsdScratch;
use super::types::DsdFilterState;
use super::types::DsdInfo;
use symphonia_core::errors::{Result, decode_error, unsupported_error};

pub(super) fn decode_dsd_into(
    samples: &mut Vec<i32>,
    dsd: DsdInfo<'_>,
    flags: u32,
    block_samples: usize,
    scratch: &mut DsdScratch,
) -> Result<()> {
    let channels = if flags & MONO_FLAG != 0 { 1 } else { 2 };
    let total = block_samples.saturating_mul(channels);
    samples.clear();
    samples.reserve(total);

    match dsd.mode {
        0 => {
            if dsd.payload.len() < total {
                return decode_error("wavpack: truncated dsd payload");
            }
            samples.extend(dsd.payload[..total].iter().copied().map(i32::from));
        }
        1 => decode_dsd_mode_fast_into(samples, dsd.payload, total, channels, scratch)?,
        3 => decode_dsd_mode_high_into(samples, dsd.payload, total, channels, scratch)?,
        _ => return unsupported_error("wavpack: unknown compressed dsd mode"),
    }

    Ok(())
}

pub(super) fn decode_dsd_mode_fast_into(
    output: &mut Vec<i32>,
    payload: &[u8],
    total: usize,
    channels: usize,
    scratch: &mut DsdScratch,
) -> Result<()> {
    if payload.len() < 2 {
        return decode_error("wavpack: invalid dsd fast payload");
    }

    let mut cursor = 0usize;
    let history_bits = payload[cursor];
    cursor += 1;
    if history_bits > MAX_HISTORY_BITS {
        return decode_error("wavpack: invalid dsd history bits");
    }
    let history_bins = 1usize << history_bits;

    let max_probability = payload[cursor];
    cursor += 1;

    let table_len = history_bins * 256;
    scratch.probabilities.clear();
    scratch.probabilities.resize(table_len, 0);
    let probabilities = &mut scratch.probabilities;

    if max_probability < 0xff {
        let mut out_idx = 0usize;
        while out_idx < table_len && cursor < payload.len() {
            let code = payload[cursor];
            cursor += 1;
            if code > max_probability {
                let zcount = usize::from(code - max_probability);
                let fill = zcount.min(table_len - out_idx);
                out_idx += fill;
            } else if code != 0 {
                probabilities[out_idx] = code;
                out_idx += 1;
            } else {
                break;
            }
        }
        if out_idx < table_len {
            return decode_error("wavpack: invalid dsd probability table");
        }
        if cursor < payload.len() {
            if payload[cursor] != 0 {
                return decode_error("wavpack: invalid dsd probability terminator");
            }
            cursor += 1;
        }
    } else {
        if payload.len().saturating_sub(cursor) < table_len {
            return decode_error("wavpack: invalid dsd probability table size");
        }
        probabilities.copy_from_slice(&payload[cursor..cursor + table_len]);
        cursor += table_len;
    }

    scratch.summed.clear();
    scratch.summed.resize(table_len, 0);
    scratch.offsets.clear();
    scratch.offsets.resize(history_bins, usize::MAX);
    scratch.lookup.clear();
    scratch.lookup.reserve(history_bins * MAX_BYTES_PER_BIN);
    let summed = &mut scratch.summed;
    let offsets = &mut scratch.offsets;
    let lookup = &mut scratch.lookup;

    for (bi, offset) in offsets.iter_mut().enumerate().take(history_bins) {
        let base = bi * 256;
        let mut sum = 0u32;
        for i in 0..256 {
            sum = sum.wrapping_add(u32::from(probabilities[base + i]));
            summed[base + i] = sum as u16;
        }
        if sum != 0 {
            if sum as usize > MAX_BYTES_PER_BIN {
                return decode_error("wavpack: invalid dsd summed probabilities");
            }
            *offset = lookup.len();
            for i in 0..256 {
                let c = probabilities[base + i];
                if c != 0 {
                    lookup.extend(std::iter::repeat_n(i as u8, usize::from(c)));
                }
            }
        }
    }

    if payload.len().saturating_sub(cursor) < 4 {
        return decode_error("wavpack: truncated dsd fast range state");
    }

    let mut value = 0u32;
    for _ in 0..4 {
        value = (value << 8) | u32::from(payload[cursor]);
        cursor += 1;
    }
    let mut low = 0u32;
    let mut high = u32::MAX;
    let mut p0 = 0usize;
    let mut p1 = 0usize;
    let mono = channels == 1;

    for _ in 0..total {
        let base = p0 * 256;
        let sum_total = u32::from(summed[base + 255]);
        if sum_total == 0 {
            return decode_error("wavpack: invalid dsd probability state");
        }

        let mut mult = (high.wrapping_sub(low)) / sum_total;
        if mult == 0 {
            if payload.len().saturating_sub(cursor) < 4 {
                return decode_error("wavpack: truncated dsd fast range state");
            }
            value = 0;
            for _ in 0..4 {
                value = (value << 8) | u32::from(payload[cursor]);
                cursor += 1;
            }
            low = 0;
            high = u32::MAX;
            mult = high / sum_total;
            if mult == 0 {
                return decode_error("wavpack: invalid dsd range multiplier");
            }
        }

        let index = value.wrapping_sub(low) / mult;
        if index >= sum_total {
            return decode_error("wavpack: invalid dsd range index");
        }

        let off = offsets[p0];
        if off == usize::MAX {
            return decode_error("wavpack: missing dsd lookup bin");
        }
        let code = lookup[off + index as usize];
        output.push(i32::from(code));

        if code != 0 {
            low = low
                .wrapping_add(u32::from(summed[base + usize::from(code) - 1]).wrapping_mul(mult));
        }
        high = low
            .wrapping_add(u32::from(probabilities[base + usize::from(code)]).wrapping_mul(mult))
            .wrapping_sub(1);

        if mono {
            p0 = usize::from(code) & (history_bins - 1);
        } else {
            p0 = p1;
            p1 = usize::from(code) & (history_bins - 1);
        }

        while ((high ^ low) & 0xff00_0000) == 0 {
            if cursor >= payload.len() {
                return decode_error("wavpack: truncated dsd fast bitstream");
            }
            value = (value << 8) | u32::from(payload[cursor]);
            cursor += 1;
            high = (high << 8) | 0xff;
            low <<= 8;
        }
    }

    Ok(())
}

pub(super) fn decode_dsd_mode_high_into(
    output: &mut Vec<i32>,
    payload: &[u8],
    total: usize,
    channels: usize,
    scratch: &mut DsdScratch,
) -> Result<()> {
    let header_len = 2 + channels * 7 + 4;
    if payload.len() < header_len {
        return decode_error("wavpack: invalid dsd high payload");
    }
    let mut cursor = 0usize;
    let rate_i = payload[cursor];
    cursor += 1;
    let rate_s = payload[cursor];
    cursor += 1;
    if rate_s != RATE_S {
        return decode_error("wavpack: unsupported dsd high slope");
    }

    let mut filters = [DsdFilterState::default(), DsdFilterState::default()];
    for state in filters.iter_mut().take(channels) {
        state.filter1 = i32::from(payload[cursor]) << (PRECISION - 8);
        cursor += 1;
        state.filter2 = i32::from(payload[cursor]) << (PRECISION - 8);
        cursor += 1;
        state.filter3 = i32::from(payload[cursor]) << (PRECISION - 8);
        cursor += 1;
        state.filter4 = i32::from(payload[cursor]) << (PRECISION - 8);
        cursor += 1;
        state.filter5 = i32::from(payload[cursor]) << (PRECISION - 8);
        cursor += 1;
        state.filter6 = 0;
        let factor = i16::from_le_bytes([payload[cursor], payload[cursor + 1]]);
        cursor += 2;
        state.factor = i32::from(factor);
    }

    let mut value = 0u32;
    for _ in 0..4 {
        value = (value << 8) | u32::from(payload[cursor]);
        cursor += 1;
    }
    let mut low = 0u32;
    let mut high = u32::MAX;
    init_dsd_ptable(&mut scratch.ptable, rate_i);
    let ptable = &mut scratch.ptable;

    let frames = total / channels;
    for _ in 0..frames {
        for state in filters.iter_mut().take(channels) {
            state.value = state.filter1 - state.filter5 + ((state.filter6 * state.factor) >> 2);
        }

        for _ in 0..8 {
            for state in filters.iter_mut().take(channels) {
                let pidx = ((state.value >> (PRECISION - PRECISION_USE)) as usize) & PTABLE_MASK;
                let pp = &mut ptable[pidx];
                let split = low
                    .wrapping_add(((high.wrapping_sub(low)) >> 8).wrapping_mul((*pp >> 16) as u32));
                let filter0 = if value <= split {
                    high = split;
                    *pp += (UP - *pp) >> DECAY;
                    -1
                } else {
                    low = split.wrapping_add(1);
                    *pp += (DOWN - *pp) >> DECAY;
                    0
                };

                while ((high ^ low) & 0xff00_0000) == 0 {
                    if cursor >= payload.len() {
                        return decode_error("wavpack: truncated dsd high bitstream");
                    }
                    value = (value << 8) | u32::from(payload[cursor]);
                    cursor += 1;
                    high = (high << 8) | 0xff;
                    low <<= 8;
                }

                state.value += state.filter6 * 8;
                state.byte = (state.byte << 1) | ((filter0 & 1) as u8);
                state.factor += (((state.value ^ filter0) >> 31) | 1)
                    & ((state.value ^ (state.value - (state.filter6 * 16))) >> 31);
                state.filter1 += ((filter0 & VALUE_ONE) - state.filter1) >> 6;
                state.filter2 += ((filter0 & VALUE_ONE) - state.filter2) >> 4;
                state.filter3 += (state.filter2 - state.filter3) >> 4;
                state.filter4 += (state.filter3 - state.filter4) >> 4;
                state.value = (state.filter4 - state.filter5) >> 4;
                state.filter5 += state.value;
                state.filter6 += (state.value - state.filter6) >> 3;
                state.value = state.filter1 - state.filter5 + ((state.filter6 * state.factor) >> 2);
            }
        }

        for state in filters.iter_mut().take(channels) {
            output.push(i32::from(state.byte));
            state.factor -= (state.factor + 512) >> 10;
        }
    }

    Ok(())
}
