// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_decorr_passes;
use super::apply::apply_hybrid_correction_into;
use super::consts::ID_DECORR_SAMPLES;
use super::consts::ID_DECORR_TERMS;
use super::consts::ID_DECORR_WEIGHTS;
use super::consts::ID_DSD_BLOCK;
use super::consts::ID_ENTROPY_VARS;
use super::consts::ID_FLOAT_INFO;
use super::consts::ID_HYBRID_PROFILE;
use super::consts::ID_INT32_INFO;
use super::consts::ID_SHAPING_WEIGHTS;
use super::consts::ID_WV_BITSTREAM;
use super::consts::ID_WVC_BITSTREAM;
use super::consts::ID_WVX_BITSTREAM;
use super::consts::ID_WVX_NEW_BITSTREAM;
use super::consts::MAX_NTERMS;
use super::consts::WAVPACK_HEADER_LEN;
use super::consts::fixup_samples;
use super::decode::decode_dsd_into;
use super::dsd_scratch::DsdScratch;
use super::expand::expand_false_stereo;
use super::misc::dsd_crc;
use super::parse::parse_decorr_samples;
use super::parse::parse_decorr_terms;
use super::parse::parse_decorr_weights;
use super::parse::parse_dsd_info;
use super::parse::parse_entropy_vars;
use super::parse::parse_float_info;
use super::parse::parse_hybrid_profile;
use super::parse::parse_int32_info;
use super::parse::parse_shaping_info;
use super::types::DecodedWord;
use super::types::DecorrPass;
use super::types::DsdInfo;
use super::types::EntropyVars;
use super::types::FloatInfo;
use super::types::HybridProfile;
use super::types::Int32Info;
use super::types::ShapingInfo;
use super::wav_pack_bit_reader::WavPackBitReader;
use super::wav_pack_block_header::WavPackBlockHeader;
use super::wav_pack_metadata_iter::WavPackMetadataIter;
use super::words_decoder::WordsDecoder;
use symphonia_core::errors::{Error, Result, decode_error};

#[derive(Debug)]
pub(super) struct DecodeBlock<'a> {
    pub(super) header: WavPackBlockHeader,
    pub(super) decorr_passes: [DecorrPass; MAX_NTERMS],
    pub(super) decorr_pass_count: usize,
    pub(super) entropy: Option<EntropyVars>,
    pub(super) decorr_samples: Option<&'a [u8]>,
    pub(super) hybrid_profile: Option<HybridProfile>,
    pub(super) shaping_info: Option<ShapingInfo>,
    pub(super) float_info: Option<FloatInfo>,
    pub(super) int32_info: Option<Int32Info>,
    pub(super) dsd: Option<DsdInfo<'a>>,
    pub(super) wv_bitstream: Option<&'a [u8]>,
    pub(super) wvc_bitstream: Option<&'a [u8]>,
    pub(super) wvx_bitstream: Option<&'a [u8]>,
    pub(super) wvx_new_bitstream: bool,
}

impl<'a> DecodeBlock<'a> {
    pub(super) fn parse(data: &'a [u8]) -> Result<Self> {
        let header = WavPackBlockHeader::parse(data)?;

        if data.len() < header.byte_len() as usize {
            return decode_error("wavpack: block overruns packet");
        }

        let mut parsed = DecodeBlock {
            header,
            decorr_passes: [DecorrPass::default(); MAX_NTERMS],
            decorr_pass_count: 0,
            entropy: None,
            decorr_samples: None,
            hybrid_profile: None,
            shaping_info: None,
            float_info: None,
            int32_info: None,
            dsd: None,
            wv_bitstream: None,
            wvc_bitstream: None,
            wvx_bitstream: None,
            wvx_new_bitstream: false,
        };

        let body = &data[WAVPACK_HEADER_LEN..parsed.header.byte_len() as usize];

        for metadata in WavPackMetadataIter::new_data(body) {
            let metadata = metadata?;

            match metadata.id {
                ID_DECORR_TERMS => {
                    parsed.decorr_pass_count = parse_decorr_terms(
                        metadata.data,
                        parsed.header.flags,
                        &mut parsed.decorr_passes,
                    )?;
                }
                ID_DECORR_WEIGHTS => {
                    parse_decorr_weights(
                        metadata.data,
                        parsed.header.flags,
                        parsed.decorr_passes_mut(),
                    )?;
                }
                ID_DECORR_SAMPLES => parsed.decorr_samples = Some(metadata.data),
                ID_ENTROPY_VARS => {
                    parsed.entropy = Some(parse_entropy_vars(metadata.data, parsed.header.flags)?);
                }
                ID_HYBRID_PROFILE => {
                    parsed.hybrid_profile =
                        Some(parse_hybrid_profile(metadata.data, parsed.header.flags)?);
                }
                ID_SHAPING_WEIGHTS => {
                    parsed.shaping_info =
                        Some(parse_shaping_info(metadata.data, parsed.header.flags)?);
                }
                ID_FLOAT_INFO => parsed.float_info = Some(parse_float_info(metadata.data)?),
                ID_INT32_INFO => parsed.int32_info = Some(parse_int32_info(metadata.data)?),
                ID_DSD_BLOCK => parsed.dsd = Some(parse_dsd_info(metadata.data)?),
                ID_WV_BITSTREAM => parsed.wv_bitstream = Some(metadata.data),
                ID_WVC_BITSTREAM => parsed.wvc_bitstream = Some(metadata.data),
                ID_WVX_BITSTREAM => {
                    parsed.wvx_bitstream = Some(metadata.data);
                    parsed.wvx_new_bitstream = false;
                }
                ID_WVX_NEW_BITSTREAM => {
                    parsed.wvx_bitstream = Some(metadata.data);
                    parsed.wvx_new_bitstream = true;
                }
                _ => (),
            }
        }

        if parsed.header.block_samples != 0 && parsed.wv_bitstream.is_none() && parsed.dsd.is_none()
        {
            return decode_error("wavpack: missing audio bitstream");
        }

        if let Some(decorr_samples) = parsed.decorr_samples {
            parse_decorr_samples(
                decorr_samples,
                parsed.header._version,
                parsed.header.flags,
                parsed.decorr_passes_mut(),
            )?;
        }

        Ok(parsed)
    }

    pub(super) fn metadata_summary(&self) -> (usize, bool, bool, bool, bool) {
        (
            self.decorr_pass_count,
            self.entropy.is_some(),
            self.decorr_samples.is_some()
                || self.hybrid_profile.is_some()
                || self.shaping_info.is_some()
                || self.wv_bitstream.is_some(),
            self.wvc_bitstream.is_some() || self.wvx_bitstream.is_some(),
            self.float_info.is_some() || self.int32_info.is_some(),
        )
    }

    pub(super) fn decorr_passes(&self) -> &[DecorrPass] {
        &self.decorr_passes[..self.decorr_pass_count]
    }

    pub(super) fn decorr_passes_mut(&mut self) -> &mut [DecorrPass] {
        &mut self.decorr_passes[..self.decorr_pass_count]
    }

    pub(super) fn read_decorrelated_samples_into(
        &self,
        residuals: &mut Vec<DecodedWord>,
        samples: &mut Vec<i32>,
        decorr_passes: &mut Vec<DecorrPass>,
        dsd_scratch: &mut DsdScratch,
    ) -> Result<bool> {
        if self.header.block_samples == 0 {
            samples.clear();
            return Ok(false);
        }

        if let Some(dsd) = self.dsd {
            decode_dsd_into(
                samples,
                dsd,
                self.header.flags,
                self.header.block_samples as usize,
                dsd_scratch,
            )?;
            let crc = dsd_crc(samples);
            if crc != self.header._crc {
                return decode_error("wavpack: dsd crc mismatch");
            }
            expand_false_stereo(samples, self.header.flags);
            return Ok(true);
        }

        let entropy = self
            .entropy
            .ok_or(Error::DecodeError("wavpack: missing entropy variables"))?;

        let bitstream = self
            .wv_bitstream
            .ok_or(Error::DecodeError("wavpack: missing audio bitstream"))?;

        let mut words = WordsDecoder::new(entropy, self.hybrid_profile, self.header.flags);
        let mut bits = WavPackBitReader::new(bitstream);
        let mut correction_bits = self.wvc_bitstream.map(WavPackBitReader::new);

        words.read_words_into(
            &mut bits,
            correction_bits.as_mut(),
            self.header.block_samples as usize,
            residuals,
        )?;

        if self.wvc_bitstream.is_some() {
            apply_hybrid_correction_into(
                residuals,
                self.header.flags,
                self.header.block_samples as usize,
                self.decorr_passes(),
                self.shaping_info,
                samples,
                decorr_passes,
            )?;
        } else {
            samples.clear();
            samples.reserve(residuals.len());
            samples.extend(residuals.iter().map(|word| word.value));
            apply_decorr_passes(
                samples,
                self.header.flags,
                self.header.block_samples as usize,
                self.decorr_passes(),
            )?;
        }

        fixup_samples(
            samples,
            self.header.flags,
            self.float_info,
            self.int32_info,
            self.wvx_bitstream,
            self.wvx_new_bitstream,
            self.wvc_bitstream.is_some(),
        )?;
        expand_false_stereo(samples, self.header.flags);

        Ok(true)
    }
}
