// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::PTABLE_BINS;

#[derive(Debug)]
pub(super) struct DsdScratch {
    pub(super) probabilities: Vec<u8>,
    pub(super) summed: Vec<u16>,
    pub(super) offsets: Vec<usize>,
    pub(super) lookup: Vec<u8>,
    pub(super) ptable: [i32; PTABLE_BINS],
}

impl Default for DsdScratch {
    fn default() -> Self {
        DsdScratch {
            probabilities: Vec::new(),
            summed: Vec::new(),
            offsets: Vec::new(),
            lookup: Vec::new(),
            ptable: [0; PTABLE_BINS],
        }
    }
}
