// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::FALSE_STEREO;
use super::consts::FINAL_BLOCK;
use super::consts::WAVPACK_MARKER;
use super::consts::WAVPACK_MAX_STREAM_VERSION;
use super::consts::WAVPACK_MIN_CK_SIZE;
use super::consts::WAVPACK_MIN_STREAM_VERSION;
use symphonia_core::errors::{Result, decode_error, unsupported_error};
use symphonia_core::io::{BufReader, ReadBytes};

pub(super) fn expand_false_stereo(samples: &mut Vec<i32>, flags: u32) {
    if flags & FALSE_STEREO == 0 {
        return;
    }

    let old_len = samples.len();
    samples.resize(old_len * 2, 0);

    for i in (0..old_len).rev() {
        let sample = samples[i];
        samples[2 * i] = sample;
        samples[2 * i + 1] = sample;
    }
}

pub(super) fn expand_matroska_packet(data: &[u8], version: u16) -> Result<Vec<u8>> {
    if !(WAVPACK_MIN_STREAM_VERSION..=WAVPACK_MAX_STREAM_VERSION).contains(&version) {
        return unsupported_error("wavpack: unsupported matroska stream version");
    }

    let mut reader = BufReader::new(data);
    let mut out = Vec::new();
    let mut block_samples = None;
    let mut multiple_blocks = false;

    while reader.pos() < data.len() as u64 {
        if data.len().saturating_sub(reader.pos() as usize) < 8 {
            return decode_error("wavpack: truncated matroska block");
        }

        if block_samples.is_none() {
            let samples = reader.read_u32()?;
            block_samples = Some(samples);
        }

        let flags = reader.read_u32()?;

        if out.is_empty() && flags & FINAL_BLOCK == 0 {
            multiple_blocks = true;
        }

        let crc = reader.read_u32()?;

        let block_size = if multiple_blocks {
            if data.len().saturating_sub(reader.pos() as usize) < 4 {
                return decode_error("wavpack: missing matroska block size");
            }

            reader.read_u32()? as usize
        } else {
            data.len() - reader.pos() as usize
        };

        if data.len().saturating_sub(reader.pos() as usize) < block_size {
            return decode_error("wavpack: matroska block overruns packet");
        }

        let block_samples = block_samples.unwrap();
        let ck_size = WAVPACK_MIN_CK_SIZE + block_size as u32;

        out.extend_from_slice(&WAVPACK_MARKER);
        out.extend_from_slice(&ck_size.to_le_bytes());
        out.extend_from_slice(&version.to_le_bytes());
        out.push(0);
        out.push(0);
        out.extend_from_slice(&block_samples.to_le_bytes());
        out.extend_from_slice(&0u32.to_le_bytes());
        out.extend_from_slice(&block_samples.to_le_bytes());
        out.extend_from_slice(&flags.to_le_bytes());
        out.extend_from_slice(&crc.to_le_bytes());
        out.extend_from_slice(&data[reader.pos() as usize..reader.pos() as usize + block_size]);

        reader.ignore_bytes(block_size as u64)?;
    }

    if out.is_empty() {
        return decode_error("wavpack: empty matroska packet");
    }

    Ok(out)
}
