// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::FALSE_STEREO;
use super::consts::MONO_FLAG;

pub(super) fn is_trailing_metadata_marker(marker: [u8; 4]) -> bool {
    marker == *b"APET" || marker[..3] == *b"TAG" || marker[..3] == *b"ID3"
}

pub(super) fn is_mono(flags: u32) -> bool {
    flags & (MONO_FLAG | FALSE_STEREO) != 0
}
