// Symphonia
// Copyright (c) 2019-2026 The Project Symphonia Developers.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#![warn(rust_2018_idioms)]
#![forbid(unsafe_code)]
// The following lints are allowed in all Symphonia crates. Please see clippy.toml for their
// justification.
#![allow(clippy::comparison_chain)]
#![allow(clippy::excessive_precision)]
#![allow(clippy::identity_op)]
#![allow(clippy::manual_range_contains)]

// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

mod apply;
mod consts;
mod decode;
mod decode_block;
mod decorr;
mod dsd_scratch;
mod expand;
mod is;
mod make;
mod misc;
mod parse;
mod predict;
mod read;
mod restore;
mod shape;
mod stream_info;
#[cfg(test)]
mod tests;
mod types;
mod update;
mod wav_pack_bit_reader;
mod wav_pack_block_header;
mod wav_pack_decoder;
mod wav_pack_metadata_iter;
mod wav_pack_reader;
mod words_decoder;
mod wp;
mod write;

pub use wav_pack_decoder::*;
pub use wav_pack_reader::*;
