// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::DSD_FLAG;
use super::stream_info::StreamInfo;
use super::types::WavPackBlock;
use symphonia_core::audio::Channels;
use symphonia_core::codecs::audio::AudioCodecParameters;
use symphonia_core::codecs::audio::well_known::CODEC_ID_WAVPACK;
use symphonia_core::errors::{Error, Result};

pub(super) fn make_channels(count: u16, mask: Option<u32>) -> Channels {
    if let Some(mask) = mask.and_then(symphonia_core::audio::Position::from_wave_channel_mask) {
        Channels::Positioned(mask)
    } else {
        Channels::Discrete(count)
    }
}

pub(super) fn make_codec_params(block: &WavPackBlock) -> Result<AudioCodecParameters> {
    let stream_info = StreamInfo::from_block(block)?;
    let channels = stream_info
        .channels
        .unwrap_or_else(|| block.header.channels_in_block());
    let mut sample_rate = stream_info
        .sample_rate
        .ok_or(Error::Unsupported("wavpack: sample rate is required"))?;
    if block.header.flags & DSD_FLAG != 0 {
        let multiplier = stream_info.dsd_multiplier.unwrap_or(1);
        sample_rate = sample_rate
            .checked_mul(multiplier)
            .and_then(|rate| rate.checked_mul(8))
            .ok_or(Error::DecodeError("wavpack: invalid dsd sample rate"))?;
    }
    let sample_format = block.header.sample_format()?;
    let bits_per_sample = block.header.bits_per_sample();

    let mut params = AudioCodecParameters::new();
    params
        .for_codec(CODEC_ID_WAVPACK)
        .with_sample_rate(sample_rate)
        .with_channels(make_channels(channels, stream_info.channel_mask))
        .with_sample_format(sample_format)
        .with_bits_per_sample(bits_per_sample)
        .with_bits_per_coded_sample(bits_per_sample);

    if block.header.flags & DSD_FLAG != 0 {
        params.with_bits_per_sample(8).with_bits_per_coded_sample(1);
    }

    if block.header.block_samples != 0 {
        params.with_max_frames_per_packet(u64::from(block.header.block_samples));
    }

    if let Some(md5) = stream_info.md5 {
        params.with_verification_code(symphonia_core::codecs::audio::VerificationCheck::Md5(md5));
    }

    Ok(params)
}
