// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use symphonia_core::audio::GenericAudioBuffer;
use symphonia_core::audio::sample::SampleFormat;
use symphonia_core::errors::{Result, decode_error};

pub(super) fn undo_joint_stereo(samples: &mut [i32]) {
    for frame in samples.chunks_exact_mut(2) {
        frame[1] -= frame[0] >> 1;
        frame[0] += frame[1];
    }
}

pub(super) fn dsd_crc(samples: &[i32]) -> u32 {
    let mut crc = 0u32;
    for &sample in samples {
        crc = crc.wrapping_add((crc << 1).wrapping_add((sample as u32) & 0xff));
    }
    crc
}

pub(super) fn prepare_output_buffer(buf: &mut GenericAudioBuffer, frames: usize) -> Result<()> {
    if buf.is_empty() {
        buf.grow_capacity(frames);
        buf.resize_uninit(frames);
    } else if buf.frames() != frames {
        return decode_error("wavpack: packet block duration mismatch");
    }

    Ok(())
}

pub(super) fn generic_buffer_format(buf: &GenericAudioBuffer) -> SampleFormat {
    match buf {
        GenericAudioBuffer::U8(_) => SampleFormat::U8,
        GenericAudioBuffer::U16(_) => SampleFormat::U16,
        GenericAudioBuffer::U24(_) => SampleFormat::U24,
        GenericAudioBuffer::U32(_) => SampleFormat::U32,
        GenericAudioBuffer::S8(_) => SampleFormat::S8,
        GenericAudioBuffer::S16(_) => SampleFormat::S16,
        GenericAudioBuffer::S24(_) => SampleFormat::S24,
        GenericAudioBuffer::S32(_) => SampleFormat::S32,
        GenericAudioBuffer::F32(_) => SampleFormat::F32,
        GenericAudioBuffer::F64(_) => SampleFormat::F64,
    }
}
