// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::HYBRID_BITRATE;
use super::consts::HYBRID_FLAG;
use super::consts::MAX_NTERMS;
use super::consts::MAX_TERM;
use super::consts::MAX_TERM_USIZE;
use super::is::is_mono;
use super::read::read_wp_log_value;
use super::read::read_wp_signed_log_value;
use super::restore::restore_weight;
use super::types::DecorrPass;
use super::types::DsdInfo;
use super::types::EntropyVars;
use super::types::FloatInfo;
use super::types::HybridProfile;
use super::types::Int32Info;
use super::types::ShapingInfo;
use super::wp::wp_exp2s;
use symphonia_core::errors::{Result, decode_error};
use symphonia_core::io::{BufReader, ReadBytes};

pub(super) fn parse_channel_info(data: &[u8]) -> Result<Option<(u16, Option<u32>)>> {
    if data.is_empty() || data.len() > 7 {
        return decode_error("wavpack: invalid channel info");
    }

    let (channels, mask_data) = if data.len() >= 6 {
        let channels = u16::from(data[0]) | (u16::from(data[2] & 0x0f) << 8);
        (channels + 1, &data[3..])
    } else {
        (u16::from(data[0]), &data[1..])
    };

    let mut mask = 0u32;

    for (i, &byte) in mask_data.iter().enumerate() {
        mask |= u32::from(byte) << (i * 8);
    }

    Ok(Some((channels, if mask == 0 { None } else { Some(mask) })))
}

pub(super) fn parse_decorr_terms(
    data: &[u8],
    flags: u32,
    passes: &mut [DecorrPass],
) -> Result<usize> {
    if data.len() > MAX_NTERMS {
        return decode_error("wavpack: too many decorrelation terms");
    }

    if data.len() > passes.len() {
        return decode_error("wavpack: too many decorrelation terms");
    }

    for pass in passes.iter_mut() {
        *pass = DecorrPass::default();
    }

    for (&byte, pass) in data.iter().zip(passes[..data.len()].iter_mut().rev()) {
        let term = (byte & 0x1f) as i8 - 5;
        let delta = (byte >> 5) & 0x7;

        if term == 0
            || term < -3
            || (term > MAX_TERM && term < 17)
            || term > 18
            || (is_mono(flags) && term < 0)
        {
            return decode_error("wavpack: invalid decorrelation term");
        }

        pass.term = term;
        pass.delta = delta;
    }

    Ok(data.len())
}

pub(super) fn parse_decorr_weights(
    data: &[u8],
    flags: u32,
    passes: &mut [DecorrPass],
) -> Result<()> {
    let term_count = if is_mono(flags) {
        data.len()
    } else {
        data.len() / 2
    };

    if term_count > passes.len() || (!is_mono(flags) && data.len() & 1 != 0) {
        return decode_error("wavpack: invalid decorrelation weights");
    }

    for pass in passes.iter_mut() {
        pass.weight_a = 0;
        pass.weight_b = 0;
    }

    let mut weights = data.iter().copied();

    for pass in passes.iter_mut().rev().take(term_count) {
        pass.weight_a = restore_weight(weights.next().unwrap() as i8);

        if !is_mono(flags) {
            pass.weight_b = restore_weight(weights.next().unwrap() as i8);
        }
    }

    Ok(())
}

pub(super) fn parse_entropy_vars(data: &[u8], flags: u32) -> Result<EntropyVars> {
    let expected = if is_mono(flags) { 6 } else { 12 };

    if data.len() != expected {
        return decode_error("wavpack: invalid entropy variables");
    }

    let mut entropy = EntropyVars::default();

    for ch in 0..if is_mono(flags) { 1 } else { 2 } {
        for median in 0..3 {
            let pos = ch * 6 + median * 2;
            let log = u16::from_le_bytes([data[pos], data[pos + 1]]);
            entropy.median[ch][median] = wp_exp2s(i32::from(log)) as u32;
        }
    }

    Ok(entropy)
}

pub(super) fn parse_decorr_samples(
    data: &[u8],
    version: u16,
    flags: u32,
    passes: &mut [DecorrPass],
) -> Result<()> {
    let mono = is_mono(flags);
    let mut reader = BufReader::new(data);

    for pass in passes.iter_mut() {
        pass.samples_a = [0; MAX_TERM_USIZE];
        pass.samples_b = [0; MAX_TERM_USIZE];
    }

    if version == 0x402 && flags & HYBRID_FLAG != 0 {
        reader.read_i16()?;

        if !mono {
            reader.read_i16()?;
        }
    }

    for pass in passes.iter_mut().rev() {
        if reader.pos() == data.len() as u64 {
            break;
        }

        if pass.term > MAX_TERM {
            pass.samples_a[0] = read_wp_signed_log_value(&mut reader)?;
            pass.samples_a[1] = read_wp_signed_log_value(&mut reader)?;

            if !mono {
                pass.samples_b[0] = read_wp_signed_log_value(&mut reader)?;
                pass.samples_b[1] = read_wp_signed_log_value(&mut reader)?;
            }
        } else if pass.term < 0 {
            pass.samples_a[0] = read_wp_signed_log_value(&mut reader)?;
            pass.samples_b[0] = read_wp_signed_log_value(&mut reader)?;
        } else {
            for sample in 0..pass.term as usize {
                pass.samples_a[sample] = read_wp_signed_log_value(&mut reader)?;

                if !mono {
                    pass.samples_b[sample] = read_wp_signed_log_value(&mut reader)?;
                }
            }
        }
    }

    if reader.pos() != data.len() as u64 {
        return decode_error("wavpack: invalid decorrelation samples");
    }

    Ok(())
}

pub(super) fn parse_hybrid_profile(data: &[u8], flags: u32) -> Result<HybridProfile> {
    let mono = is_mono(flags);
    let mut reader = BufReader::new(data);
    let mut profile = HybridProfile::default();

    if flags & HYBRID_BITRATE != 0 {
        profile.slow_level[0] = read_wp_log_value(&mut reader)? as u32;

        if !mono {
            profile.slow_level[1] = read_wp_log_value(&mut reader)? as u32;
        }
    }

    profile.bitrate_acc[0] = u32::from(reader.read_u16()?) << 16;

    if !mono {
        profile.bitrate_acc[1] = u32::from(reader.read_u16()?) << 16;
    }

    if reader.pos() < data.len() as u64 {
        profile.bitrate_delta[0] = read_wp_signed_log_value(&mut reader)? as u32;

        if !mono {
            profile.bitrate_delta[1] = read_wp_signed_log_value(&mut reader)? as u32;
        }
    }

    if reader.pos() != data.len() as u64 {
        return decode_error("wavpack: invalid hybrid profile");
    }

    Ok(profile)
}

pub(super) fn parse_shaping_info(data: &[u8], flags: u32) -> Result<ShapingInfo> {
    let mono = is_mono(flags);
    let mut info = ShapingInfo::default();

    if data.len() == 2 {
        info.shaping_acc[0] = restore_weight(data[0] as i8) << 16;
        info.shaping_acc[1] = restore_weight(data[1] as i8) << 16;
        return Ok(info);
    }

    let expected = if mono { 4 } else { 8 };
    let expected_with_delta = if mono { 6 } else { 12 };

    if data.len() < expected {
        return decode_error("wavpack: invalid shaping info");
    }

    let mut reader = BufReader::new(data);
    info.error[0] = read_wp_signed_log_value(&mut reader)?;
    info.shaping_acc[0] = read_wp_signed_log_value(&mut reader)?;

    if !mono {
        info.error[1] = read_wp_signed_log_value(&mut reader)?;
        info.shaping_acc[1] = read_wp_signed_log_value(&mut reader)?;
    }

    if data.len() == expected_with_delta {
        info.shaping_delta[0] = read_wp_signed_log_value(&mut reader)?;

        if !mono {
            info.shaping_delta[1] = read_wp_signed_log_value(&mut reader)?;
        }
    }

    Ok(info)
}

pub(super) fn parse_four_byte_info(data: &[u8], kind: &'static str) -> Result<[u8; 4]> {
    if data.len() != 4 {
        return match kind {
            "float" => decode_error("wavpack: invalid float info"),
            "int32" => decode_error("wavpack: invalid int32 info"),
            _ => decode_error("wavpack: invalid metadata info"),
        };
    }

    let mut info = [0; 4];
    info.copy_from_slice(data);
    Ok(info)
}

pub(super) fn parse_int32_info(data: &[u8]) -> Result<Int32Info> {
    let info = parse_four_byte_info(data, "int32")?;

    Ok(Int32Info {
        sent_bits: u32::from(info[0]) & 0x1f,
        zeros: u32::from(info[1]) & 0x1f,
        ones: u32::from(info[2]) & 0x1f,
        dups: u32::from(info[3]) & 0x1f,
    })
}

pub(super) fn parse_float_info(data: &[u8]) -> Result<FloatInfo> {
    let info = parse_four_byte_info(data, "float")?;

    Ok(FloatInfo {
        flags: info[0],
        shift: info[1],
        max_exp: info[2],
        _norm_exp: info[3],
    })
}

pub(super) fn parse_dsd_info(data: &[u8]) -> Result<DsdInfo<'_>> {
    if data.len() < 2 {
        return decode_error("wavpack: invalid dsd block");
    }

    let multiplier_pow = data[0];
    if multiplier_pow > 31 {
        return decode_error("wavpack: invalid dsd multiplier");
    }

    Ok(DsdInfo {
        multiplier_pow,
        mode: data[1],
        payload: &data[2..],
    })
}
