// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_weight;
use super::consts::MAX_TERM;
use super::types::DecorrPass;

pub(super) fn predict_term_17(prev: i32, older: i32) -> i32 {
    prev.wrapping_mul(2).wrapping_sub(older)
}

pub(super) fn predict_term_18(prev: i32, older: i32) -> i32 {
    prev.wrapping_mul(3).wrapping_sub(older) >> 1
}

pub(super) fn predict_term_18_stereo(prev: i32, older: i32) -> i32 {
    prev.wrapping_add(prev.wrapping_sub(older) >> 1)
}

pub(super) fn preview_corrected_stereo_sample(
    pass: &DecorrPass,
    mut left: i32,
    mut right: i32,
    m: usize,
) -> (i32, i32) {
    if pass.term > 0 {
        let (sam_a, sam_b) = if pass.term > MAX_TERM {
            if pass.term & 1 != 0 {
                (
                    predict_term_17(pass.samples_a[0], pass.samples_a[1]),
                    predict_term_17(pass.samples_b[0], pass.samples_b[1]),
                )
            } else {
                (
                    predict_term_18(pass.samples_a[0], pass.samples_a[1]),
                    predict_term_18(pass.samples_b[0], pass.samples_b[1]),
                )
            }
        } else {
            (pass.samples_a[m], pass.samples_b[m])
        };

        left = left.wrapping_add(apply_weight(pass.weight_a, sam_a));
        right = right.wrapping_add(apply_weight(pass.weight_b, sam_b));
    } else if pass.term == -1 {
        left = left.wrapping_add(apply_weight(pass.weight_a, pass.samples_a[0]));
        right = right.wrapping_add(apply_weight(pass.weight_b, left));
    } else {
        right = right.wrapping_add(apply_weight(pass.weight_b, pass.samples_b[0]));

        if pass.term == -3 {
            left = left.wrapping_add(apply_weight(pass.weight_a, pass.samples_a[0]));
        } else {
            left = left.wrapping_add(apply_weight(pass.weight_a, right));
        }
    }

    (left, right)
}
