// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::WAVPACK_HEADER_LEN;
use super::consts::WAVPACK_HEADER_REST_LEN;
use super::consts::WAVPACK_MARKER;
use super::is::is_trailing_metadata_marker;
use super::types::WavPackBlock;
use super::wav_pack_block_header::WavPackBlockHeader;
use super::wp::wp_exp2s;
use std::io::ErrorKind;
use symphonia_core::errors::{Result, decode_error};
use symphonia_core::io::{BufReader, MediaSourceStream, ReadBytes};

pub(super) fn read_block_with_marker(
    reader: &mut MediaSourceStream<'_>,
    marker: [u8; 4],
) -> Result<WavPackBlock> {
    if marker != WAVPACK_MARKER {
        return decode_error("wavpack: invalid block marker");
    }

    let mut data = Vec::with_capacity(WAVPACK_HEADER_LEN);
    data.extend_from_slice(&marker);
    data.extend_from_slice(&reader.read_boxed_slice_exact(WAVPACK_HEADER_REST_LEN)?);

    let header = WavPackBlockHeader::parse(&data)?;
    let body = reader.read_boxed_slice_exact(header.body_len())?;
    data.extend_from_slice(&body);

    Ok(WavPackBlock {
        header,
        data: data.into_boxed_slice(),
    })
}

pub(super) fn read_block_header_with_marker(
    reader: &mut MediaSourceStream<'_>,
    marker: [u8; 4],
) -> Result<WavPackBlockHeader> {
    if marker != WAVPACK_MARKER {
        return decode_error("wavpack: invalid block marker");
    }

    let mut data = [0u8; WAVPACK_HEADER_LEN];
    data[..4].copy_from_slice(&marker);
    reader.read_buf_exact(&mut data[4..])?;
    WavPackBlockHeader::parse(&data)
}

pub(super) fn read_block(reader: &mut MediaSourceStream<'_>) -> Result<Option<WavPackBlock>> {
    let marker = match reader.read_quad_bytes() {
        Ok(marker) => marker,
        Err(err) if err.kind() == ErrorKind::UnexpectedEof => return Ok(None),
        Err(err) => return Err(err.into()),
    };

    if is_trailing_metadata_marker(marker) {
        return Ok(None);
    }

    read_block_with_marker(reader, marker).map(Some)
}

pub(super) fn read_wp_log_value(reader: &mut BufReader<'_>) -> Result<i32> {
    Ok(wp_exp2s(i32::from(reader.read_u16()?)))
}

pub(super) fn read_wp_signed_log_value(reader: &mut BufReader<'_>) -> Result<i32> {
    Ok(wp_exp2s(i32::from(reader.read_i16()?)))
}
