// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_int32_redundancy;
use super::consts::FLOAT_NEG_ZEROS;
use super::consts::FLOAT_SHIFT_ONES;
use super::consts::FLOAT_SHIFT_SAME;
use super::consts::FLOAT_SHIFT_SENT;
use super::consts::FLOAT_ZEROS_SENT;
use super::types::FloatInfo;
use super::types::Int32Info;
use super::wav_pack_bit_reader::WavPackBitReader;
use symphonia_core::errors::Result;

pub(super) fn restore_weight(weight: i8) -> i32 {
    let mut result = i32::from(weight) * 8;

    if result > 0 {
        result += (result + 64) >> 7;
    }

    result
}

pub(super) fn restore_int32_low_bits(
    samples: &mut [i32],
    info: Int32Info,
    wvx_bitstream: &[u8],
    wvx_new_bitstream: bool,
) -> Result<()> {
    let mut bits = WavPackBitReader::new(wvx_bitstream);
    let max_width = if wvx_new_bitstream {
        bits.read_bits(5)? & 0x1f
    } else {
        0
    };
    let mask = (1u32 << info.sent_bits) - 1;

    for sample in samples {
        if info.sent_bits != 0 {
            if max_width != 0 {
                let pvalue = if *sample < 0 { !*sample } else { *sample } as u32;
                let width = if pvalue == 0 {
                    0
                } else {
                    32 - pvalue.leading_zeros()
                };
                let mut bits_to_read = info.sent_bits as i32;
                bits_to_read -= (width + info.sent_bits).saturating_sub(max_width) as i32;

                if bits_to_read > 0 {
                    let bits_to_read = bits_to_read as u32;
                    let data = bits.read_bits(bits_to_read)? & ((1u32 << bits_to_read) - 1);
                    *sample = (((*sample as u32) << bits_to_read) | data)
                        .wrapping_shl(info.sent_bits - bits_to_read)
                        as i32;
                } else {
                    *sample = ((*sample as u32) << info.sent_bits) as i32;
                }
            } else {
                let data = bits.read_bits(info.sent_bits)? & mask;
                *sample = (((*sample as u32) << info.sent_bits) | data) as i32;
            }
        }

        apply_int32_redundancy(sample, info.zeros, info.ones, info.dups);
    }

    Ok(())
}

pub(super) fn restore_float_values(
    samples: &mut [i32],
    info: FloatInfo,
    wvx_bitstream: Option<&[u8]>,
    wvx_new_bitstream: bool,
) -> Result<()> {
    if let Some(wvx_bitstream) = wvx_bitstream {
        restore_float_values_wvx(samples, info, wvx_bitstream, wvx_new_bitstream)
    } else {
        restore_float_values_nowvx(samples, info);
        Ok(())
    }
}

pub(super) fn restore_float_values_nowvx(samples: &mut [i32], info: FloatInfo) {
    for sample in samples {
        let mut value = *sample;
        let mut out = 0u32;

        if value != 0 {
            let mut shift_count = 0;
            let mut exp = info.max_exp;
            value = ((value as u32) << (u32::from(info.shift) & 0x1f)) as i32;

            if value < 0 {
                value = value.wrapping_neg();
                out |= 1 << 31;
            }

            let mut mag = value as u32;

            if mag >= 0x1000000 {
                while mag & 0x0f00_0000 != 0 {
                    mag >>= 1;
                    exp = exp.wrapping_add(1);
                }
            } else if exp != 0 {
                while mag & 0x800000 == 0 && exp != 0 {
                    exp = exp.wrapping_sub(1);
                    if exp == 0 {
                        break;
                    }
                    shift_count += 1;
                    mag <<= 1;
                }

                shift_count &= 0x1f;
                if shift_count != 0 && info.flags & FLOAT_SHIFT_ONES != 0 {
                    mag |= (1u32 << shift_count) - 1;
                }
            }

            out |= mag & 0x7fffff;
            out |= u32::from(exp) << 23;
        }

        *sample = out as i32;
    }
}

pub(super) fn restore_float_values_wvx(
    samples: &mut [i32],
    info: FloatInfo,
    wvx_bitstream: &[u8],
    wvx_new_bitstream: bool,
) -> Result<()> {
    let mut bits = WavPackBitReader::new(wvx_bitstream);
    let (min_shifted_zeros, max_shifted_ones) = if wvx_new_bitstream {
        (bits.read_bits(5)? & 0x1f, bits.read_bits(5)? & 0x1f)
    } else {
        (0, 0)
    };

    for sample in samples {
        let mut value = *sample;
        let mut out = 0u32;
        let mut exp = u32::from(info.max_exp);

        if value == 0 {
            if info.flags & FLOAT_ZEROS_SENT != 0 {
                if bits.read_bit()? != 0 {
                    let mantissa = bits.read_bits(23)?;
                    out |= mantissa & 0x7fffff;

                    if exp >= 25 {
                        exp = bits.read_bits(8)?;
                    }

                    out |= (bits.read_bit()? & 1) << 31;
                } else if info.flags & FLOAT_NEG_ZEROS != 0 {
                    out |= (bits.read_bit()? & 1) << 31;
                }
            }
        } else {
            value = ((value as u32) << (u32::from(info.shift) & 0x1f)) as i32;

            if value < 0 {
                value = value.wrapping_neg();
                out |= 1 << 31;
            }

            let mut mag = value as u32;

            if mag == 0x1000000 {
                if bits.read_bit()? != 0 {
                    out |= bits.read_bits(23)? & 0x7fffff;
                }

                exp = 255;
            } else {
                let mut shift_count = 0;

                if exp != 0 {
                    while mag & 0x800000 == 0 && exp != 0 {
                        exp -= 1;
                        if exp == 0 {
                            break;
                        }
                        shift_count += 1;
                        mag <<= 1;
                    }
                }

                shift_count &= 0x1f;

                if shift_count != 0 {
                    if info.flags & FLOAT_SHIFT_ONES != 0
                        || (info.flags & FLOAT_SHIFT_SAME != 0 && bits.read_bit()? != 0)
                    {
                        mag |= (1u32 << shift_count) - 1;
                    } else if info.flags & FLOAT_SHIFT_SENT != 0 {
                        let mask = (1u32 << shift_count) - 1;
                        let mut num_zeros = 0;

                        if max_shifted_ones != 0 && shift_count > max_shifted_ones {
                            num_zeros = shift_count - max_shifted_ones;
                        }

                        if min_shifted_zeros > num_zeros {
                            num_zeros = if min_shifted_zeros > shift_count {
                                shift_count
                            } else {
                                min_shifted_zeros
                            };
                        }

                        shift_count -= num_zeros;

                        if shift_count > 0 {
                            let data = bits.read_bits(shift_count)?;
                            mag |= (data << num_zeros) & mask;
                        }
                    }
                }

                out |= mag & 0x7fffff;
            }

            out |= (exp & 0xff) << 23;
        }

        *sample = out as i32;
    }

    Ok(())
}
