// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_weight;
use super::consts::HYBRID_SHAPE;
use super::consts::NEW_SHAPING;
use super::types::ShapingInfo;

pub(super) fn shape_hybrid_sample(
    flags: u32,
    shaping: &mut ShapingInfo,
    channel: usize,
    lossy: i32,
    correction: i32,
) -> i32 {
    if flags & HYBRID_SHAPE == 0 {
        return lossy.wrapping_add(correction);
    }

    let corrected = lossy.wrapping_add(correction);
    shape_corrected_output(flags, shaping, channel, lossy, corrected)
}

pub(super) fn shape_corrected_output(
    flags: u32,
    shaping: &mut ShapingInfo,
    channel: usize,
    _lossy: i32,
    corrected: i32,
) -> i32 {
    let correction = corrected.wrapping_sub(_lossy);
    let shaping_acc = shaping.shaping_acc[channel].wrapping_add(shaping.shaping_delta[channel]);
    shaping.shaping_acc[channel] = shaping_acc;

    let shaping_weight = shaping_acc >> 16;
    let mut temp = apply_weight(shaping_weight, shaping.error[channel]).wrapping_neg();

    if flags & NEW_SHAPING != 0 && shaping_weight < 0 && temp != 0 {
        if temp == shaping.error[channel] {
            temp = if temp < 0 {
                temp.wrapping_add(1)
            } else {
                temp.wrapping_sub(1)
            };
        }

        shaping.error[channel] = temp.wrapping_sub(correction);
    } else {
        shaping.error[channel] = correction.wrapping_neg();
    }

    corrected.wrapping_sub(temp)
}
