// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::ID_CHANNEL_INFO;
use super::consts::ID_DSD_BLOCK;
use super::consts::ID_MD5_CHECKSUM;
use super::consts::ID_SAMPLE_RATE;
use super::parse::parse_channel_info;
use super::parse::parse_dsd_info;
use super::types::WavPackBlock;
use super::wav_pack_metadata_iter::WavPackMetadataIter;
use symphonia_core::errors::Result;

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct StreamInfo {
    pub(super) sample_rate: Option<u32>,
    pub(super) channels: Option<u16>,
    pub(super) channel_mask: Option<u32>,
    pub(super) md5: Option<[u8; 16]>,
    pub(super) dsd_multiplier: Option<u32>,
}

impl StreamInfo {
    pub(super) fn from_block(block: &WavPackBlock) -> Result<Self> {
        let mut info = StreamInfo {
            sample_rate: block.header.sample_rate_from_flags(),
            channels: Some(block.header.output_channels_in_block() as u16),
            channel_mask: None,
            md5: None,
            dsd_multiplier: None,
        };

        for metadata in WavPackMetadataIter::new(block) {
            let metadata = metadata?;

            match metadata.id {
                ID_SAMPLE_RATE => {
                    if matches!(metadata.data.len(), 3 | 4) {
                        let mut sample_rate = u32::from(metadata.data[0])
                            | (u32::from(metadata.data[1]) << 8)
                            | (u32::from(metadata.data[2]) << 16);

                        if metadata.data.len() == 4 {
                            sample_rate |= (u32::from(metadata.data[3]) & 0x7f) << 24;
                        }

                        info.sample_rate = Some(sample_rate);
                    }
                }
                ID_CHANNEL_INFO => {
                    if let Some((channels, mask)) = parse_channel_info(metadata.data)? {
                        info.channels = Some(channels);
                        info.channel_mask = mask;
                    }
                }
                ID_MD5_CHECKSUM if metadata.data.len() == 16 => {
                    let mut md5 = [0; 16];
                    md5.copy_from_slice(metadata.data);
                    info.md5 = Some(md5);
                }
                ID_DSD_BLOCK => {
                    let dsd = parse_dsd_info(metadata.data)?;
                    info.dsd_multiplier =
                        Some(1u32.checked_shl(u32::from(dsd.multiplier_pow)).unwrap_or(0));
                }
                _ => (),
            }
        }

        Ok(info)
    }
}
