// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::apply::apply_decorr_passes;
use super::apply::apply_hybrid_correction_into;
use super::consts::DSD_FLAG;
use super::consts::FALSE_STEREO;
use super::consts::FINAL_BLOCK;
use super::consts::FLOAT_DATA;
use super::consts::HYBRID_BITRATE;
use super::consts::HYBRID_FLAG;
use super::consts::HYBRID_SHAPE;
use super::consts::ID_CHANNEL_INFO;
use super::consts::ID_DSD_BLOCK;
use super::consts::ID_ODD_SIZE;
use super::consts::INITIAL_BLOCK;
use super::consts::INT32_DATA;
use super::consts::JOINT_STEREO;
use super::consts::MONO_FLAG;
use super::consts::RATE_S;
use super::consts::SHIFT_LSB;
use super::consts::SRATE_LSB;
use super::consts::fixup_samples;
use super::decode::decode_dsd_into;
use super::dsd_scratch::DsdScratch;
use super::expand::expand_false_stereo;
use super::make::make_codec_params;
use super::misc::dsd_crc;
use super::parse::parse_decorr_samples;
use super::parse::parse_dsd_info;
use super::parse::parse_hybrid_profile;
use super::parse::parse_shaping_info;
use super::restore::restore_weight;
use super::types::DecodedWord;
use super::types::DecorrPass;
use super::types::FloatInfo;
use super::types::Int32Info;
use super::types::ShapingInfo;
use super::wav_pack_decoder::WavPackDecoder;
use super::wp::wp_exp2s;
use super::write::write_samples_to_buffer;
use symphonia_core::audio::sample::SampleFormat;
use symphonia_core::audio::{AudioSpec, Channels, GenericAudioBuffer};
use symphonia_core::codecs::audio::AudioDecoder;
use symphonia_core::errors::{Error, Result};
use symphonia_core::formats::prelude::*;
use symphonia_core::units::{Duration, Timestamp};

mod make;
mod misc;

use make::make_test_block;
use make::make_test_block_with_crc;
use misc::parse_test_block;

#[cfg(test)]
fn apply_hybrid_correction(
    residuals: &[DecodedWord],
    flags: u32,
    sample_count: usize,
    passes: &[DecorrPass],
    shaping_info: Option<ShapingInfo>,
) -> Result<Vec<i32>> {
    let mut samples = Vec::new();
    let mut decorr_passes = Vec::new();
    apply_hybrid_correction_into(
        residuals,
        flags,
        sample_count,
        passes,
        shaping_info,
        &mut samples,
        &mut decorr_passes,
    )?;
    Ok(samples)
}

#[test]
fn wavpack_exp2s_matches_reference_values() {
    assert_eq!(wp_exp2s(0), 0);
    assert_eq!(wp_exp2s(0x100), 1);
    assert_eq!(wp_exp2s(0x200), 2);
    assert_eq!(wp_exp2s(-0x200), -2);
    assert_eq!(restore_weight(64), 516);
}

#[test]
fn wavpack_decorr_samples_parse_mono_history() {
    let mut passes = vec![DecorrPass {
        term: 2,
        ..Default::default()
    }];

    parse_decorr_samples(&[0, 1, 0, 0xfe], 0x410, MONO_FLAG, &mut passes).unwrap();

    assert_eq!(passes[0].samples_a[0], 1);
    assert_eq!(passes[0].samples_a[1], -2);
}

#[test]
fn wavpack_decorr_mono_pass_reconstructs_predictive_samples() {
    let pass = DecorrPass {
        term: 1,
        weight_a: 512,
        samples_a: [10, 0, 0, 0, 0, 0, 0, 0],
        ..Default::default()
    };
    let mut samples = vec![1, 2, 3];

    apply_decorr_passes(&mut samples, MONO_FLAG, 3, &[pass]).unwrap();

    assert_eq!(samples, vec![6, 5, 6]);
}

#[test]
fn wavpack_decorr_stereo_negative_term_reconstructs_cross_channel_samples() {
    let pass = DecorrPass {
        term: -1,
        weight_a: 512,
        weight_b: 512,
        samples_a: [10, 0, 0, 0, 0, 0, 0, 0],
        ..Default::default()
    };
    let mut samples = vec![2, 4];

    apply_decorr_passes(&mut samples, 0, 1, &[pass]).unwrap();

    assert_eq!(samples, vec![7, 8]);
}

#[test]
fn wavpack_joint_stereo_reconstructs_left_right() {
    let mut samples = vec![10, 3, -9, 4];

    apply_decorr_passes(&mut samples, JOINT_STEREO, 2, &[]).unwrap();

    assert_eq!(samples, vec![8, -2, 0, 9]);
}

#[test]
fn wavpack_fixup_applies_final_shift() {
    let mut samples = vec![1, -2];

    fixup_samples(&mut samples, 2 << SHIFT_LSB, None, None, None, false, false).unwrap();

    assert_eq!(samples, vec![4, -8]);
}

#[test]
fn wavpack_fixup_restores_int32_redundant_bits() {
    let mut zeros = vec![3, -3];
    let mut ones = vec![3, -3];
    let mut dups = vec![2, 3];

    fixup_samples(
        &mut zeros,
        INT32_DATA,
        None,
        Some(Int32Info {
            zeros: 1,
            ..Default::default()
        }),
        None,
        false,
        false,
    )
    .unwrap();
    fixup_samples(
        &mut ones,
        INT32_DATA,
        None,
        Some(Int32Info {
            ones: 2,
            ..Default::default()
        }),
        None,
        false,
        false,
    )
    .unwrap();
    fixup_samples(
        &mut dups,
        INT32_DATA,
        None,
        Some(Int32Info {
            dups: 3,
            ..Default::default()
        }),
        None,
        false,
        false,
    )
    .unwrap();

    assert_eq!(zeros, vec![6, -6]);
    assert_eq!(ones, vec![15, -9]);
    assert_eq!(dups, vec![16, 31]);
}

#[test]
fn wavpack_float_fixup_restores_ieee_bits_without_wvx() {
    let mut samples = vec![0x800000, -0x800000, 0x1000000];
    let float = FloatInfo {
        max_exp: 127,
        ..Default::default()
    };

    fixup_samples(
        &mut samples,
        FLOAT_DATA,
        Some(float),
        None,
        None,
        false,
        false,
    )
    .unwrap();

    assert_eq!(samples[0] as u32, 1.0f32.to_bits());
    assert_eq!(samples[1] as u32, (-1.0f32).to_bits());
    assert_eq!(samples[2] as u32, 2.0f32.to_bits());
}

#[test]
fn wavpack_false_stereo_duplicates_mono_samples() {
    let mut samples = vec![1, -2, 3];

    expand_false_stereo(&mut samples, FALSE_STEREO);

    assert_eq!(samples, vec![1, 1, -2, -2, 3, 3]);
}

#[test]
fn wavpack_output_writer_fills_planar_integer_buffer() {
    let mut buf = GenericAudioBuffer::new(
        SampleFormat::S16,
        AudioSpec::new(44100, Channels::Discrete(2)),
        0,
    );

    write_samples_to_buffer(&mut buf, &[1, 2], 2, 1, 0).unwrap();
    write_samples_to_buffer(&mut buf, &[3, 4], 2, 1, 1).unwrap();

    let mut interleaved = Vec::<i16>::new();
    buf.copy_to_vec_interleaved(&mut interleaved);

    assert_eq!(interleaved, vec![1, 3, 2, 4]);
}

#[test]
fn wavpack_stream_info_accepts_ten_channel_float_blocks() {
    let flags = FLOAT_DATA | 3 | (8 << SRATE_LSB);
    let block = parse_test_block(&make_test_block(
        flags,
        Some(1),
        1,
        &[ID_CHANNEL_INFO | ID_ODD_SIZE, 1, 10, 0],
    ));
    let params = make_codec_params(&block).unwrap();

    assert!(matches!(params.sample_format, Some(SampleFormat::F32)));
    assert_eq!(params.sample_rate, Some(32000));
    assert_eq!(params.channels.unwrap().count(), 10);
}

#[test]
fn wavpack_dsd_mode0_decodes_packed_bytes() {
    let dsd = parse_dsd_info(&[0, 0, 0xAA, 0x55]).unwrap();
    let mut out = Vec::new();
    let mut scratch = DsdScratch::default();

    decode_dsd_into(&mut out, dsd, MONO_FLAG | DSD_FLAG, 2, &mut scratch).unwrap();

    assert_eq!(out, vec![0xAA, 0x55]);
}

#[test]
fn wavpack_dsd_mode1_decodes_minimal_fixture() {
    let mut payload = Vec::new();
    payload.push(0); // history bits.
    payload.push(0xff); // raw probability table follows.
    payload.push(1); // bin0 value 0 probability.
    payload.extend(std::iter::repeat_n(0u8, 255));
    payload.extend_from_slice(&[0, 0, 0, 0]); // initial range value.
    let mut md = vec![0, 1];
    md.extend_from_slice(&payload);

    let dsd = parse_dsd_info(&md).unwrap();
    let mut out = Vec::new();
    let mut scratch = DsdScratch::default();
    decode_dsd_into(&mut out, dsd, MONO_FLAG | DSD_FLAG, 1, &mut scratch).unwrap();

    assert_eq!(out, vec![0]);
}

#[test]
fn wavpack_dsd_mode3_decodes_minimal_fixture() {
    let mut payload = Vec::new();
    payload.push(0); // rate_i
    payload.push(RATE_S); // rate_s
    payload.extend_from_slice(&[0, 0, 0, 0, 0, 0, 0]); // filter state + factor
    payload.extend_from_slice(&[0, 0, 0, 0]); // initial range value
    payload.extend(std::iter::repeat_n(0u8, 16)); // extra bytes for renorm
    let mut md = vec![0, 3];
    md.extend_from_slice(&payload);

    let dsd = parse_dsd_info(&md).unwrap();
    let mut out = Vec::new();
    let mut scratch = DsdScratch::default();
    decode_dsd_into(&mut out, dsd, MONO_FLAG | DSD_FLAG, 1, &mut scratch).unwrap();

    assert_eq!(out, vec![0xFF]);
}

#[test]
fn wavpack_dsd_codec_params_scale_sample_rate() {
    let flags = DSD_FLAG | MONO_FLAG | (9 << SRATE_LSB);
    let block = parse_test_block(&make_test_block(
        flags | INITIAL_BLOCK | FINAL_BLOCK,
        Some(1),
        1,
        &[ID_DSD_BLOCK | ID_ODD_SIZE, 2, 1, 0, 0xAA, 0],
    ));
    let params = make_codec_params(&block).unwrap();

    assert!(matches!(params.sample_format, Some(SampleFormat::U8)));
    assert_eq!(params.sample_rate, Some(44100 * 2 * 8));
    assert_eq!(params.bits_per_coded_sample, Some(1));
}

#[test]
fn wavpack_decoder_rejects_dsd_crc_mismatch() {
    let flags = DSD_FLAG | MONO_FLAG | INITIAL_BLOCK | FINAL_BLOCK | (9 << SRATE_LSB);
    let body = [ID_DSD_BLOCK | ID_ODD_SIZE, 2, 1, 0, 0xAA, 0];
    let data = make_test_block_with_crc(flags, Some(1), 1, 0, &body);
    let block = parse_test_block(&data);
    let params = make_codec_params(&block).unwrap();
    let mut decoder = WavPackDecoder::try_new(&params, &Default::default()).unwrap();
    let packet = Packet::new(
        0,
        Timestamp::new(0),
        Duration::from(1u64),
        data.into_boxed_slice(),
    );

    assert!(matches!(
        decoder.decode_ref(&packet.as_packet_ref()),
        Err(Error::DecodeError(_))
    ));
}

#[test]
fn wavpack_decoder_accepts_dsd_crc_match() {
    let flags = DSD_FLAG | MONO_FLAG | INITIAL_BLOCK | FINAL_BLOCK | (9 << SRATE_LSB);
    let body = [ID_DSD_BLOCK | ID_ODD_SIZE, 2, 1, 0, 0xAA, 0];
    let data = make_test_block_with_crc(flags, Some(1), 1, dsd_crc(&[0xAA]), &body);
    let block = parse_test_block(&data);
    let params = make_codec_params(&block).unwrap();
    let mut decoder = WavPackDecoder::try_new(&params, &Default::default()).unwrap();
    let packet = Packet::new(
        0,
        Timestamp::new(0),
        Duration::from(1u64),
        data.into_boxed_slice(),
    );

    assert!(decoder.decode_ref(&packet.as_packet_ref()).is_ok());
}

#[test]
fn wavpack_hybrid_profile_parses_mono_bitrate_state() {
    let profile = parse_hybrid_profile(
        &[0, 1, 2, 0, 0, 2],
        MONO_FLAG | HYBRID_FLAG | HYBRID_BITRATE,
    )
    .unwrap();

    assert_eq!(profile.slow_level[0], 1);
    assert_eq!(profile.bitrate_acc[0], 2 << 16);
    assert_eq!(profile.bitrate_delta[0], 2);
}

#[test]
fn wavpack_shaping_info_parses_accumulators_and_deltas() {
    let shaping = parse_shaping_info(
        &[
            0, 1, // error[0].
            0, 2, // shaping_acc[0].
            0, 3, // shaping_delta[0].
        ],
        MONO_FLAG | HYBRID_FLAG | HYBRID_SHAPE,
    )
    .unwrap();

    assert_eq!(shaping.error[0], 1);
    assert_eq!(shaping.shaping_acc[0], 2);
    assert_eq!(shaping.shaping_delta[0], 4);

    let shaping = parse_shaping_info(&[64, 0], HYBRID_FLAG | HYBRID_SHAPE).unwrap();

    assert_eq!(shaping.shaping_acc[0], 516 << 16);
    assert_eq!(shaping.shaping_acc[1], 0);
}

#[test]
fn wavpack_hybrid_correction_reconstructs_mono_samples() {
    let residuals = vec![
        DecodedWord {
            value: 10,
            correction: 3,
        },
        DecodedWord {
            value: -4,
            correction: -2,
        },
    ];

    assert_eq!(
        apply_hybrid_correction(&residuals, MONO_FLAG | HYBRID_FLAG, 2, &[], None).unwrap(),
        vec![13, -6]
    );
}

#[test]
fn wavpack_hybrid_correction_reconstructs_joint_stereo() {
    let residuals = vec![
        DecodedWord {
            value: 10,
            correction: 2,
        },
        DecodedWord {
            value: 4,
            correction: -1,
        },
    ];

    assert_eq!(
        apply_hybrid_correction(&residuals, HYBRID_FLAG | JOINT_STEREO, 1, &[], None).unwrap(),
        vec![9, -3]
    );
}
