// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::MAX_TERM_USIZE;
use super::wav_pack_block_header::WavPackBlockHeader;
use symphonia_core::units::{Duration, Timestamp};

#[derive(Clone, Debug)]
pub(super) struct WavPackBlock {
    pub(super) header: WavPackBlockHeader,
    pub(super) data: Box<[u8]>,
}

pub(super) type WavPackPacketBlocks = (Timestamp, Duration, Box<[u8]>);

#[derive(Debug)]
pub(super) struct WavPackMetadata<'a> {
    pub(super) id: u8,
    pub(super) data: &'a [u8],
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct DecorrPass {
    pub(super) term: i8,
    pub(super) delta: u8,
    pub(super) weight_a: i32,
    pub(super) weight_b: i32,
    pub(super) samples_a: [i32; MAX_TERM_USIZE],
    pub(super) samples_b: [i32; MAX_TERM_USIZE],
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct EntropyVars {
    pub(super) median: [[u32; 3]; 2],
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct HybridProfile {
    pub(super) slow_level: [u32; 2],
    pub(super) bitrate_acc: [u32; 2],
    pub(super) bitrate_delta: [u32; 2],
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub(super) struct ShapingInfo {
    pub(super) error: [i32; 2],
    pub(super) shaping_acc: [i32; 2],
    pub(super) shaping_delta: [i32; 2],
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub(super) struct DecodedWord {
    pub(super) value: i32,
    pub(super) correction: i32,
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct Int32Info {
    pub(super) sent_bits: u32,
    pub(super) zeros: u32,
    pub(super) ones: u32,
    pub(super) dups: u32,
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct FloatInfo {
    pub(super) flags: u8,
    pub(super) shift: u8,
    pub(super) max_exp: u8,
    pub(super) _norm_exp: u8,
}

#[derive(Copy, Clone, Debug)]
pub(super) struct DsdInfo<'a> {
    pub(super) multiplier_pow: u8,
    pub(super) mode: u8,
    pub(super) payload: &'a [u8],
}

#[derive(Copy, Clone, Debug, Default)]
pub(super) struct DsdFilterState {
    pub(super) byte: u8,
    pub(super) factor: i32,
    pub(super) filter1: i32,
    pub(super) filter2: i32,
    pub(super) filter3: i32,
    pub(super) filter4: i32,
    pub(super) filter5: i32,
    pub(super) filter6: i32,
    pub(super) value: i32,
}
