// Auto-generated by r2factor. Manual edits will be overwritten on next split.

pub(super) fn update_weight(weight: &mut i32, delta: u8, source: i32, result: i32) {
    if source != 0 && result != 0 {
        let s = (source ^ result) >> 31;
        *weight = (i32::from(delta) ^ s) + (*weight - s);
    }
}

pub(super) fn update_weight_clip(weight: &mut i32, delta: u8, source: i32, result: i32) {
    if source != 0 && result != 0 {
        let s = (source ^ result) >> 31;
        let mut updated = (*weight ^ s) + (i32::from(delta) - s);

        if updated > 1024 {
            updated = 1024;
        }

        *weight = (updated ^ s) - s;
    }
}
