// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::LIMIT_ONES;
use symphonia_core::errors::{Error, Result, decode_error};

pub(super) struct WavPackBitReader<'a> {
    pub(super) data: &'a [u8],
    pub(super) pos: usize,
    pub(super) sr: u32,
    pub(super) bc: u32,
}

impl<'a> WavPackBitReader<'a> {
    pub(super) fn new(data: &'a [u8]) -> Self {
        WavPackBitReader {
            data,
            pos: 0,
            sr: 0,
            bc: 0,
        }
    }

    pub(super) fn read_bit(&mut self) -> Result<u32> {
        if self.bc == 0 {
            let byte = self
                .data
                .get(self.pos)
                .ok_or(Error::DecodeError("wavpack: bitstream eof"))?;
            self.pos += 1;
            self.sr = u32::from(*byte);
            self.bc = 8;
        }

        let bit = self.sr & 1;
        self.sr >>= 1;
        self.bc -= 1;
        Ok(bit)
    }

    pub(super) fn ensure_bits(&mut self, nbits: u32) -> Result<()> {
        while self.bc < nbits {
            let byte = self
                .data
                .get(self.pos)
                .ok_or(Error::DecodeError("wavpack: bitstream eof"))?;
            self.pos += 1;
            self.sr |= u32::from(*byte) << self.bc;
            self.bc += 8;
        }

        Ok(())
    }

    pub(super) fn read_bits(&mut self, nbits: u32) -> Result<u32> {
        if nbits == 0 {
            return Ok(0);
        }

        self.ensure_bits(nbits)?;

        let value = self.sr & ((1u32 << nbits) - 1);
        self.sr >>= nbits;
        self.bc -= nbits;
        Ok(value)
    }

    pub(super) fn read_code(&mut self, maxcode: u32) -> Result<u32> {
        if maxcode < 2 {
            return if maxcode == 0 { Ok(0) } else { self.read_bit() };
        }

        let mut bitcount = 32 - maxcode.leading_zeros();
        let extras = (1 << bitcount) - maxcode - 1;
        let low_bits = self.read_bits(bitcount - 1)?;

        if low_bits >= extras {
            let high_bit = self.read_bit()?;
            Ok((low_bits << 1) - extras + high_bit)
        } else {
            bitcount -= 1;
            debug_assert_eq!(bitcount, 32 - maxcode.leading_zeros() - 1);
            Ok(low_bits)
        }
    }

    pub(super) fn read_limited_ones(&mut self) -> Result<u32> {
        let mut ones = 0;

        while ones < LIMIT_ONES + 1 && self.read_bit()? != 0 {
            ones += 1;
        }

        if ones == LIMIT_ONES + 1 {
            return decode_error("wavpack: invalid ones count");
        }

        if ones == LIMIT_ONES {
            let cbits = self.read_limited_ones()?;

            ones = if cbits < 2 {
                cbits
            } else {
                let mut mask = 1;
                let mut value = 0;

                for _ in 1..cbits {
                    if self.read_bit()? != 0 {
                        value |= mask;
                    }

                    mask <<= 1;
                }

                value | mask
            };

            ones += LIMIT_ONES;
        }

        Ok(ones)
    }
}
