// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::INT32_DATA;
use super::consts::WAVPACK_CODEC_INFO;
use super::consts::WAVPACK_HEADER_LEN;
use super::consts::WAVPACK_MARKER;
use super::decode_block::DecodeBlock;
use super::dsd_scratch::DsdScratch;
use super::expand::expand_matroska_packet;
use super::misc::generic_buffer_format;
use super::types::DecodedWord;
use super::types::DecorrPass;
use super::write::write_samples_to_buffer;
use log::debug;
use symphonia_core::audio::sample::SampleFormat;
use symphonia_core::audio::{AsGenericAudioBufferRef, AudioSpec, GenericAudioBuffer};
use symphonia_core::codecs::CodecInfo;
use symphonia_core::codecs::audio::well_known::CODEC_ID_WAVPACK;
use symphonia_core::codecs::audio::{
    AudioCodecParameters, AudioDecoder, AudioDecoderOptions, FinalizeResult,
};
use symphonia_core::codecs::registry::{RegisterableAudioDecoder, SupportedAudioCodec};
use symphonia_core::errors::{Error, Result, decode_error, unsupported_error};
use symphonia_core::io::{BufReader, ReadBytes};
use symphonia_core::packet::PacketRef;
use symphonia_core::support_audio_codec;

/// WavPack decoder.
pub struct WavPackDecoder {
    pub(super) params: AudioCodecParameters,
    pub(super) matroska_version: Option<u16>,
    pub(super) buf: GenericAudioBuffer,
    pub(super) residuals: Vec<DecodedWord>,
    pub(super) samples: Vec<i32>,
    pub(super) decorr_passes: Vec<DecorrPass>,
    pub(super) dsd_scratch: DsdScratch,
}

impl WavPackDecoder {
    pub fn try_new(params: &AudioCodecParameters, _opts: &AudioDecoderOptions) -> Result<Self> {
        if params.codec != CODEC_ID_WAVPACK {
            return unsupported_error("wavpack: invalid codec");
        }

        let sample_rate = params
            .sample_rate
            .ok_or(Error::Unsupported("wavpack: sample rate is required"))?;
        let channels = params
            .channels
            .clone()
            .ok_or(Error::Unsupported("wavpack: channels are required"))?;
        let sample_format = params.sample_format.unwrap_or(SampleFormat::S32);
        let capacity = params.max_frames_per_packet.unwrap_or(0) as usize;
        let matroska_version = params
            .extra_data
            .as_deref()
            .and_then(|extra| extra.get(..2))
            .map(|version| u16::from_le_bytes([version[0], version[1]]));

        let buf = GenericAudioBuffer::new(
            sample_format,
            AudioSpec::new(sample_rate, channels),
            capacity,
        );

        Ok(WavPackDecoder {
            params: params.clone(),
            matroska_version,
            buf,
            residuals: Vec::new(),
            samples: Vec::new(),
            decorr_passes: Vec::new(),
            dsd_scratch: DsdScratch::default(),
        })
    }

    pub(super) fn ensure_output_format(&mut self, sample_format: SampleFormat) -> Result<()> {
        if std::mem::discriminant(&generic_buffer_format(&self.buf))
            == std::mem::discriminant(&sample_format)
        {
            return Ok(());
        }

        if !self.buf.is_empty() {
            return decode_error("wavpack: packet changes sample format between blocks");
        }

        let spec = self.buf.spec().clone();
        let capacity = self.buf.capacity();
        self.buf = GenericAudioBuffer::new(sample_format, spec, capacity);
        self.params.sample_format = Some(sample_format);

        Ok(())
    }

    pub(super) fn decode_inner(&mut self, packet: &PacketRef<'_>) -> Result<()> {
        self.buf.clear();

        let expanded;
        let data = if packet.data.starts_with(&WAVPACK_MARKER) {
            packet.data
        } else if let Some(version) = self.matroska_version {
            expanded = expand_matroska_packet(packet.data, version)?;
            &expanded
        } else {
            return decode_error("wavpack: headerless packet without version");
        };

        let mut reader = BufReader::new(data);
        let mut channel_offset = 0;
        let output_channels = self.buf.spec().channels().count();

        while reader.pos() < data.len() as u64 {
            let pos = reader.pos() as usize;
            if data.len().saturating_sub(pos) < WAVPACK_HEADER_LEN {
                return decode_error("wavpack: truncated packet block");
            }

            let block = DecodeBlock::parse(&data[pos..])?;
            let (num_terms, has_entropy, has_primary_data, has_correction, has_extended_samples) =
                block.metadata_summary();
            reader.ignore_bytes(block.header.byte_len())?;

            if block.header.flags & INT32_DATA != 0 {
                debug!("wavpack packet contains extended int32 data");
            }

            self.ensure_output_format(block.header.sample_format()?)?;

            if !block.read_decorrelated_samples_into(
                &mut self.residuals,
                &mut self.samples,
                &mut self.decorr_passes,
                &mut self.dsd_scratch,
            )? {
                continue;
            }
            let block_channels = block.header.output_channels_in_block();

            write_samples_to_buffer(
                &mut self.buf,
                &self.samples,
                block.header.block_samples as usize,
                block_channels,
                channel_offset,
            )?;
            channel_offset += block_channels;

            debug!(
                "parsed wavpack block: terms={num_terms}, entropy={has_entropy}, primary={has_primary_data}, correction={has_correction}, extended={has_extended_samples}, samples={}",
                self.samples.len()
            );
        }

        if channel_offset == 0 {
            return decode_error("wavpack: packet contained no audio samples");
        }

        if channel_offset != output_channels {
            return decode_error("wavpack: packet channel count mismatch");
        }

        Ok(())
    }
}

impl AudioDecoder for WavPackDecoder {
    fn reset(&mut self) {
        self.buf.clear();
        self.residuals.clear();
        self.samples.clear();
        self.decorr_passes.clear();
        self.dsd_scratch.probabilities.clear();
        self.dsd_scratch.summed.clear();
        self.dsd_scratch.offsets.clear();
        self.dsd_scratch.lookup.clear();
    }

    fn codec_info(&self) -> &CodecInfo {
        &WAVPACK_CODEC_INFO
    }

    fn codec_params(&self) -> &AudioCodecParameters {
        &self.params
    }

    fn decode_ref(
        &mut self,
        packet: &PacketRef<'_>,
    ) -> Result<symphonia_core::audio::GenericAudioBufferRef<'_>> {
        if let Err(e) = self.decode_inner(packet) {
            self.buf.clear();
            Err(e)
        } else {
            Ok(self.buf.as_generic_audio_buffer_ref())
        }
    }

    fn finalize(&mut self) -> FinalizeResult {
        Default::default()
    }

    fn last_decoded(&self) -> symphonia_core::audio::GenericAudioBufferRef<'_> {
        self.buf.as_generic_audio_buffer_ref()
    }
}

impl RegisterableAudioDecoder for WavPackDecoder {
    fn try_registry_new(
        params: &AudioCodecParameters,
        opts: &AudioDecoderOptions,
    ) -> Result<Box<dyn AudioDecoder>>
    where
        Self: Sized,
    {
        Ok(Box::new(WavPackDecoder::try_new(params, opts)?))
    }

    fn supported_codecs() -> &'static [SupportedAudioCodec] {
        &[support_audio_codec!(CODEC_ID_WAVPACK, "wavpack", "WavPack")]
    }
}
