// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::BYTES_STORED;
use super::consts::DSD_FLAG;
use super::consts::FALSE_STEREO;
use super::consts::FLOAT_DATA;
use super::consts::MONO_FLAG;
use super::consts::SAMPLE_RATES;
use super::consts::SHIFT_LSB;
use super::consts::SHIFT_MASK;
use super::consts::SRATE_LSB;
use super::consts::SRATE_MASK;
use super::consts::WAVPACK_HEADER_LEN;
use super::consts::WAVPACK_MARKER;
use super::consts::WAVPACK_MAX_STREAM_VERSION;
use super::consts::WAVPACK_MIN_CK_SIZE;
use super::consts::WAVPACK_MIN_STREAM_VERSION;
use symphonia_core::audio::sample::SampleFormat;
use symphonia_core::errors::{Result, decode_error, unsupported_error};
use symphonia_core::io::{BufReader, ReadBytes};

#[derive(Clone, Debug)]
pub(super) struct WavPackBlockHeader {
    pub(super) ck_size: u32,
    pub(super) _version: u16,
    pub(super) block_index: u64,
    pub(super) total_samples: Option<u64>,
    pub(super) block_samples: u32,
    pub(super) flags: u32,
    pub(super) _crc: u32,
}

impl WavPackBlockHeader {
    pub(super) fn parse(src: &[u8]) -> Result<Self> {
        if src.len() < WAVPACK_HEADER_LEN || src[..4] != WAVPACK_MARKER {
            return decode_error("wavpack: invalid block header");
        }

        let mut reader = BufReader::new(&src[4..WAVPACK_HEADER_LEN]);
        let ck_size = reader.read_u32()?;

        if ck_size < WAVPACK_MIN_CK_SIZE {
            return decode_error("wavpack: invalid block size");
        }

        let version = reader.read_u16()?;

        if !(WAVPACK_MIN_STREAM_VERSION..=WAVPACK_MAX_STREAM_VERSION).contains(&version) {
            return unsupported_error("wavpack: unsupported stream version");
        }

        let block_index_hi = u64::from(reader.read_byte()?);
        let total_samples_hi = u64::from(reader.read_byte()?);
        let total_samples_lo = reader.read_u32()?;
        let block_index_lo = reader.read_u32()?;
        let block_samples = reader.read_u32()?;
        let flags = reader.read_u32()?;
        let crc = reader.read_u32()?;

        let total_samples = if total_samples_lo == u32::MAX {
            None
        } else {
            Some(u64::from(total_samples_lo) + (total_samples_hi << 32) - total_samples_hi)
        };

        Ok(WavPackBlockHeader {
            ck_size,
            _version: version,
            block_index: u64::from(block_index_lo) + (block_index_hi << 32),
            total_samples,
            block_samples,
            flags,
            _crc: crc,
        })
    }

    pub(super) fn byte_len(&self) -> u64 {
        u64::from(self.ck_size) + 8
    }

    pub(super) fn body_len(&self) -> usize {
        (self.ck_size - WAVPACK_MIN_CK_SIZE) as usize
    }

    pub(super) fn channels_in_block(&self) -> u16 {
        if self.flags & MONO_FLAG != 0 { 1 } else { 2 }
    }

    pub(super) fn bytes_per_sample(&self) -> u32 {
        (self.flags & BYTES_STORED) + 1
    }

    pub(super) fn shifted_bits(&self) -> u32 {
        (self.flags & SHIFT_MASK) >> SHIFT_LSB
    }

    pub(super) fn bits_per_sample(&self) -> u32 {
        self.bytes_per_sample() * 8 - self.shifted_bits()
    }

    pub(super) fn sample_rate_from_flags(&self) -> Option<u32> {
        let idx = ((self.flags & SRATE_MASK) >> SRATE_LSB) as usize;
        SAMPLE_RATES.get(idx).copied()
    }

    pub(super) fn output_channels_in_block(&self) -> usize {
        if self.flags & FALSE_STEREO != 0 {
            2
        } else if self.flags & MONO_FLAG != 0 {
            1
        } else {
            2
        }
    }

    pub(super) fn sample_format(&self) -> Result<SampleFormat> {
        if self.flags & DSD_FLAG != 0 {
            return Ok(SampleFormat::U8);
        }

        if self.flags & FLOAT_DATA != 0 {
            Ok(SampleFormat::F32)
        } else {
            match self.bytes_per_sample() {
                1 => Ok(SampleFormat::S8),
                2 => Ok(SampleFormat::S16),
                3 => Ok(SampleFormat::S24),
                4 => Ok(SampleFormat::S32),
                _ => decode_error("wavpack: invalid sample width"),
            }
        }
    }
}
