// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::ID_LARGE;
use super::consts::ID_ODD_SIZE;
use super::consts::ID_UNIQUE;
use super::consts::WAVPACK_HEADER_LEN;
use super::types::WavPackBlock;
use super::types::WavPackMetadata;
use symphonia_core::errors::{Result, decode_error};

pub(super) struct WavPackMetadataIter<'a> {
    pub(super) data: &'a [u8],
    pub(super) pos: usize,
}

impl<'a> WavPackMetadataIter<'a> {
    pub(super) fn new(block: &'a WavPackBlock) -> Self {
        Self::new_data(&block.data[WAVPACK_HEADER_LEN..])
    }

    pub(super) fn new_data(data: &'a [u8]) -> Self {
        WavPackMetadataIter { data, pos: 0 }
    }
}

impl<'a> Iterator for WavPackMetadataIter<'a> {
    type Item = Result<WavPackMetadata<'a>>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.data.len().saturating_sub(self.pos) < 2 {
            return None;
        }

        let mut id = self.data[self.pos];
        self.pos += 1;

        let mut byte_len = usize::from(self.data[self.pos]) << 1;
        self.pos += 1;

        if id & ID_LARGE != 0 {
            id &= !ID_LARGE;

            if self.data.len().saturating_sub(self.pos) < 2 {
                return Some(decode_error("wavpack: invalid large metadata size"));
            }

            byte_len += usize::from(self.data[self.pos]) << 9;
            self.pos += 1;
            byte_len += usize::from(self.data[self.pos]) << 17;
            self.pos += 1;
        }

        if id & ID_ODD_SIZE != 0 {
            if byte_len == 0 {
                return Some(decode_error("wavpack: invalid odd metadata size"));
            }

            id &= !ID_ODD_SIZE;
            byte_len -= 1;
        }

        let padded_len = byte_len + (byte_len & 1);

        if self.data.len().saturating_sub(self.pos) < padded_len {
            return Some(decode_error("wavpack: metadata overruns block"));
        }

        let data = &self.data[self.pos..self.pos + byte_len];
        self.pos += padded_len;

        Some(Ok(WavPackMetadata {
            id: id & ID_UNIQUE,
            data,
        }))
    }
}
