// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::FINAL_BLOCK;
use super::consts::INITIAL_BLOCK;
use super::consts::WAVPACK_FORMAT_INFO;
use super::consts::WAVPACK_HEADER_LEN;
use super::is::is_trailing_metadata_marker;
use super::make::make_codec_params;
use super::read::read_block;
use super::read::read_block_header_with_marker;
use super::read::read_block_with_marker;
use super::types::WavPackBlock;
use super::types::WavPackPacketBlocks;
use log::{debug, info};
use std::io::{ErrorKind, Seek, SeekFrom};
use symphonia_core::codecs::CodecParameters;
use symphonia_core::errors::{Error, Result, SeekErrorKind, decode_error, seek_error};
use symphonia_core::formats::prelude::*;
use symphonia_core::formats::probe::{ProbeFormatData, ProbeableFormat, Score, Scoreable};
use symphonia_core::io::{MediaSource, MediaSourceStream, ReadBytes, ScopedStream};
use symphonia_core::meta::{Metadata, MetadataLog};
use symphonia_core::support_format;
use symphonia_core::units::{Duration, Timestamp};

/// WavPack native block reader.
pub struct WavPackReader<'s> {
    pub(super) reader: MediaSourceStream<'s>,
    pub(super) media_info: MediaInfo,
    pub(super) tracks: Vec<Track>,
    pub(super) metadata: MetadataLog,
    pub(super) chapters: Option<ChapterGroup>,
    pub(super) pending: Option<WavPackBlock>,
    pub(super) total_samples: Option<u64>,
    pub(super) next_ts: Timestamp,
}

impl<'s> WavPackReader<'s> {
    pub fn try_new(mut mss: MediaSourceStream<'s>, opts: FormatOptions) -> Result<Self> {
        let marker = mss.read_quad_bytes()?;
        let first = read_block_with_marker(&mut mss, marker)?;

        let codec_params = make_codec_params(&first)?;
        let total_samples = first.header.total_samples;

        let mut track = Track::new(0);

        if let Some(total_samples) = total_samples {
            track
                .with_num_frames(total_samples)
                .with_duration(Duration::from(total_samples));
        }

        track.with_codec_params(CodecParameters::Audio(codec_params));

        let media_info = MediaInfo::from_track(&track);

        Ok(WavPackReader {
            reader: mss,
            media_info,
            tracks: vec![track],
            metadata: opts.external_data.metadata.unwrap_or_default(),
            chapters: opts.external_data.chapters,
            pending: Some(first),
            total_samples,
            next_ts: Timestamp::new(0),
        })
    }

    pub(super) fn next_block(&mut self) -> Result<Option<WavPackBlock>> {
        if let Some(block) = self.pending.take() {
            Ok(Some(block))
        } else {
            read_block(&mut self.reader)
        }
    }

    pub(super) fn next_audio_block(&mut self) -> Result<Option<WavPackBlock>> {
        while let Some(block) = self.next_block()? {
            if block.header.block_samples != 0 {
                return Ok(Some(block));
            }

            debug!("skipping non-audio wavpack block");
        }

        Ok(None)
    }

    pub(super) fn read_packet_blocks(&mut self) -> Result<Option<WavPackPacketBlocks>> {
        if let Some(total_samples) = self.total_samples
            && self.next_ts.get() >= 0
            && self.next_ts.get() as u64 >= total_samples
        {
            return Ok(None);
        }

        let Some(first) = self.next_audio_block()? else {
            return Ok(None);
        };

        let ts = Timestamp::new(first.header.block_index as i64);
        let dur = Duration::from(u64::from(first.header.block_samples));
        let mut packet = Vec::from(first.data.as_ref());
        let mut saw_final = first.header.flags & FINAL_BLOCK != 0;

        if first.header.flags & INITIAL_BLOCK == 0 {
            info!("wavpack packet starts on a non-initial block");
        }

        while !saw_final {
            let Some(block) = self.next_audio_block()? else {
                return decode_error("wavpack: unterminated multichannel packet");
            };

            if block.header.block_index != ts.get() as u64 {
                return decode_error("wavpack: multichannel block index mismatch");
            }

            if block.header.block_samples != dur.get() as u32 {
                return decode_error("wavpack: multichannel block duration mismatch");
            }

            saw_final = block.header.flags & FINAL_BLOCK != 0;
            packet.extend_from_slice(&block.data);
        }

        self.next_ts = Timestamp::new(ts.get().saturating_add(dur.get() as i64));

        Ok(Some((ts, dur, packet.into_boxed_slice())))
    }

    pub(super) fn scan_seek_target(
        &mut self,
        required_ts: Timestamp,
        mode: SeekMode,
    ) -> Result<Option<(u64, Timestamp)>> {
        self.reader.seek(SeekFrom::Start(0))?;

        let mut best_before: Option<(u64, Timestamp)> = None;
        let mut first_after: Option<(u64, Timestamp)> = None;

        loop {
            let block_offset = self.reader.pos();
            let marker = match self.reader.read_quad_bytes() {
                Ok(marker) => marker,
                Err(err) if err.kind() == ErrorKind::UnexpectedEof => break,
                Err(err) => return Err(err.into()),
            };

            if is_trailing_metadata_marker(marker) {
                break;
            }

            let header = read_block_header_with_marker(&mut self.reader, marker)?;
            let packet_ts = Timestamp::new(header.block_index as i64);

            if header.block_samples != 0 && header.flags & INITIAL_BLOCK != 0 {
                if packet_ts <= required_ts {
                    best_before = Some((block_offset, packet_ts));
                } else if first_after.is_none() {
                    first_after = Some((block_offset, packet_ts));
                    if mode == SeekMode::Coarse {
                        break;
                    }
                }
            }

            let remaining = header.byte_len().saturating_sub(WAVPACK_HEADER_LEN as u64);
            self.reader.ignore_bytes(remaining)?;
        }

        if mode == SeekMode::Coarse {
            Ok(first_after.or(best_before))
        } else {
            Ok(best_before)
        }
    }
}

impl Scoreable for WavPackReader<'_> {
    fn score(_src: ScopedStream<&mut MediaSourceStream<'_>>) -> Result<Score> {
        Ok(Score::Supported(255))
    }
}

impl ProbeableFormat<'_> for WavPackReader<'_> {
    fn try_probe_new(
        mss: MediaSourceStream<'_>,
        opts: FormatOptions,
    ) -> Result<Box<dyn FormatReader + '_>> {
        Ok(Box::new(WavPackReader::try_new(mss, opts)?))
    }

    fn probe_data() -> &'static [ProbeFormatData] {
        &[support_format!(
            WAVPACK_FORMAT_INFO,
            &["wv", "wvp", "wavpack"],
            &["audio/wavpack", "audio/x-wavpack"],
            &[b"wvpk"]
        )]
    }
}

impl FormatReader for WavPackReader<'_> {
    fn format_info(&self) -> &FormatInfo {
        &WAVPACK_FORMAT_INFO
    }

    fn media_info(&self) -> &MediaInfo {
        &self.media_info
    }

    fn metadata(&mut self) -> Metadata<'_> {
        self.metadata.metadata()
    }

    fn chapters(&self) -> Option<&ChapterGroup> {
        self.chapters.as_ref()
    }

    fn seek(&mut self, mode: SeekMode, to: SeekTo) -> Result<SeekedTo> {
        if !self.reader.is_seekable() {
            return seek_error(SeekErrorKind::Unseekable);
        }

        let track = self
            .tracks
            .first()
            .ok_or(Error::SeekError(SeekErrorKind::Unseekable))?;
        let required_ts = match to {
            SeekTo::Timestamp { ts, .. } => ts,
            SeekTo::Time { time, .. } => {
                let tb = track
                    .time_base
                    .ok_or(Error::SeekError(SeekErrorKind::Unseekable))?;
                tb.calc_timestamp(time)
                    .ok_or(Error::SeekError(SeekErrorKind::OutOfRange))?
            }
        };

        if required_ts.get() < 0 {
            return seek_error(SeekErrorKind::OutOfRange);
        }

        if let Some(total_samples) = self.total_samples
            && required_ts.get() as u64 > total_samples
        {
            return seek_error(SeekErrorKind::OutOfRange);
        }

        let (offset, actual_ts) = if required_ts == Timestamp::new(0) {
            (0, Timestamp::new(0))
        } else {
            self.scan_seek_target(required_ts, mode)?
                .ok_or(Error::SeekError(SeekErrorKind::OutOfRange))?
        };

        self.reader.seek(SeekFrom::Start(offset))?;
        self.pending = read_block(&mut self.reader)?;
        self.next_ts = actual_ts;

        Ok(SeekedTo {
            track_id: 0,
            actual_ts,
            required_ts,
        })
    }

    fn tracks(&self) -> &[Track] {
        &self.tracks
    }

    fn next_packet(&mut self) -> Result<Option<Packet>> {
        match self.read_packet_blocks()? {
            Some((ts, dur, data)) => Ok(Some(Packet::new(0, ts, dur, data))),
            None => Ok(None),
        }
    }

    fn into_inner<'s>(self: Box<Self>) -> MediaSourceStream<'s>
    where
        Self: 's,
    {
        self.reader
    }
}
