// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::DIV0;
use super::consts::DIV1;
use super::consts::DIV2;
use super::consts::HYBRID_BALANCE;
use super::consts::HYBRID_BITRATE;
use super::consts::HYBRID_FLAG;
use super::consts::SLO;
use super::consts::SLS;
use super::is::is_mono;
use super::types::DecodedWord;
use super::types::EntropyVars;
use super::types::HybridProfile;
use super::wav_pack_bit_reader::WavPackBitReader;
use super::wp::wp_exp2s;
use super::wp::wp_log2;
use symphonia_core::errors::Result;

#[derive(Clone, Debug)]
pub(super) struct WordsDecoder {
    pub(super) entropy: EntropyVars,
    pub(super) hybrid: Option<HybridProfile>,
    pub(super) error_limit: [u32; 2],
    pub(super) flags: u32,
    pub(super) holding_one: u32,
    pub(super) holding_zero: bool,
    pub(super) zeros_acc: u32,
    pub(super) mono: bool,
}

impl WordsDecoder {
    pub(super) fn new(entropy: EntropyVars, hybrid: Option<HybridProfile>, flags: u32) -> Self {
        WordsDecoder {
            entropy,
            hybrid,
            error_limit: [0; 2],
            flags,
            holding_one: 0,
            holding_zero: false,
            zeros_acc: 0,
            mono: is_mono(flags),
        }
    }

    pub(super) fn get_med(&self, chan: usize, med: usize) -> u32 {
        (self.entropy.median[chan][med] >> 4) + 1
    }

    pub(super) fn inc_med(&mut self, chan: usize, med: usize) {
        let div = match med {
            0 => DIV0,
            1 => DIV1,
            _ => DIV2,
        };

        self.entropy.median[chan][med] += ((self.entropy.median[chan][med] + div) / div) * 5;
    }

    pub(super) fn dec_med(&mut self, chan: usize, med: usize) {
        let div = match med {
            0 => DIV0,
            1 => DIV1,
            _ => DIV2,
        };

        self.entropy.median[chan][med] -= ((self.entropy.median[chan][med] + (div - 2)) / div) * 2;
    }

    pub(super) fn medians_are_low(&self) -> bool {
        self.entropy.median[0][0] < 2 && self.entropy.median[1][0] < 2
    }

    pub(super) fn update_slow_level_for_zero(&mut self, chan: usize) {
        if let Some(hybrid) = self.hybrid.as_mut() {
            hybrid.slow_level[chan] =
                hybrid.slow_level[chan].wrapping_sub((hybrid.slow_level[chan] + SLO) >> SLS);
        }
    }

    pub(super) fn read_zero_run(&mut self, bs: &mut WavPackBitReader<'_>) -> Result<bool> {
        if self.zeros_acc != 0 {
            self.zeros_acc -= 1;

            return Ok(self.zeros_acc != 0);
        }

        let cbits = bs.read_limited_ones()?;

        self.zeros_acc = if cbits < 2 {
            cbits
        } else {
            let mut mask = 1;
            let mut value = 0;

            for _ in 1..cbits {
                if bs.read_bit()? != 0 {
                    value |= mask;
                }

                mask <<= 1;
            }

            value | mask
        };

        if self.zeros_acc != 0 {
            self.entropy.median = [[0; 3]; 2];
            return Ok(true);
        }

        Ok(false)
    }

    pub(super) fn update_error_limit(&mut self) {
        let Some(hybrid) = self.hybrid.as_mut() else {
            return;
        };

        hybrid.bitrate_acc[0] = hybrid.bitrate_acc[0].wrapping_add(hybrid.bitrate_delta[0]);
        let mut bitrate_0 = (hybrid.bitrate_acc[0] >> 16) as i32;

        if self.mono {
            self.error_limit[0] = if self.flags & HYBRID_BITRATE != 0 {
                let slow_log_0 = ((hybrid.slow_level[0] + SLO) >> SLS) as i32;
                if slow_log_0 - bitrate_0 > -0x100 {
                    wp_exp2s(slow_log_0 - bitrate_0 + 0x100) as u32
                } else {
                    0
                }
            } else {
                wp_exp2s(bitrate_0) as u32
            };
        } else {
            hybrid.bitrate_acc[1] = hybrid.bitrate_acc[1].wrapping_add(hybrid.bitrate_delta[1]);
            let mut bitrate_1 = (hybrid.bitrate_acc[1] >> 16) as i32;

            if self.flags & HYBRID_BITRATE != 0 {
                let slow_log_0 = ((hybrid.slow_level[0] + SLO) >> SLS) as i32;
                let slow_log_1 = ((hybrid.slow_level[1] + SLO) >> SLS) as i32;

                if self.flags & HYBRID_BALANCE != 0 {
                    let balance = (slow_log_1 - slow_log_0 + bitrate_1 + 1) >> 1;

                    if balance > bitrate_0 {
                        bitrate_1 = bitrate_0 * 2;
                        bitrate_0 = 0;
                    } else if -balance > bitrate_0 {
                        bitrate_0 *= 2;
                        bitrate_1 = 0;
                    } else {
                        bitrate_1 = bitrate_0 + balance;
                        bitrate_0 -= balance;
                    }
                }

                self.error_limit[0] = if slow_log_0 - bitrate_0 > -0x100 {
                    wp_exp2s(slow_log_0 - bitrate_0 + 0x100) as u32
                } else {
                    0
                };

                self.error_limit[1] = if slow_log_1 - bitrate_1 > -0x100 {
                    wp_exp2s(slow_log_1 - bitrate_1 + 0x100) as u32
                } else {
                    0
                };
            } else {
                self.error_limit[0] = wp_exp2s(bitrate_0) as u32;
                self.error_limit[1] = wp_exp2s(bitrate_1) as u32;
            }
        }
    }

    pub(super) fn read_word(
        &mut self,
        bs: &mut WavPackBitReader<'_>,
        mut correction_bits: Option<&mut WavPackBitReader<'_>>,
        chan: usize,
    ) -> Result<DecodedWord> {
        if self.holding_zero {
            self.holding_zero = false;
            let mut low = 0;
            let mut high = self.get_med(chan, 0) - 1;
            self.dec_med(chan, 0);

            if self.flags & HYBRID_FLAG != 0 && chan == 0 {
                self.update_error_limit();
            }

            if self.error_limit[chan] == 0 {
                low += bs.read_code(high - low)?;
            } else {
                let mut mid = (high + low + 1) >> 1;

                while high - low > self.error_limit[chan] {
                    if bs.read_bit()? != 0 {
                        low = mid;
                    } else {
                        high = mid - 1;
                    }

                    mid = (high + low + 1) >> 1;
                }

                low = mid;
            }

            let sign = bs.read_bit()?;

            let correction = if let Some(correction_bits) = correction_bits.as_mut() {
                if self.error_limit[chan] != 0 {
                    let value = correction_bits.read_code(high - low)? + low;
                    if sign != 0 {
                        low as i32 - value as i32
                    } else {
                        value as i32 - low as i32
                    }
                } else {
                    0
                }
            } else {
                0
            };

            if self.flags & HYBRID_BITRATE != 0
                && let Some(hybrid) = self.hybrid.as_mut()
            {
                hybrid.slow_level[chan] =
                    hybrid.slow_level[chan].wrapping_sub((hybrid.slow_level[chan] + SLO) >> SLS);
                hybrid.slow_level[chan] = hybrid.slow_level[chan].wrapping_add(wp_log2(low) as u32);
            }

            return Ok(DecodedWord {
                value: if sign != 0 { !(low as i32) } else { low as i32 },
                correction,
            });
        }

        if self.medians_are_low() && self.holding_one == 0 && self.read_zero_run(bs)? {
            self.update_slow_level_for_zero(chan);
            return Ok(DecodedWord {
                value: 0,
                correction: 0,
            });
        }

        let raw_ones = bs.read_limited_ones()?;
        let mut ones_count = (raw_ones >> 1) + self.holding_one;
        self.holding_one = raw_ones & 1;
        self.holding_zero = (raw_ones & 1) == 0;

        if self.flags & HYBRID_FLAG != 0 && chan == 0 {
            self.update_error_limit();
        }

        let (mut low, high) = if ones_count == 0 {
            let high = self.get_med(chan, 0) - 1;
            self.dec_med(chan, 0);
            (0, high)
        } else {
            let mut low = self.get_med(chan, 0);
            self.inc_med(chan, 0);

            if ones_count == 1 {
                let high = low + self.get_med(chan, 1) - 1;
                self.dec_med(chan, 1);
                (low, high)
            } else {
                low += self.get_med(chan, 1);
                self.inc_med(chan, 1);
                ones_count -= 2;

                if ones_count == 0 {
                    let high = low + self.get_med(chan, 2) - 1;
                    self.dec_med(chan, 2);
                    (low, high)
                } else {
                    low += ones_count * self.get_med(chan, 2);
                    let high = low + self.get_med(chan, 2) - 1;
                    self.inc_med(chan, 2);
                    (low, high)
                }
            }
        };

        let mut high = high;
        low &= 0x7fff_ffff;
        high &= 0x7fff_ffff;

        if low > high {
            high = low;
        }

        let mut mid = (high + low + 1) >> 1;

        if self.error_limit[chan] == 0 {
            mid = bs.read_code(high - low)? + low;
        } else {
            while high - low > self.error_limit[chan] {
                if bs.read_bit()? != 0 {
                    low = mid;
                } else {
                    high = mid - 1;
                }

                mid = (high + low + 1) >> 1;
            }
        }

        let sign = bs.read_bit()?;
        let correction = if let Some(correction_bits) = correction_bits.as_mut() {
            if self.error_limit[chan] != 0 {
                let value = correction_bits.read_code(high - low)? + low;
                if sign != 0 {
                    mid as i32 - value as i32
                } else {
                    value as i32 - mid as i32
                }
            } else {
                0
            }
        } else {
            0
        };

        if self.flags & HYBRID_BITRATE != 0
            && let Some(hybrid) = self.hybrid.as_mut()
        {
            hybrid.slow_level[chan] =
                hybrid.slow_level[chan].wrapping_sub((hybrid.slow_level[chan] + SLO) >> SLS);
            hybrid.slow_level[chan] = hybrid.slow_level[chan].wrapping_add(wp_log2(mid) as u32);
        }

        Ok(DecodedWord {
            value: if sign != 0 { !(mid as i32) } else { mid as i32 },
            correction,
        })
    }

    pub(super) fn read_words_into(
        &mut self,
        bs: &mut WavPackBitReader<'_>,
        mut correction_bits: Option<&mut WavPackBitReader<'_>>,
        samples: usize,
        out: &mut Vec<DecodedWord>,
    ) -> Result<()> {
        let channels = if self.mono { 1 } else { 2 };
        out.clear();
        out.reserve(samples * channels);

        for i in 0..samples * channels {
            let chan = if self.mono { 0 } else { i & 1 };
            out.push(self.read_word(bs, correction_bits.as_deref_mut(), chan)?);
        }

        Ok(())
    }

    #[cfg(test)]
    pub(super) fn read_words(
        &mut self,
        bs: &mut WavPackBitReader<'_>,
        correction_bits: Option<&mut WavPackBitReader<'_>>,
        samples: usize,
    ) -> Result<Vec<DecodedWord>> {
        let mut out = Vec::new();
        self.read_words_into(bs, correction_bits, samples, &mut out)?;
        Ok(out)
    }
}
