// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::consts::EXP2_TABLE;
use super::consts::LOG2_TABLE;

pub(super) fn wp_exp2s(log: i32) -> i32 {
    if log < 0 {
        return !wp_exp2s(-log).wrapping_sub(1);
    }

    let value = u32::from(EXP2_TABLE[(log & 0xff) as usize]) | 0x100;
    let log = log >> 8;

    if log <= 9 {
        (value >> (9 - log)) as i32
    } else {
        (value << ((log - 9) & 0x1f)) as i32
    }
}

pub(super) fn wp_log2(mut value: u32) -> i32 {
    value = value.wrapping_add(value >> 9);

    if value < (1 << 8) {
        let dbits = if value == 0 {
            0
        } else {
            32 - value.leading_zeros()
        };
        (dbits << 8) as i32 + i32::from(LOG2_TABLE[((value << (9 - dbits)) & 0xff) as usize])
    } else {
        let dbits = 32 - value.leading_zeros();
        (dbits << 8) as i32 + i32::from(LOG2_TABLE[((value >> (dbits - 9)) & 0xff) as usize])
    }
}
