// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::prepare_output_buffer;
use symphonia_core::audio::sample::i24;
use symphonia_core::audio::{AudioMut, GenericAudioBuffer};
use symphonia_core::errors::{Error, Result, decode_error, unsupported_error};

pub(super) fn write_samples_to_buffer(
    buf: &mut GenericAudioBuffer,
    samples: &[i32],
    frames: usize,
    channels: usize,
    channel_offset: usize,
) -> Result<()> {
    if samples.len() != frames * channels {
        return decode_error("wavpack: invalid output sample count");
    }

    prepare_output_buffer(buf, frames)?;

    if channel_offset + channels > buf.spec().channels().count() {
        return decode_error("wavpack: packet has too many channels");
    }

    match buf {
        GenericAudioBuffer::U8(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, |sample| {
                sample as u8
            })
        }
        GenericAudioBuffer::S8(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, |sample| {
                sample as i8
            })
        }
        GenericAudioBuffer::S16(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, |sample| {
                sample as i16
            })
        }
        GenericAudioBuffer::S24(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, i24::from)
        }
        GenericAudioBuffer::S32(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, |sample| {
                sample
            })
        }
        GenericAudioBuffer::F32(buf) => {
            write_integer_samples(buf, samples, frames, channels, channel_offset, |sample| {
                f32::from_bits(sample as u32)
            })
        }
        _ => unsupported_error("wavpack: unsupported output sample format"),
    }
}

pub(super) fn write_integer_samples<S, F>(
    buf: &mut symphonia_core::audio::AudioBuffer<S>,
    samples: &[i32],
    frames: usize,
    channels: usize,
    channel_offset: usize,
    mut convert: F,
) -> Result<()>
where
    S: symphonia_core::audio::sample::Sample,
    F: FnMut(i32) -> S,
{
    match channels {
        1 => {
            let plane = buf
                .plane_mut(channel_offset)
                .ok_or(Error::DecodeError("wavpack: invalid output channel"))?;

            for (dst, &sample) in plane.iter_mut().zip(samples.iter()).take(frames) {
                *dst = convert(sample);
            }
        }
        2 => {
            let (left, right) = buf
                .plane_pair_mut(channel_offset, channel_offset + 1)
                .ok_or(Error::DecodeError("wavpack: invalid output channels"))?;

            for (frame, lr) in samples.chunks_exact(2).enumerate().take(frames) {
                left[frame] = convert(lr[0]);
                right[frame] = convert(lr[1]);
            }
        }
        _ => return decode_error("wavpack: invalid output channel count"),
    }

    Ok(())
}
